### ISSUE TITLE
Grading system colours can not be distinguished by colour-blind persons

### ISSUE THREAD

**Issue by NielsLeenheer** [WebPlatformTest/HTML5test#1]
The grading system with the colours for 'non-existant', 'good', 'great' etc. are a colour-blind person's nightmare. :-) Can't tell the difference between most of them!

/via Ben Nunns

**Comment by bbarry** [comment]
Might I suggest:

```
#results ul li em.good {
    color: #33C3E7;
}
#results ul li em.great {
    color: #003AAE;
}
```

or something similar.

The problems for me are roughly reasonable==good and badly==great. 

http://kuler.adobe.com/#themeID/1203478
