### ISSUE TITLE
Button formmethod, formaction and formenctype

### ISSUE THREAD

**Issue by zanona** [WebPlatformTest/HTML5test#102]
Perhaps it would be interesting to add these, since they are very useful somehow, although it seems only firefox implements it:

https://developer.mozilla.org/en/HTML/Element/button#section_7

Cheers ;)

**Comment by NielsLeenheer** [comment]
If I am not mistaken, these properties were removed from HTML5 after Mozilla finished their implementation. Earlier versions of html5test.com had test for these properties, but they were removed to make it in line with the spec.
