### ISSUE TITLE
noValidate attribute is tested against the wrong element

### ISSUE THREAD

**Issue by mounirlamouri** [WebPlatformTest/HTML5test#103]
noValidate attribute seems to be tested on the input element but it should be tested on the form element.
For the input element, there is formNoValidate attribute (which is already tested).

As a result, no browser passes this test (as far as tested, which means Chromium, Opera Next and Firefox).

Unfortunately, I can't provide a patch given that the github repository isn't up to date.

**Comment by DongwooIm** [comment]
I agree with mounirlamouri. "input" element doesn't need to have "noValidate" attribute.

**Comment by NielsLeenheer** [comment]
Fixed
