### ISSUE TITLE
The score of keygen is something wrong.

### ISSUE THREAD

**Issue by DongwooIm** [WebPlatformTest/HTML5test#104]
"Minimal element support" of keygen element is 'partial'  on Chrome, Safari, Opera, and FireFox.

But the "pass" condition below is true on Chrome and Opera, when I test with only the line of code.
(typeof HTMLKeygenElement != 'undefined' && element.firstChild instanceof HTMLKeygenElement && 'challenge' in element.firstChild && 'keytype' in element.firstChild)

I think this is weird, but I don't know why.

Is there anyone has an idea of it?
Please let me know the reason of this weird situation.

**Comment by NielsLeenheer** [comment]
The keygen element has been implement in various browsers, but none were compatible with the spec. What these browser did was whenever they encountered a keygen element, they created a select element with some preset option elements. These implementation get 'partial' credit. There was a bug however that tested the wrong element and caused even proper implementations to get credited as 'partial'.
