### ISSUE TITLE
offsetWidth attribute is not a member of input element.

### ISSUE THREAD

**Issue by DongwooIm** [WebPlatformTest/HTML5test#105]
In the "input type=image" test case,
for "width" case, html5test check input element has "width" attribute and "offsetWidth" attribute.
For "height" case, html5test check input element has "height" attribute and "offsetHeight" attribute.

But, in the HTML5 spec, "offsetWidth" and "offset Height" is not a member of input element, as I know.
(http://www.w3.org/TR/html5/the-input-element.html#the-input-element)

In my opinion, just check the "width" and "height" attribute is enough for those cases.

Please check this issue.

**Comment by NielsLeenheer** [comment]
OffsetWidth and offsetHeight are not the properties being tested. They are only used for checking if the width and height properties actually make the input element change its width and height in the rendered document.
