### ISSUE TITLE
The JS Notifications property is spelt incorrectly.

### ISSUE THREAD

**Issue by Arpita** [WebPlatformTest/HTML5test#107]
The Notifications property for Webkit is currently spelt as "webkitNotification" whereas the specification says that it should be "webkitNotifications" with an 's' at the end.

The property should be window.webkitNotifications and not window.webkitNotification.

Kindly rectify the same.

**Comment by vijayanbits** [comment]
Yes. I observed the same too. The "Notifications" section has this bug. 
The "s" needs to be added according to the spec. The test case needs to be changed.

**Comment by leonzy** [comment]
the test remains unchanged. why is this issue closed? do you mean you won't fix this?

**Comment by NielsLeenheer** [comment]
It has been fixed in the upcoming update. You can try it at beta.html5test.com.

Cheers,
Niels

Sent from my iPhone

On 16 dec. 2011, at 04:07, leonzy
reply@reply.github.com
wrote:

**Comment by leonzy** [comment]
thanks.!!!

On Fri, Dec 16, 2011 at 6:35 PM, Niels Leenheer <
reply@reply.github.com
