### ISSUE TITLE
Form novalidate test in html5test.com

### ISSUE THREAD

**Issue by gurpreetkaur** [WebPlatformTest/HTML5test#111]
The novalidate test case for "Forms Validation" in Section "Forms" is incorrect. The novalidate attribute is for form elements and not for input element.
http://www.w3.org/TR/html5/the-input-element.html#the-input-element
Its creating a var element = document.createElement('input'); and then checking novalidate on it ,which is incorrect.
Kindly update the test site.

**Comment by Arpita** [comment]
The "novalidate" attribute is an attribute of the form element and not of the input element. Hence the test case fails.

Please update the same on the website.

**Comment by Arpita** [comment]
This issue has been fixed on the beta version of the site: beta.html5test.com

**Comment by NielsLeenheer** [comment]
Arpita is correct. This has been fixed on beta.html5test.com and will be part of the next update

**Comment by gurpreetkaur** [comment]
Thanks for the update. Please change the html5test.com site.Many are using this site to check scores of HTML5.
