### ISSUE TITLE
HTML editing support for Android - ICS browsers

### ISSUE THREAD

**Issue by Arpita** [WebPlatformTest/HTML5test#112]
This is regarding the html5test.com site's content editable test case.

This test case currently puts all Android browsers in the blocked list and thus even though Android browsers (the ICS flavor) support contenteditable property and do launch the IME to enable the user to edit the content, they still remain in the blocked list and hence are unable to pass this test case.

Because of this, we are losing out on 17 points.

The blocked list adds all mobile and tablet user-agents and as per your test site any Android user-agent shall either be classified as a mobile or a tablet user-agent.

Request you to please verify the contenteditable support (on ICS browser) and change the test case accordingly so that ICS based Android browsers are able to pass the test cases.

**Comment by NielsLeenheer** [comment]
I just confirmed contenteditable support on Android 4. This is great news! I will remove Android 4 and higher from the blacklist in the next update.

**Comment by Arpita** [comment]
Thank-you for the verification.
