### ISSUE TITLE
Nokia Lumia 800 (Windows Phone 7.5) won't run all the tests

### ISSUE THREAD

**Issue by Tronic** [WebPlatformTest/HTML5test#113]
"Your browser scores 42 and 1 bonus point out of a total of 62 points"

Apparently only parsing, canvas and video tests get run as other categories don't appear on the page at all (nor in the total score).

**Comment by NielsLeenheer** [comment]
Could you try again. I could have been a temporary issue, because I am getting proper scores from other Windows Phone 7.5 devices right now.

**Comment by Tronic** [comment]
Actually it seems to depend on Internet Explorer settings. If I choose "Website preference: Desktop version", the test works properly and "Mobile Internet Explorer 9.0 on Windows Phone 7.5" is detected. If I choose "Mobile version" (the default), the test fails to run (only 62 total points) and it says "You are using undefined".

**Comment by NielsLeenheer** [comment]
Ok, could you got to http://whatsmyuseragent.com/ with your browser in mobile mode and paste the user agent of your phone in this bug report?

**Comment by Tronic** [comment]
Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 800)

**Comment by NielsLeenheer** [comment]
Seems to work fine right now.
