### ISSUE TITLE
Please add an UA in the test.

### ISSUE THREAD

**Issue by JohnBear** [WebPlatformTest/HTML5test#118]
Hi,  please add the UA[360EE] support for 360 Extreme Explorer in the test.

360 Extreme Explorer is a fameous browser widely used in China. It follows the chromium open source group, provides powerful and convenient features for Chinese, fix bugs for the chromium group too.
Now, we find that it can't be detected in http://html5test.com/. 
Please consider supporting it, you will be much appreciated.

The codes are like this:
if (ua.match('360EE')) {
  detected.browser.stock = false;
  detected.browser.name = '360 Extreme Explorer';
  detected.browser.version = null;
}

**Comment by JohnBear** [comment]
The website for downloading 360 Extreme Explorer is http://chrome.360.cn/

**Comment by JohnBear** [comment]
Our group think that http://html5test.com/ is very good, so we translate it, put the Chinese version in http://chrome.360.cn/test/html5/index.html.
Hope you like it.

**Comment by JohnBear** [comment]
If you like the Chinese version of html5test.com, we are glad to give it to you, put it on your website.

**Comment by NielsLeenheer** [comment]
360 Extreme Explorer was added to the UA detection.

**Comment by JohnBear** [comment]
Thanks.

**Comment by NielsLeenheer** [comment]
Hi John, I like the Chinese translation a lot. I get quite a lot of visitors from China and having a Chinese translate is a great addition. I saw you updated the translation to the latest version a couple of times.

Unfortunately it is quite difficult to keep up with all of the smaller changes, so I've decided to add internationalisation support right into the main website. That way the translated websites are always up to date. Translations are added by a simple Javascript file which makes translating a lot easier. None of the other files need to be changed.

I've copied much of your Chinese translation and created this test site: http://beta.cn.html5test.com

Please take a look at it and I would be grateful for any suggestions you have. If by any chance you want to contribute missing translations, you can find the Chinese translation file here on Github: https://github.com/NielsLeenheer/html5test/blob/master/translations/cn/index.js

Thanks again,

Niels

**Comment by JohnBear** [comment]
I'm glad to see your reply.
We will take a look at beta.cn.html5test.com, and see what we can do for it.
Would you please give me your email address or other ways to connect you instantly?

**Comment by JohnBear** [comment]
I have added some translations into translations/cn/index.js.

**Comment by NielsLeenheer** [comment]
Hi John, you can contact me at niels@leenheer.nl

**Comment by JohnBear** [comment]
ok.Thanks!

2012-07-09

xiong peng

发件人：Niels Leenheer
发送时间：2012-07-09 17:50
主题：Re: [html5test] Please add an UA in the test. (#118)
收件人："JohnBear"xiongpeng524_@163.com
抄送：

Hi John, you can contact me at niels@leenheer.nl 

---

**Comment by NielsLeenheer** [comment]
Could make a pull request for both your patch-1 and your patch-2 branch. That way I can automatically pull in your changes. 

Cheers, 
Niels

**Comment by JohnBear** [comment]
Oops. I edit index.js in the browser directly other than git.
What do you mean a pull request for both of them?

2012-07-09

xiong peng

发件人：Niels Leenheer
发送时间：2012-07-09 18:46
主题：Re: [html5test] Please add an UA in the test. (#118)
收件人："JohnBear"xiongpeng524_@163.com
抄送：

Could make a pull request for both your patch-1 and your patch-2 branch. That way I can automatically pull in your changes.  

Cheers,  
Niels 

---

**Comment by NielsLeenheer** [comment]
I noticed you created two branches with extra translations on your fork of html5test: https://github.com/JohnBear/html5test/tree/patch-1 and https://github.com/JohnBear/html5test/tree/patch-2.

If you go to each one of these branches and click on the Pull Request button at the top of the screen, GitHub will allow me to automatically import your changes.

**Comment by JohnBear** [comment]
I've done it.
Thanks.

2012-07-09

xiong peng

发件人：Niels Leenheer
发送时间：2012-07-09 19:10
主题：Re: [html5test] Please add an UA in the test. (#118)
收件人："JohnBear"xiongpeng524_@163.com
抄送：

I noticed you created two branches with extra translations on your fork of html5test: https://github.com/JohnBear/html5test/tree/patch-1 and https://github.com/JohnBear/html5test/tree/patch-2. 

If you go to each one of these branches and click on the Pull Request button at the top of the screen, GitHub will allow me to automatically import your changes. 

---

**Comment by NielsLeenheer** [comment]
Thanks. I've just pulled your changes into the master branch and updated beta.cn.html5test.com.
