### ISSUE TITLE
Track support in Google Chrome

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#123]
I'm running the beta html5test with Google Chrome 16.0.912.75 and in the html5 subtitle support said that my browser don't support the subtitles. I have the track html5 option activated in the about:flags chrome's page, and in many pages the subtitles work for me.

An example of a page, that uses html5 subtitles:
http://www.storiesinflight.com/js_videosub/#example

PS: Sorry about my poor english, but I'm from Spain.

**Comment by joroldan** [comment]
Firefox also support that subtitles and fail in the test.

**Comment by ericduran** [comment]
The text seems to be correct. I just tested this on Chrome 19.0.1038.0 canary and the test pass.

Note: You need to enabled the track element in chrome://flags/

I can't really comment in firefox I didn't test it.

**Comment by NielsLeenheer** [comment]
Test seems to work fine in Chrome when enabled in about:flags. Firefox doesn't support subtitles, so it properly fails the test.
