### ISSUE TITLE
Menu support in Google Chrome

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#124]
I'm running Google Chrome 16.0.619.72, and the html5 beta test said that my web browser supports menu tag. I have found an example where it seems that it's is really not supported by chrome.

http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_menu

**Comment by NielsLeenheer** [comment]
Chome does support the menu tag, but only the list type, while Firefox also supports the context type. So far no browser supports the toolbar type. I've added tests for the different menu types on beta.html5test.com
