### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#125]
In the html5test (also in the beta), when you click the Subtitle Support link, you go to this page: 
http://www.w3.org/TR/html5/video.html#timed-text-tracks

I think that the link is broken because when you go to that page it says "Document Not Found"

Sorry about my poor English, but I'm from Spain.

**Comment by ghost** [comment]
Really, I think that this is not the only one that is broken. All the links in the Video section of the test seem to be broken.

**Comment by ghost** [comment]
The audio element link is also broken.

http://www.w3.org/TR/html5/video.html#audio

**Comment by NielsLeenheer** [comment]
Fixed broken links
