### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sanbornc** [WebPlatformTest/HTML5test#128]
I think there would be value in the following: 
- When viewing a requirement (such as local storage) it would be nice to be have a link that would take you to a screen that would allow you to see how that feature is supported by different browsers.  This would help me in determining if I want to uses the requirement.
- If from the other browsers tab, I could look click on a browser to see it's current support for each of the HTML 5 features, that would be valuable.

**Comment by David-Mulder** [comment]
Or you could simply link to http://caniuse.com/#search=featurename .
