### ISSUE TITLE
browser compare based on a subfeature omits feature as title.

### ISSUE THREAD

**Issue by hero-m** [WebPlatformTest/HTML5test#130]
when a feature is selected for comparison, it's name is shown on top of the column. but when a subfeature is selected, the feature name itself is omitted, which might not be clear. for example selecting "field types: output - minimal element support" only shows "minimal element support" as column title.

see here as example:
http://html5test.com/compare/feature/form-output-element/form-tel-element/form-fieldset-element.html

**Comment by NielsLeenheer** [comment]
Took a while, but fixed in the upcoming release...

<img width="523" alt="screen shot 2015-08-13 at 12 23 58" src="https://cloud.githubusercontent.com/assets/233230/9247766/3e817532-41b6-11e5-86a9-1de5f44a7f47.png">
