### ISSUE TITLE
Test `<input type=datetime>.valueAsDate`

### ISSUE THREAD

**Issue by kornelski** [WebPlatformTest/HTML5test#133]
`input.valueAsDate` doesn't seem to be implemented in any browser any more.

I'd expect this to return `Date` object:

```
$('<input type=datetime value="2012-04-16">')[0].valueAsDate
```

but I'm getting `null` in Opera 11.62, despite passing support for `input type=datetime` in the test.

**Comment by NielsLeenheer** [comment]
I'll add an test for valueAsDate in the next release.

**Comment by NielsLeenheer** [comment]
Added `valueAsDate` and `valueAsNumber` as a new test for the next release (currently at alpha.html5test.com). The result in the example you give above is as expected however. "2012-04-16" isn't a valid value for a datetime field. `valueAsDate` is null for invalid values.

The example below seems to work fine:

<pre>e = document.createElement('input');
e.type = 'date';
e.value='2010-10-10';
e.valueAsDate</pre>
