### ISSUE TITLE
Keygen support firefox should be at least partial

### ISSUE THREAD

**Issue by David-Mulder** [WebPlatformTest/HTML5test#134]
At the very least the front end of the keygen tag works: http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_keygen even if possible not entirely correct yet 

```
 https://developer.mozilla.org/en/Document_Object_Model_%28DOM%29/HTMLKeygenElement
```

**Comment by NielsLeenheer** [comment]
The keygen support in Firefox is a legacy and proprietary implementation that is not compatible with the HTML5 specification.

**Comment by David-Mulder** [comment]
The test page@w3schools I mentioned above returns the /exact/ same result as chrome. The real problem (as far as I know) is that the implementation is replacing the keygen tag with a selectbox, but still the frontend and submit work so partial marks seem to be valid (e.g. a test case which submit the form in question and observes the received data)
