### ISSUE TITLE
Add Dolphin Browser to mobile browsers

### ISSUE THREAD

**Issue by Sanaki** [WebPlatformTest/HTML5test#140]
Browser website: http://dolphin-browser.com/

Available on iOS and Android. I personally only use it on iOS, but it appears to have better HTML5 compatibility than Safari, better features across the board, and a desktop mode for bypassing sites that refuse to allow mobile viewers access to a usable form of the website. Known user agents below:

User agent, iOS, desktop viewing disabled:
Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; 6533.17.9) AppleWebKit/en_US (KHTML, like Gecko) Mobile/8C148 Safari/6533.18.5

User agent, iOS , desktop viewing enabled:
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en_US) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1

**Comment by NielsLeenheer** [comment]
Dolphin uses the system rendering engine as far as I know. Scores of Dolphin on Android would be similar to the stock browser on Android and Scores on iOS would be similar to Safari. 

Adding Dolphin would serve little purpose. You can see the results under the generic "Android x.x" and "iOS x.x" labels. Besides if I add Dolphin I would have to add dozens of similar mobile browsers too and I fear nobody is waiting for a list of a dozen browsers with the same scores.
