### ISSUE TITLE
Missing MachBlue XT 1.0 Browser in TV section

### ISSUE THREAD

**Issue by ralao** [WebPlatformTest/HTML5test#141]
MachBlue XT 1.0 is a Webkit based browser built by Bluestreak for TV OEMs. It is currently used in several Blurays and Connected TVs using Panasonic IC chipset.

MachBlue XT 1.0 reference platform is currently the leading scorer in the TV category with 362 points + 11 bonus points. Could you please add it to your highest scorer list?

Thanks in adavance for your assistance and do not hesitate to contact me shall you need further information.

Best Regards,

Rachad ALAO.

**Comment by NielsLeenheer** [comment]
Hi Rachad,

I will certainly add MachBlue XT to the TV section, but there are a couple of simple rules:

The browser or reference platform itself can be listed under the 'development' section. The 'current' section is strictly for currently shipping consumer products, but for each product the platform will be mentioned. To qualify for these sections I will need to be able to detect the manufacturer and product series, or the reference platform version from the user agent string.

To be included I will also need to know the following to things:
- Does your browser support contentEditable? Please test with http://html5demos.com/contenteditable
- Does your browser support HTML5 drag and drop? Please test with http://html5demos.com/drag

Cheers,

Niels

**Comment by ralao** [comment]
Hi Niels,

 Thanks for the follow-up. We would like to add MachBlue XT's reference platform to the development section only for now. We will resubmit a new ticket as soon as commercial devices start shipping with this version. Here is our user agent string:

 Mozilla/5.0 (U; Linux x86_64; en_CA.UTF-8) AppleWebKit/534.26+ (KHTML, like Gecko) mbxtWebKit/1.0.0 (gtk)

 As you can see, just matching "mbxtWebKit/{version}" should detect us.

 With respect to your two additional questions:
- Does your browser support contentEditable? Please test with  http://html5demos.com/contenteditable
  [Answer] Yes
- Does your browser support HTML5 drag and drop? Please test with  http://html5demos.com/drag
  [Answer] Not yet
  
  Thanks again for your help.
  
  Rachad ALAO.

**Comment by ralao** [comment]
Hi Niels,

 How are you? Do you need more info for us to add MachBlue XT to the TV section? Let me know.

 Best Regards,

 Rachad ALAO.

**Comment by ralao** [comment]
Hi Niels,

 I'm not sure if you receive this comment from the github bug, so I'm sending it again.

 Best Regards,

 Rachad ALAO.

# 

Hi Niels,

Thanks for the follow-up. We would like to add MachBlue XT's reference platform to the development section only for now. We will resubmit a new ticket as soon as commercial devices start shipping with this version. Here is our user agent string:

Mozilla/5.0 (U; Linux x86_64; en_CA.UTF-8) AppleWebKit/534.26+ (KHTML, like Gecko) mbxtWebKit/1.0.0 (gtk)

As you can see, just matching "mbxtWebKit/{version}" should detect us.

With respect to your two additional questions:
 •
Does your browser support contentEditable? Please test with http://html5demos.com/contenteditable
 [Answer] Yes

 •
Does your browser support HTML5 drag and drop? Please test with http://html5demos.com/drag
 [Answer] Not yet

Thanks again for your help.

Rachad ALAO.

-----Original Message-----

**Comment by NielsLeenheer** [comment]
The results will be updated soon. It didn't make the previous update because there were no recorded visits from MachBlue XT at the time. The user agent detection should be updated already.

**Comment by ralao** [comment]
Thanks for the update. We will re-run the test again to make sure we appear in the results just in case. Thanks again for your help.

 Best Regards,

 Rachad ALAO.

-----Original Message-----
