### ISSUE TITLE
Please add UA "Polaris" to the whitelist

### ISSUE THREAD

**Issue by SunChulBaek-2** [WebPlatformTest/HTML5test#143]
Hi, please add UA "Ploaris" to the whitelist.

Polaris Browser is famous browser widely used in Korea.

The UA "Polaris" is not in the whitelist, gets incorrect score.
Since version 8.0, we support contentEditable and drap and drop.
(We tested on http://html5demos.com/contenteditable and http://html5demos.com/drag.)

Please consider adding it, you will be much appreciated.

PS. How can I show the score of Polaris Browser in "others browsers" tab?

**Comment by NielsLeenheer** [comment]
Are you sure Drag and Drop actually works? And if so could you provide some more information about how you solved the problem of implementing drag and drop on touch screens? I'm quite curious because if this is true, Polaris would be the first mobile browser to support this.

**Comment by NielsLeenheer** [comment]
Also, I'm seeing multiple user agents mentioning Polaris, including one with just the string "Polaris". Could you tell a bit more about which platforms are supported by Polaris.

**Comment by SunChulBaek-2** [comment]
Polaris 8.0 support Android and Windows now.
We use user agents like "Mozilla/5.0 (Android 2.3.6; Windows NT 6.1) AppleWebkit/536.2 (KHTML, like Gecko) Polaris/8.0 3.20E.283320311 Safari/536.2"
(The user agent "Polaris" is our test to avoid whitelist block)

We finally decided to not support drag and drop on mobile device.
So we want Polaris 8.0 only to get the score of contentEditable.

Thank you.

**Comment by NielsLeenheer** [comment]
Polaris has been added to the whitelist
