### ISSUE TITLE
IE9 does not show D'n'D support

### ISSUE THREAD

**Issue by panzi** [WebPlatformTest/HTML5test#144]
For me IE 9 under Windows 7 (in a VirtualBox) did not show D'n'D support. I think it should even show _partial_ support for the D'n'D events in IE >= 5.5.

**Comment by NielsLeenheer** [comment]
This by design. Older versions of Internet Explorer do support some form of drag and drop, but this is not compatible with the HTML5 specification.

**Comment by panzi** [comment]
As I see it it's a subset of the HTML5 specification. After all IE invented the API and w3 extended it. Even the limited version of IE's D'n'D can be useful, so I think there should be more detail about what is supported.
