### ISSUE TITLE
Maxthon form implemenation

### ISSUE THREAD

**Issue by David-Mulder** [WebPlatformTest/HTML5test#146]
I just looked at the maxthon form fields implementation for date, datetime, etc. and it seems unfair to give them the same amount of points as say a real implementation chrome or firefox may come with, as right now they have simply used a type=number field with a mask. And either way I sort of question whether such an implementation deserves any points, as realistically nobody will /ever/ want to use it. (Open http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_input_type_date in maxthon)

**Comment by David-Mulder** [comment]
And btw type=color has a different button from the normal one, but it doesn't work at all as you can see when you open http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_input_type_color

**Comment by NielsLeenheer** [comment]
Looking into it.

**Comment by NielsLeenheer** [comment]
I created a blacklist for detecting custom UI for these field types and added Maxthon.

**Comment by wesleyzeng** [comment]
Maxthon 3.4.1.1000 supports color input completely, please check it. Thank you!

**Comment by NielsLeenheer** [comment]
I tested the color field on various machine and while it shows a
customized field, it did not allow me to change the color value.
Clicking on the field never popped up a color well.

On 4 jul. 2012, at 17:08, wesleyzeng
reply@reply.github.com
wrote:

**Comment by wesleyzeng** [comment]
Can you give me a test website or web page about color input. We check it http://www.w3schools.com/html5/tryit.asp?filename=tryhtml5_input_type_color, but it's fine.

**Comment by NielsLeenheer** [comment]
I've tried the w3schools.com test page you mentioned and while I do see the customized field and the default color, I can not change the color value. I've tested with Maxthon 3.4.1.1000 on both Windows Vista, Windows 7 and Windows 8.

**Comment by wesleyzeng** [comment]
The window color dialog has a trick. If you only click the color panel on the right side of the dialog and OK button, the color value will not be changed. After you click Add to custom Colors button or Basic colors of the dialog, the color value will change.

**Comment by wesleyzeng** [comment]
By the way, we will fix WebGL etc, as soon as quickly. Thank you!

**Comment by NielsLeenheer** [comment]
With the currently released version I do not see a color panel at all.
If I click on the color field nothing happens.

**Comment by wesleyzeng** [comment]
Sorry！I make a mistake. 3.4.2.1000 fixed color input, Subtitles (remove this feature), Webcam  (remove this feature), WebGL.

**Comment by wesleyzeng** [comment]
Anyway, Thank you!
