### ISSUE TITLE
Maxthon Betas & Firefox Nightly detection

### ISSUE THREAD

**Issue by warmth** [WebPlatformTest/HTML5test#149]
Why are Maxthon betas being detected as RTM versions?

"You are using Maxthon 3.3.9 on Windows 7"

And Firefox Nightly like Aurora?

"You are using Firefox Aurora 15.0a1 on Windows 7"

**Comment by NielsLeenheer** [comment]
As far as I know there is no way to distinguish between beta versions and rtm version of Maxthon.

**Comment by warmth** [comment]
You should post about it here: http://forum.maxthon.com/
