### ISSUE TITLE
Missing UC Mobile Browser in Mobiles test

### ISSUE THREAD

**Issue by abaddon12** [WebPlatformTest/HTML5test#153]
Hi  Niels:

I created issue #151 several days ago and  I'm not sure if you read it. Maybe I didn't make sense to you.

Could you just please add UA support for UC Mobile Browser in the Html5test process. 

UC Browser 8.5  of android platform is currently the leading scorer in the Mobiles category with 415 points + 7 bonus points. Our user-agent string in HTC One X is showed as follow:

"Mozilla/5.0 (Linux; U; Android 2.1-update1; zh-cn; HTC One X/ERE27) UC AppleWebKit/530+ (KHTML; like Gecko) Mobile Safari/530"

As you can see, just matching "UC" should detect us. 

You can get our product from http://www.uc.cn/product/product_ucbrowser_android.shtml. By the way, UC Browser 8.5  of android platform is not released yet, and it is coming soon. If you need to detect our product now, I can send it to you by e-mail. 

In addition, you can know about further information of UC Browser from http://www.ucweb.com/index.html. UC Browser is very famous mobile browser in China, and over half of mobile Internet users are using it. In India market, we get  more than 25% of market share. And our servers cover over 150 countries.

Thanks in adavance for your assistance and do not hesitate to contact me shall you need further information.

Best Regards,

Rocky Ding

**Comment by NielsLeenheer** [comment]
UC Browser is now supported
