### ISSUE TITLE
Score in "compare" is lower for Chrome

### ISSUE THREAD

**Issue by firewave** [WebPlatformTest/HTML5test#156]
With Chrome (tested with 19 and 21) the score in the "compare" view is lower than on the main page. It differs by 1 and it is caused by the "input type=file" detected as not supported in the compare view.

**Comment by NielsLeenheer** [comment]
The scores listed in the "compare" view are the most common recorded score and may differ from you own score due to differences in operating system, hardware support and other external factors.
