### ISSUE TITLE
MathML support

### ISSUE THREAD

**Issue by imuromtsev** [WebPlatformTest/HTML5test#157]
No one browser, except Firefox doesn't support mathml, but your tests pass it. Could you fix it?

**Comment by NielsLeenheer** [comment]
The test is not strictly about MathML being enabled, but if the parser knows how to deal with MathML syntax. It is required by the HTML5 parser specification.

**Comment by imuromtsev** [comment]
But it is wrong: seems like mathml tags processed with default tag parser.
So, it is no mean that browser supports embedding of MathML. You can use
http://www.mozilla.org/projects/mathml/demo/texvsmml.html test for check
it.

**Comment by NielsLeenheer** [comment]
Actually it isn't wrong. There are three possibilities:

a) The parser does not understand MathML in HTML5 notation
b) The parser does understand MathML in HTML5 notation, but the renderer does not understand MathML
c) The parser does understand MathML in HTML5 notation and the renderer also knows MathML.

Only a) is a failure on HTML5test. And only c) actually shows the rendered MathML. b) does not show rendered equations, but does follow the HTML5 spec properly on how to deal with embedded MathML content.

**Comment by dotnetCarpenter** [comment]
I see your point but like @timeking I think it's misleading. I thought that I could use html5test.com to track MathML support and believed it to be well supported until I actually tested the rendering.

I'm hoping that you'll reconsider this issue and use a detection algorithm similar to [MathJax](http://www.mathjax.org/demos/mathml). When selecting `MathML` in _Select the rendering mode:_, you get a warning if the renderer doesn't understand MathML.

**Comment by fred-wang** [comment]
MathJax does not have a reliable detection algorithm for MathML, it just checks the UA string or other browser-specific properties to try to guess which browser is used and indicates whether or not they have MathML support.

For an  example of how to test MathML by checking some metrics, see for example hasMathMLSupport() in https://developer.mozilla.org/en-US/docs/Web/MathML/Authoring#Fallback_for_Browsers_without_MathML_support

Similar JS tests are done in the MathML acid 3 test (https://github.com/fred-wang/AcidTestsMathML).

Of course, the goal of the test is perhaps not to test SVG/MathML at all, only the parsing rules defined in the HTML5 spec...
