### ISSUE TITLE
Fails on Nokia 5800 with DOM Exception 7

### ISSUE THREAD

**Issue by jviki** [WebPlatformTest/HTML5test#162]
Fails when loading in Nokia 5800 builtin browser with this message: 

> Error: NO_MODIFICATION_ALLOWED_ERR: DOM Exception 7

Tested on both http://html5test.com and http://beta.html5test.com.
In the beta it points to scripts/engine.js:1224 that is
`styles.innerHTML += "input[type=date]::-webkit-textfield-decoration-container, input[type=datetime]::-webkit-textfield-decoration-container, input[type=month]::-webkit-textfield-decoration-container, input[type=week]::-webkit-textfield-decoration-container, input[type=time]::-webkit-textfield-decoration-container, input[type=datetime-local]::-webkit-textfield-decoration-container { padding: 10px; }";`

**Comment by jviki** [comment]
Well, it looks to be fixed in master (3cc75842ab6269ca3733a68a1da80af2b4763c24), but fails on another more magic issue:
`URL: Line: 74
Error: Value undefined (result expression y.proxyMessage) is not object.`
But this is probably because I do not run the PHP part of that thing.

**Comment by NielsLeenheer** [comment]
The first error should be fixed. The second one is a mystery, I have no idea where it comes from.
