### ISSUE TITLE
New Browsers (Chrome, Firefox, Dolphin Engine)

### ISSUE THREAD

**Issue by yeahmann** [WebPlatformTest/HTML5test#163]
Desktop betas:
Chrome Beta
Chrome Dev
Firefox Beta
Firefox Aurora
Firefox Nightly

Mobile betas:
Firefox Beta (oddly you have Aurora)
Firefox Nightly
Dolphin Engine Beta (Dolphin HD just uses the Android rendering APIs but Engine does its own).

**Comment by kurtextrem** [comment]
Actually Chrome Dev is recognized as Chrome Nightly while there is no Chrome Nightly.
Chrome Nightly would be either Chrome Canary or Chromium (while Chromium has less codex support I think)

**Comment by niutech** [comment]
+1 for Dolphin Jetpack, Maxthon and Opera Dev (19 by now)
