### ISSUE TITLE
Html5test.com breaks on Windows 7 & IE 8

### ISSUE THREAD

**Issue by sivakotee** [WebPlatformTest/HTML5test#169]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MS-RTC LM 8)
Timestamp: Sat, 30 Jun 2012 09:53:00 UTC

Message: Unknown runtime error
Line: 1
Char: 19934
Code: 0
URI: http://html5test.com/scripts/engine.js

**Comment by NielsLeenheer** [comment]
Fixed...

**Comment by sivakotee** [comment]
Great.

it's working fine.

On Tue, Jul 3, 2012 at 5:22 PM, Niels Leenheer <
reply@reply.github.com
