### ISSUE TITLE
Support for section elements, Firefox reports 0/7

### ISSUE THREAD

**Issue by fvsch** [WebPlatformTest/HTML5test#17]
Hi,

I was wondering why Firefox 3.5 and 3.6 fails all the tests for the section elements. What level of support is expected exactly?

Contrarily to IE6-9, Firefox does support styling and scripting on these elements. As their role is mainly to add semantic meaning, this is quite enough for most needs. What might be seen as missing is a browser default style for these elements, mostly declaring them all as "display:block".
Is this what you are testing? Chrome passes the test and does have user agent styles (a simple "display:block" in most cases) for these elements.

**Comment by NielsLeenheer** [comment]
There are two basic requirements for the section elements:
-  The DOM object must be of the HTMLElement type (see spec 4.4)
-  The default style must be 'display: block' (see spec 10.2.2)

The current version of the test only checks the first. The next version of the test will check both.

Firefox current fails both tests.

**Comment by fvsch** [comment]
Thank you for this information. I think you can close this issue.
On the Firefox side, I reported a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=559284
(Might be a duplicate of existing bugs, though i didn’t find them.)

**Comment by NielsLeenheer** [comment]
Thanks for filing the bug. I was planning to, but haven't gotten around to it yet.

**Comment by nickolay** [comment]
"The default style must be 'display: block' (see spec 10.2.2)"

You meant 12.2.2:
http://www.whatwg.org/specs/web-apps/current-work/multipage/rendering.html#display-types

**Comment by NielsLeenheer** [comment]
Actually 10.2.2 is correct.

We are talking about the same section, but I referenced the official working draft published by the W3C: http://www.w3.org/TR/html5/
