### ISSUE TITLE
LG NetCast 2012 html5 score is incorrect/outdated

### ISSUE THREAD

**Issue by jcbiznoff** [WebPlatformTest/HTML5test#170]
Testing on the actual TV set reads 318. (35 from user interaction. Drag and Drop is partially supported).

From emulator version 2.1, the score reads 284.  (additional 2 comes from input type=number, customer user interface)

Thanks

**Comment by NielsLeenheer** [comment]
Scores on the current version of html5test.com will no longer be updated. A new version will be released in about a week with different scoring rules.
