### ISSUE TITLE
Typo in Fullscreen test

### ISSUE THREAD

**Issue by c-a** [WebPlatformTest/HTML5test#176]
According to the spec: http://dvcs.w3.org/hg/fullscreen/raw-file/tip/Overview.html#dom-element-requestfullscreen the function name is requestFullscreen() and not requestFullScreen() with a capital S.

**Comment by c-a** [comment]
Note that mozRequestFullScreen() and webkitRequestFullScreen() seem to be spelled with a capital S though.

**Comment by Hanrui** [comment]
Chromium supports both the minuscule styled function name as well as the legacy capital one. So testing webkitRequestFullscreen is also okay for Chrome and Chromium.

**Comment by homm** [comment]
I vote for this issue. Opera implement fullscreen support, but this test fail.
http://my.opera.com/ODIN/blog/2012/08/28/colourful-opera-12-50-snapshot

**Comment by NielsLeenheer** [comment]
Will be fixed in the next update.
