### ISSUE TITLE
notifications test should contain a sub item of HTMLNotification

### ISSUE THREAD

**Issue by LittleShadow** [WebPlatformTest/HTML5test#178]
Some browsers (for example, Maxthon) doesn't support HTMLNotification but does support normal notification, well, even without any permission request nor warning showing to the end users (imho, this is against the spec too).

So I think it's better to split the notification item into two sub items to make the scores more reasonable.

**Comment by NielsLeenheer** [comment]
Because there are no implementations of the new spec at this time I am willing to accept the old specification as scoring full points. This may change in future versions of html5test.com.
