### ISSUE TITLE
Sogou 4.0 doesn't support Notifications nor Local multimedia

### ISSUE THREAD

**Issue by LittleShadow** [WebPlatformTest/HTML5test#179]
But it gets all the points!
Not to mention all the new form elements.

Check all of these features on Sogou, and you'll see that it actually cannot support any of them.

**Comment by NielsLeenheer** [comment]
In the upcoming version of html5test.com I have added Sogou to the blacklist for: 
- various field types
- full screen support
- notifications
- getUserMedia
- subtitles

**Comment by puppywang** [comment]
Hi, we have release a new version of SogouExplroer 4.0, with all blacklisted function fixed. Please check it at http://download.ie.sogou.com/se/sogou_explorer_4.0_newpreview.exe. Thanks!
