### ISSUE TITLE
Web Intent should be tested

### ISSUE THREAD

**Issue by jldupont** [WebPlatformTest/HTML5test#190]
http://webintents.org/

**Comment by webtester** [comment]
Probably not. It is not clear what the spec will look like. There are few different proposals.

**Comment by NielsLeenheer** [comment]
I'm hesitant about adding Web Intents at this time. Are there plans from other browser vendors for supporting this spec?

**Comment by PaulKinlan** [comment]
It is currently removed from Chrome.
