### ISSUE TITLE
Baidu browser support

### ISSUE THREAD

**Issue by ilteronder** [WebPlatformTest/HTML5test#191]
Baidu browser does not show anything on the html5test.com page with default settings.

**Comment by niutech** [comment]
+1 for adding Baidu browser! And it should be crowned the top browser, scoring 467 points: https://lh3.googleusercontent.com/-vpf50064Xt0/UETM9Myyy9I/AAAAAAAALig/3J4EUbqDYUk/w480-h480/SC20120903-142923.png

Here is its user agent: https://lh6.googleusercontent.com/-gmXlSKTnP9c/UETM9gH3awI/AAAAAAAALi4/Ts7dGfFXTvY/w480-h480/SC20120903-143452.png

**Comment by niutech** [comment]
Any updates?

**Comment by NielsLeenheer** [comment]
Baidu Browser is currently on our blacklist. The only reason they have such a high score is because they claim to support features that they don't.
