### ISSUE TITLE
Chart is not accurate

### ISSUE THREAD

**Issue by Geompse** [WebPlatformTest/HTML5test#192]
On this page : http://html5test.com/results/desktop.html
The bottom chart "Timeline" 's lines are rounded, it is beautiful, i know, but it is not relevant for the analysis.

For example, take the IE path. From v8 to v9, nothing evolved.
V8 is from 03/2009 and V9 from 03/2011 : in 03/2010 the IE score was (probably) the same as in 03/2009 = 42
On the chart you can read for this time a score around 60.

I think you should use straight lines (like this : _|) ; and if you want to keep some nice effects you can round "corners".

Geompse

**Comment by NielsLeenheer** [comment]
Will be fixed in the next update.

**Comment by Geompse** [comment]
Thank you, that's way much better !

On the production site there is a dot for "IE11 <unreleased>", but not on the test site.
To me, unreleased versions are irrelevant in the timeline because at the current time only the already released version must be used. It would be nice if you could draw a straight line from the last dot to the present time ? Something like _|¨¨ (but not dashed).
Of course, you can restore the "IE11" dot ;)
Sorry if you were expecting me to open another issue, but this seems related ("chart accuracy").

Regards,
Geompse
