### ISSUE TITLE
Please support the updated BB10 user agent

### ISSUE THREAD

**Issue by touchthedesign** [WebPlatformTest/HTML5test#193]
Hello,
I'm writing you on behalf of the BlackBerry Browser team. Incase you're not aware we've recently updated the forthcoming BB10 Browser's user agent. The new user agent is as follows:

<strong>Mozilla/5.0 (BB10; &lt;Device Model&gt;) AppleWebKit/&lt;WebKit Version&gt; (KHTML, like Gecko) Version/&lt;BB Version #&gt; Mobile Safari/&lt;WebKit Version&gt;</strong>

<em>were the items in &lt; &gt; will wary</em>

We'd like to make sure your site is properly testing against the updated UA.

More info on the update can be found here:

http://devblog.blackberry.com/2012/08/blackberry-10-user-agent-string/

We love your site, please keep up the great work :)

If you have any questions, or would like to chat offline please shoot me a PM.

Thanks, Romeo

**Comment by NielsLeenheer** [comment]
Thanks for the heads-up. I'll add this to the UA detection library.

BTW, I'll be at BlackBerry Jam in Amsterdam next week. Do you know if there will be somebody from the browser team? I'd love talk a bit about the future of the BlackBerry browser.

**Comment by NielsLeenheer** [comment]
Hi Romeo, I've just added support for the BB10 user agent. This also means the blacklist for drag and drop is working again, which should prevent a false positive.

**Comment by touchthedesign** [comment]
That's awesome news Niels :) We're you able to link up with Laurent this past weekend?

**Comment by NielsLeenheer** [comment]
Yes, I had a great talk with Laurent during PhoneGap day and also with Luca at BlackBerry 10 Jam. If you have any more issues or know of any bugs, please let me know and I'll look into it.
