### ISSUE TITLE
hyperlink download attribute

### ISSUE THREAD

**Issue by liser25** [WebPlatformTest/HTML5test#194]
Please, add to the test support of a hyperlink download attribute.

eg. <a href="http://example.com/" download="foo.bar">example</a>

It's a very useful thing, but currently supported by chrome only. 

http://developers.whatwg.org/links.html#attr-hyperlink-download

**Comment by NielsLeenheer** [comment]
Added to the list of potential new tests for the next update

**Comment by NielsLeenheer** [comment]
Will be added to the next release of html5test.com
