### ISSUE TITLE
GNOME Web doesn't appear in the results page

### ISSUE THREAD

**Issue by bochecha** [WebPlatformTest/HTML5test#195]
GNOME Web (also known as Epiphany) scores quite well at the HTML5 test:
- 3.2.2 gets 338 points plus 14 bonus points
- 3.4.1 gets 345 points plus 15 bonus points
- 3.5.90 (the development version) gets 363 points plus 15 bonus points

That's a similar score to recent versions of Firefox and Safari.

Would it be possible to have it appear in the "other browsers" and
"compare" tabs, as a desktop browser? (preferably as "GNOME Web", that's
its new user-visible name since 3.4.0)

**Comment by paulirish** [comment]
is GNOME Web maintained? Last I went sleuthing I didnt find activity.  Can
you point to work within their web platform improvements?

**Comment by bochecha** [comment]
It is under active development:
http://git.gnome.org/browse/epiphany/log/

And it should go on improving quite a lot in the future, as GNOME has ambitious plans for overhauling the whole browsing experience:
https://live.gnome.org/Design/Apps/Web

As for the actual platform powering GNOME Web, it's WebKitGtk, the Gtk port of WebKit. As you can see, there are regular (and recent) releases:
https://trac.webkit.org/browser/releases/WebKitGTK

So yeah, it's a pretty active project. :)

**Comment by paulirish** [comment]
Cool! thanks for the heads up. Coming from the github side of open source
sometimes its hard to poke into the linux-y communities and identify the
activity centers. :) Thanks

**Comment by niutech** [comment]
Any updates? Web is still absent on beta.html5test.com

**Comment by NielsLeenheer** [comment]
I don't have the time to maintain Gnome Web as a separate browser on HTMLtest. But the browser itself and version updates will be accepted as a PR as long as it is frequently maintained. See https://github.com/WebPlatformTest/Data for more information.
