### ISSUE TITLE
incorrect test result for "input type=file"

### ISSUE THREAD

**Issue by azuo** [WebPlatformTest/HTML5test#197]
iOS5 does not support file uploading, but the following test result says it does support "input type=file":

http://html5test.com/compare/browser/ios50.html

I think we can't consider a browser support "input type=file" if it just allows and renders that tag, but makes the rendered control disabled permanently, and never performs the correct action that should be taken by the tag.

**Comment by NielsLeenheer** [comment]
I'll look into it.

**Comment by NielsLeenheer** [comment]
Will be fixed in the next release of html5test.com
