### ISSUE TITLE
HTML logo not rendered properly on main page when device pixel ratio > 2.0 

### ISSUE THREAD

**Issue by swypych** [WebPlatformTest/HTML5test#199]
html5test.com's main.css has the following code around line 122
# html5 {

```
float: right; 
display: block;
width: 74px;
height: 102px;
margin: 16px 0 10px 10px;
background: url(/images/html5.png);
background-size: 74px 102px;
```

}

@media only screen and (-webkit-min-device-pixel-ratio: 2) {
    #html5 {
        background: url(/images/html5@2x.png);
    }
}

With device pixel ratios greater than 2.0, the inner block is considered. The inner block's background property overrides the earlier background-size property (since background is a shorthand for setting background image, size, position, repeat, color and probably another couple of things) so it will revert to taking the image's actual size and proportion for determining how to display.

This means the device will only see the top-left quadrant of the html5 crest.

To fix this, you could change the inner 'background' to a 'background-image' so that the previous background-size wins.

**Comment by NielsLeenheer** [comment]
Will be fixed in the next release of html5test.com
