### ISSUE TITLE
Missing a browser: sogou, 470+15 points

### ISSUE THREAD

**Issue by darkclip** [WebPlatformTest/HTML5test#201]
sogou browser should be the top browser of html5test, 470+15 bonus points with the browser version 4.0. 2. actually it's always running ahead of others, but html5test never put it up.

**Comment by NielsLeenheer** [comment]
I'm sorry, but at this time I will not add Sogou to the results pages. 

As it is right now, it is little more than a shell around Chromium with all experimental features enabled. And many of these experimental features do not even work. In the next release of html5test.com I have added Sogou Explorer to various blacklists and it will not score as high as in the current version.
