### ISSUE TITLE
Dolphin Browser Blacklisted for getUserMedia 

### ISSUE THREAD

**Issue by kremsr** [WebPlatformTest/HTML5test#205]
Any reason that we are blacklisted here for this feature?  We would be more than happy to address any concerns with the functionality. 

getUserMedia: Browsers.isBrowser('Maxthon') || Browsers.isBrowser('UC Browser') || Browsers.isBrowser('Dolphin'),

Thanks,
Ryan 
Dolphin Browser

**Comment by NielsLeenheer** [comment]
The latest beta of Dolphin does seem to support getUserMedia(), but all tests I tried seem to fail. It seems like it fails to capture actual data from the camera.

**Comment by kremsr** [comment]
We are currently looking into this issue, and will provide updates once available.

**Comment by kremsr** [comment]
Updated Beta build for Dolphin (V 1.1.1)  is available which has improved performance for getUserMedia()
https://play.google.com/store/apps/details?id=com.dolphin.browser.lab.en
