### ISSUE TITLE
Incorrect and 

### ISSUE THREAD

**Issue by pascalgerritsen** [WebPlatformTest/HTML5test#206]
I tested Chrome 22.0.1229.79 and came across an incorrect test result:

It does support mpeg4, or at least I can just play mpeg4 videos

Also html5test tests for the <time> element, but html5 has dropped that and it's now replaced with the <data> element. It's scored as basic html5, not as bonus points.

(I hope I made myself clear, really tired right now)

**Comment by NielsLeenheer** [comment]
Could you please try http://beta.html5test.com/testcases/video/  On a clean install of Chrome on my computer it does not support playing plain MPEG4 files. So the test seems to be correct in that regard.

The second part of your report is missing the names of the element that is being tested and with what it is replaced with.
