### ISSUE TITLE
Lacking Opera Mobile.

### ISSUE THREAD

**Issue by ledahulevogyre** [WebPlatformTest/HTML5test#209]
I can't see Opera Mobile in "current" list.
http://html5test.com/results/mobile.html
Only "older".

Current version is 12.10

I think it's important because that's one of the top mobile browser.

**Comment by NielsLeenheer** [comment]
I am not collecting any new results for the current version of html5test at the moment. A new version with updated results will be released soon.

**Comment by ledahulevogyre** [comment]
Then why don't you keep the last version you tested (12.00) in the "current" list. Now it's like if Opera Mobile doesn't exist anymore.
