### ISSUE TITLE
Test for SVG support

### ISSUE THREAD

**Issue by Zirroz** [WebPlatformTest/HTML5test#21]
Just as Geolocation, for example, isn't part of HTML5, SVG has lately been mentioned a lot together with HTML5, and a test for the main parts would be nice.

The SVG parts I suggest testing for is:

SVG Filters
SVG Text
SVG Shapes
SVG Gradients
SVG Animation
SVG Fonts

(I am not an SVG expert so I'm not completely sure what to test for, but I know that Animation and Fonts doesn't have complete implementations in even the most modern browsers)

But, a simple test for any SVG support at all, could be OK too.

**Comment by johndrinkwater** [comment]
SVG is a must needed test for this site (I would argue it’s more relevant to HTML5 than h264 testing (which has never been in the standard)).
I assume you’d need example code and a sample rendering per test, with a canvas comparison script to confirm? unsure how you’d do test in IE without bundling the IEcanvas js.

**Comment by NielsLeenheer** [comment]
Even though this test does include specs that are not strictly HTML5, they are related to the HTML5 spec either as they were developed originally by the WHATWG or they were developed in roughly the same time frame. 

SVG is a completely separate spec, that has been around for a while. I think SVG deserves a test in its own right, but not as part of html5test.com. Perhaps svgtest.com?

The only thing that I am willing to include at this time is embedding SVG inside an HTML5 document, which is something that is directly related to HTML5 and part of the spec (4.8.15).

**Comment by ghost** [comment]
A big fat +1 for svgtest.com, could you please start to work on it? :D

(Please remove H.264 from being tested) http://www.osnews.com/story/23236/Why_Our_Civilization_s_Video_Art_and_Culture_is_Threatened_by_the_MPEG-LA

**Comment by NielsLeenheer** [comment]
Re: Removing H.264 tests:
Absolutely not!

**Comment by ghost** [comment]
"Absolutely not!"
And why is that? I think it is widely agreed that H.264 is not healthy for the open-web.

(Response for svgtest.com?)

**Comment by NielsLeenheer** [comment]
That is only widely agreed among Ogg Theora advocates.

**Comment by ghost** [comment]
"That is only widely agreed among Ogg Theora advocates."... Whom in which think the web should be open, and not patent encumbered. Think, what if you had to pay large royalties for jpeg and png...

**Comment by robrussell** [comment]
SVG is included in the html5 spec - at least the version here http://dev.w3.org/html5/spec/Overview.html#svg-0

Please move the video argument to a different thread (not saying it's not important but it's not about SVG)

**Comment by NielsLeenheer** [comment]
Added test for parsing SVG in text/html. Other SVG tests will not be part of html5test.com
