### ISSUE TITLE
Please Add Baidu Mobile Browser

### ISSUE THREAD

**Issue by jiazheng** [WebPlatformTest/HTML5test#210]
Please Add Baidu Mobile Browser, it is currently available on Android(https://play.google.com/store/apps/details?id=com.baidu.browser.apps). It got 482 and 11 bonus points which is the highest score i have ever seen.

**Comment by niutech** [comment]
Exactly, why is there no Baidu Browser in HTML5Test? It scored 482 points, as pictured [here](http://www.techinasia.com/baidu-mobile-browser-pics/), so it's the top score!
The same request was in issue #191 and there is still no response from @NielsLeenheer.

**Comment by NielsLeenheer** [comment]
Baidu Browser is currently on our blacklist. The only reason they have such a high score is because they claim to support features that they don't.

**Comment by jiazheng** [comment]
Which features that they claim to support but they don't?

**Comment by jiazheng** [comment]
Which features?

----- 原始邮件 -----
发件人：Niels Leenheer notifications@github.com
收件人：NielsLeenheer/html5test html5test@noreply.github.com
抄送人：jz kvg452@sina.com
主题：Re: [html5test] Please Add Baidu Mobile Browser (#210)
日期：2013年04月04日 03点44分
