### ISSUE TITLE
XHR Level 2 score are jumping

### ISSUE THREAD

**Issue by leoyanggit** [WebPlatformTest/HTML5test#225]
- Chromium 18.0.1025.168 (Developer Build 134367 Linux) Ubuntu 11.10: Jumping between 394 and 399

When the score is 394:
  Upload files    Yes
  Text response type    No
  Document response type    No
  Array buffer response type    No
  Blob response type    No

When the score is 397:
  Upload files    Yes
  Text response type    Yes
  Document response type    Yes
  Array buffer response type    No
  Blob response type    No

When the score is 399:
  Upload files    Yes
  Text response type    Yes
  Document response type    Yes
  Array buffer response type    Yes
  Blob response type    No
- FireFox 17.0.1 on Ubuntu 11.10: Jumping between 386 and 392 

When the score is 386:
  Upload files    Yes
  Text response type    Yes
  Document response type    No
  Array buffer response type    No
  Blob response type    No

When the score is 388:
  Upload files    Yes
  Text response type    Yes
  Document response type    Yes
  Array buffer response type    No
  Blob response type    No

When the score is 392:
  Upload files    Yes
  Text response type    Yes
  Document response type    Yes
  Array buffer response type    Yes
  Blob response type    Yes

**Comment by NielsLeenheer** [comment]
Could you test again with beta.html5test.com?

**Comment by NielsLeenheer** [comment]
Fixed
