### ISSUE TITLE
IndexDB blob read/write & Blob URI

### ISSUE THREAD

**Issue by DrYSG** [WebPlatformTest/HTML5test#226]
Can you add these items to the File API.

IndexDB Blob read/write ?
Blob URI

Here is a very short Javascript to test for this:

http://jsbin.com/eruhof/2/edit

I have been having great trouble finding out any mobile support for this. (and you are saying that Chrome v23 supports indexdb, but it does not support blobs on windows at least).

**Comment by NielsLeenheer** [comment]
Do you know of any desktop or mobile browser that does support blobs?

**Comment by NielsLeenheer** [comment]
Added to the next version of html5test.

**Comment by DrYSG** [comment]
To answer your question: IE10 and FireFox desktop both support binary blobs. Chromium is adding it now.
