### ISSUE TITLE
Chrome Beta for Android

### ISSUE THREAD

**Issue by nawoa** [WebPlatformTest/HTML5test#227]
A few hours ago, the Chrome Beta for Android was released.  This is separate from the standard Chrome app, which is based on Chrome 18 (IIRC).  The beta version is based on Chrome 25 and shares an updated codebase.  The difference is fairly significant as I'll show below.

Chrome for Android 18.0.1025469:  385+11 ( http://i.minus.com/iFIaNXaaUrbzn.png )

Chrome for Android Beta 25.0.1364.8: 422+11 ( http://i.minus.com/isFJB5dG8KGXg.png )

Can HTML5 support tracking please be added to HTML5Test?

Thanks for your consideration

**Comment by NielsLeenheer** [comment]
Done
