### ISSUE TITLE
Please check for Opus audio codec support

### ISSUE THREAD

**Issue by nawoa** [WebPlatformTest/HTML5test#228]
The very remarkable new Opus audio codec, designed for very low latency, low bitrate, high quality audio, has recently been approved as an open standardized web codec by the IETF, and is expected to be mandatory in the final WebRTC specification.

Aside from my own personal enthusiasm for such a promising new codec, I'm also very interested as a web developer to know whether it would be useful and productive for me to begin offering it on sites I manage.

According to webrtc.org, Chrome version 24 supports Opus and both Mozilla and Opera either already include support or are committed to adding support in the near future.  It's in the process of being implemented in a new version of Skype (now owned my Microsoft), and it's also been implemented in (or is in the process of implementation in) a wide variety of other software such as VLC, TeamSpeak, Mumble, and the ffmpeg library.

Clearly it's a very important and relevant test for modern browsers, so can you please add a check in HTML5Test to see if it's supported?  I'm unsure if it's supposed to be available using simply the <audio> tag (I certainly hope so) or if it will only be required to be available in conjunction with WebRTC.

(I don't see testing for WebRTC in HTML5Test either, so it might also be worth considering)

Thank you

**Comment by NielsLeenheer** [comment]
Opus is already part of the current version of html5test.com. I expect WebRTC to be added to the next version.
