### ISSUE TITLE
Test the <device /> tag.

### ISSUE THREAD

**Issue by livin52** [WebPlatformTest/HTML5test#23]
Simply that.

**Comment by Zirroz** [comment]
Isn't that way too undefined to be tested right now? It's even been said by the spec editors that it is meant for HTML6/HTML.next, and not HTML5, and that it is only located in the HTML5 spec for discussion.

**Comment by NielsLeenheer** [comment]
Agreed. Once a more definate spec is released it should become part of html5test.com, but for now, it is not ready yet.
