### ISSUE TITLE
Changing UserAgent string gets higher score on a qtwebkit based browser

### ISSUE THREAD

**Issue by pejakm** [WebPlatformTest/HTML5test#231]
Probably this applies to all qtwebkit based browsers (using qtwebkit 2.3), but I'll just give an example with QupZilla:

With the default UserAgent string score is **380**.
If I change UserAgent string by removing `Safari` and `QupZilla` and adding Chrome I get a score of **398**. The diference is in `User interaction` section.

My thought is that qtwebkit 2.3 (v537.21) supports everything from the `User Interaction` section but it's somehow ignored if browser UA string does not contain Chrome.

**Comment by nowrep** [comment]
The user agent is: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) QupZilla/1.3.5 Safari/537.21`

**Comment by pejakm** [comment]
Actually, even if I use latest Opera user agent string I get a full 398 points.

**Comment by NielsLeenheer** [comment]
The reason for this behavior is that contentEditable and drag and drop
cannot be reliably detected. Basically everybody says it supports it. There
is a whitelist for both that requires at least a desktop environment. This
usually pretty easy to detect, except for Linux. Linux could be pretty much
anything, from mobile to television and desktop to a car entertainment
system.

Unless the user agent contains a distribution name it is classified as
generic and will fail the interaction tests.

Some of the more common browsers also trigger the desktop environment, so
that is why changing the user agent will cause this behavior.

**Comment by pejakm** [comment]
Perhaps adding a check for `AppleWebKit/537.21`? If the version of WebKit is higher than 537 then those are almost certainly supported.

**Comment by NielsLeenheer** [comment]
Fixed
