### ISSUE TITLE
404 error on Video->video element link

### ISSUE THREAD

**Issue by sinzie** [WebPlatformTest/HTML5test#232]
Hi,

the link to the video element information for "Go to the specification at W3C.org" is:
http://www.w3.org/TR/html5/the-iframe-element.html#the-video-element

It should probably link to http://www.w3.org/TR/html-markup/video.html#video or http://www.w3.org/TR/html5/embedded-content-0.html#the-video-element .

This is a similar issue as #223 .

Best Regards,
sinzie

**Comment by sinzie** [comment]
Just saw that the same goes for Video->Poster image support, the current link is:
http://www.w3.org/TR/html5/the-iframe-element.html#dom-video-poster

It could be changed to: 
http://www.w3.org/TR/html-markup/video.html#video.attrs.poster
or
http://www.w3.org/TR/html5/embedded-content-0.html#attr-video-poster .

**Comment by NielsLeenheer** [comment]
Fixed
