### ISSUE TITLE
Irregular test results (page reload varies score!)

### ISSUE THREAD

**Issue by wolfbeast** [WebPlatformTest/HTML5test#235]
I noticed that in my browser (Pale Moon, which is Firefox-based), the HTML5 score varies when I hit reload (F5) on the page. The differences are always in the "Communication" category, and it seems to vary the results of:
XMLHttpRequest Level 2  Yes ✔
Upload files    Yes ✔
Text response type  Yes ✔
Document response type  Yes ✔
Array buffer response type  Yes ✔
Blob response type  Yes ✔

On occasion, it will drop "blob", or "array"+"blob", or the bottom 3 (document, array, blob). I've tried several different networking settings in the browser (pipelining on or off, varying numbers of allowed concurrent server connections) but none of it makes a difference. This problem has been verified by someone else with the same browser on a different system.
Since it should be a capability detection, which should be consistent, and the way the different tests fail, I think this may be a matter of "not waiting for results" long enough in the test? In any case, the result should be consistent but it's not.

**Comment by NielsLeenheer** [comment]
I think it may have something to do with caching. Could you try beta.html5test.com and see if the problem also is present there?

**Comment by wolfbeast** [comment]
I don't see the variance in results on my system at beta.html5test.com so that seems to solve the problem (whatever the difference is) - I'm asking the other folks reporting this behavior to verify and will relay that back to you.

**Comment by wolfbeast** [comment]
Hm, seems I was mistaken, just got a drop in score - it took longer but eventually I had the "document" response type fail.

**Comment by wolfbeast** [comment]
Confirmed by my fellows - the variance is at all times in the "communication" section, nowhere else, and specifically in the XMLHTTPRequest level 2 subtest:

Re: HTML5test score issues
Postby [removed] Sat Jan 26, 2013 12:05 pm
A quick test this morning, used the SDK7 build with a fresh profile, I am still getting a variable result of 347 or 349 whether I "F5" or reload the browser and test.
Tried the beta HTML5 test with a full profile 15.4.1 X64 and still getting the variable results - I will try it later with a fresh profile etc later today.

## 

OK. Clean profile, using SDK7 build, clearing History, Cookies and Cache after each test, reloading the browser (not the OS).
beta.html5test.com

3 results at 353
1 at 350 (Communications section - Text Response type X and Document Response type X)
1 at 352 (Communications section - Text Response type X)

## 

Re: HTML5test score issues

Postby [removed] Sat Jan 26, 2013 2:05 pm
I have with all versions (15.4.1 x64, 15.4.1 sdk7 + sdk8) the same score: 353 points.

Once i get a 346 score and once a 349 - forgot to make a screen or somethink at the 346 score, but i did it with 349 points: 
Communication
31/35
Cross-document messaging Yes ✔
Server-Sent Events Yes ✔
XMLHttpRequest Level 2 Partial ○
WebSocket Yes ✔

**Comment by wolfbeast** [comment]
A thought here: Maybe the test is thrown off by the fact that the social icons you have (G+/FB/etc.) cause a lot of processing and communication to different servers while the test is running? If there is a way to delay loading of that, that may possibly help.

**Comment by NielsLeenheer** [comment]
External scripts like Google+, Facebook and Twitter should not interfere. The scripts are inserted into the DOM after the test has finished and the results are known. I'm still suspecting that some of the XHR calls are cached in some instances.

**Comment by wolfbeast** [comment]
I assume you mean this would be cached server-side?

**Comment by NielsLeenheer** [comment]
It wasn't caching after all, but I think a bug in the code that waited for all background tasks to complete before the results are shown. 

Could you try again on beta.html5test.com. If I am right, the problem should now be solved.

**Comment by wolfbeast** [comment]
Looks good so far - I'm asking my fellows to have a check as well, will add a comment when I have their feedback.

**Comment by wolfbeast** [comment]
Problem seems to be solved on beta.html5test.com!

**Comment by NielsLeenheer** [comment]
Okay, great! I've updated html5test.com
