### ISSUE TITLE
Baidu Browser 2 scams its scores in the test.

### ISSUE THREAD

**Issue by LittleShadow** [WebPlatformTest/HTML5test#236]
Baidu Browser 2 which scores 467 recently did pretty bad things on the test.
It doesn't support geolocation actually, everytime you play with the geolocation demos, you can only get (0, 0) returned.

And for the Forms section in which part it got the full score, the UI is really ugly and the functionality is poor (sometimes does't work correctly).

Any good method to detect this kind of evil?

**Comment by NielsLeenheer** [comment]
I'll look into it. If they are scamming, I'll add them to the blacklist of the appropriate tests.

**Comment by NielsLeenheer** [comment]
Added to a whole bunch of blacklists

**Comment by superbunma** [comment]
his email: kotji@hotmail.com directly
------Original Message------
From: Niels Leenheer
To: NielsLeenheer/html5test
Cc: super bunman
ReplyTo: NielsLeenheer/html5test
Subject: Re: [html5test] Baidu Browser 2 scams its scores in the test. (#236)
Sent: Apr 4, 2013 02:36

Added to a whole bunch of blacklists 
—
Reply to this email directly or view it on GitHub. 
sent from your BlackBerry® smartphone

**Comment by jiazheng** [comment]
The geolocation service is only support in China right now because it uses its own geolocation service not the service provided by the system.

**Comment by superbunma** [comment]
NielsLeenheer/html5test/issues/236
