### ISSUE TITLE
Comparison Graph Error

### ISSUE THREAD

**Issue by paul-schwendenman** [WebPlatformTest/HTML5test#239]
The plotted graph of test scores under the timeline section has an error in the chrome plot. Chrome 24 should be later in the timeline, I think the issue is because the test is dated jan 2012 rather than jan 2013.
![Screenshot from 2013-01-28 13:49:06](https://f.cloud.github.com/assets/669804/104200/a61fec8e-697b-11e2-9c1b-a89bd66b2459.png)

**Comment by NielsLeenheer** [comment]
Fixed, thanks for reporting this issue.
