### ISSUE TITLE
Shouldn't assume that Attr inherits from Node

### ISSUE THREAD

**Issue by PavelCurtis** [WebPlatformTest/HTML5test#244]
As of DOM 4, Attr no longer inherits from Node.  That means that one should not use Node properties or methods on Attr objects.  The HTML5 tokenizer test uses the 'nodeName' property on an Attr object; it should be changed to use 'name' instead.

**Comment by NielsLeenheer** [comment]
A quick test shows that many browsers are not ready for this change and are going to lose points. This isn't a problem, they should update their implementations, but it's a big enough change that I am going to postpone this until the next major update of the site.

**Comment by NielsLeenheer** [comment]
Looked at it again and decided that I am going to change this, but allow both name and nodeName. The reason for this is that this is not a test about DOM4, but the HTML5 tokenizer. Using the DOM is just a method used to check the results. 

I do want to add additional tests for DOM4, but that is a separate issue.
