### ISSUE TITLE
Chrome Canary Version 24.0.1312.57 m returning false negatives

### ISSUE THREAD

**Issue by robertheadley** [WebPlatformTest/HTML5test#245]
HTML5 test is reporting that my build of Chrome Canary does not support features that it actually does. I tested them to see and the ones that the example supports that my build does not support are incorrect. Image attached. 

![html5testchromecanarywindows](https://f.cloud.github.com/assets/1780455/163240/577cc760-7811-11e2-882b-cf9e6759a0a8.png)

**Comment by NielsLeenheer** [comment]
The results listed for Chrome Canary are updated regularly, but given that Canary builds are updated constantly, it is quite possible the results listed on the site are 'outdated'. The reason you are seeing a better score is probably because you have a newer build than was used to record the score.

**Comment by robertheadley** [comment]
My results are lower than the build listed. The test is saying that my browser did not support elements that it actually does support. That is what I am reporting.  It is now reporting 463. So it seems to have improved somewhat.
