### ISSUE TITLE
BlackBerry Z10 Desktop Mode

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#246]
Just testing on my Z10, and normally it detects correctly.  It has the following user agent:

Mozilla/5.0 (BB10; Touch) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.0.9.2372 Mobile Safari/537.10+

However, it also has a desktop emulation mode which detects as Chrome 21 on Windows 7.  The user agent changes to:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.75 Safari/537.1

I'm not expecting anything to be done about this as it is cloning a desktop user agent to bypass mobile detection.  I just wanted you to be aware that this is happening so there is some way to explain all those awesome 485 (+11) scores on an old chrome version.

**Comment by NielsLeenheer** [comment]
Thanks for letting me know. I've informed BlackBerry about this issue and suggested including a way to detect BB10 even when using desktop mode. For now there is nothing more we can do about this.
