### ISSUE TITLE
Web SQL Database is not part of the HTML5 specification

### ISSUE THREAD

**Issue by beltzner** [WebPlatformTest/HTML5test#25]
The web SQL database specification has moved out from the main HTML5 specification and has according to its author "reached an impasse":

This specification has reached an impasse: all interested implementors have used the same SQL backend (Sqlite), but we need multiple independent implementations to proceed along a standardisation path. Until another implementor is interested in implementing this spec, the description of the SQL dialect has been left as simply a reference to Sqlite, which isn't acceptable for a standard.

Not sure it should be included as an HTML5 test, especially now that IndexedDB seems to have more motion behind it.

cite: http://dev.w3.org/html5/webdatabase/

**Comment by NielsLeenheer** [comment]
Web SQL Database will be part of the next version of html5test.com, but in a different way. Also IndexedDB is added to the test.

Web SQL Database only is 5 points, IndexedDB only will be 10 points.
IndexedDB and Web SQL Database both will also be 10 points.

So browsers will get 5 points for supporting the 'dead' spec, it has shipped in three different implementations and is actually used in real world web apps after all. But supporting the 'better' spec will get you full points, regardless of supporting the dead spec.
