### ISSUE TITLE
Notifications in Firefox nightly are not registered

### ISSUE THREAD

**Issue by Ygg01** [WebPlatformTest/HTML5test#252]
According to http://firefoxnightly.tumblr.com/ and this pastebin http://jsbin.com/notification/1/edit, which I verified that works on Mozilla Firefox, the Web notification test should pass. Is there a reason it's not passing? Is it Mozilla's fault or is the test faulty?

**Comment by iNoles** [comment]
See #211

**Comment by NielsLeenheer** [comment]
Has been fixed
