### ISSUE TITLE
Test results not readable on dark themes

### ISSUE THREAD

**Issue by falkTX** [WebPlatformTest/HTML5test#253]
I have a dark theme in my system (Ubuntu based), and the text in the results is not readable.

Please force-define text color as black in there.

![Uploading scr145.png . . .]()

**Comment by falkTX** [comment]
![scr145](https://f.cloud.github.com/assets/1334853/284273/581ff150-91da-11e2-835e-ff259e188cec.png)

uploaded screenshot, previous attempt blocked by noscript.

**Comment by NielsLeenheer** [comment]
Will be fixed in the next minor update
