### ISSUE TITLE
There is a test for a nonexistent 'command' element.

### ISSUE THREAD

**Issue by bzbarsky** [WebPlatformTest/HTML5test#257]
There is no 'command' element in either http://www.whatwg.org/specs/web-apps/current-work/multipage/ or http://www.w3.org/html/wg/drafts/html/master/

The current test seems to be based on an old draft or something.

**Comment by NielsLeenheer** [comment]
I am aware of this. This test will be removed during the next update.

**Comment by NielsLeenheer** [comment]
Fixed in the next update
