### ISSUE TITLE
the ps vitas browser has been updated now it scores 284 and two bonus points, please update your data

### ISSUE THREAD

**Issue by lalakar** [WebPlatformTest/HTML5test#258]

**Comment by danilaml** [comment]
I can confirm this. http://i70.servimg.com/u/f70/12/09/07/90/2013-012.jpg

**Comment by NielsLeenheer** [comment]
Could you run the test again and place the unique id in this bug report. The unique id can be found just below the test results.

**Comment by danilaml** [comment]
1371576561397_20ec

**Comment by NielsLeenheer** [comment]
Updated:
http://html5test.com/compare/browser/sonyvita21.html
