### ISSUE TITLE
Video and audio codecs are not part of the HTML5 specification

### ISSUE THREAD

**Issue by beltzner** [WebPlatformTest/HTML5test#26]
The HTML5 specification does not specify which codecs must be supported by browsers. Testing for support of h.264, AAC, and MP3 are not valid tests of HTML5 support.

**Comment by NielsLeenheer** [comment]
It is also mentioned that these tests go beyond the requirements of the spec.

I have changed the way codecs are tested in the next release, to prevent that browsers that support more codecs look like they are further along implementing HTML5. 

The next version will still award bonus points for codecs, but they will not be counted towards the total score. A separate tally for bonus points will be shown.

Try beta.html5test.com
