### ISSUE TITLE
Samsung Smart TV 2013 scores highest points in TV

### ISSUE THREAD

**Issue by jayne-mast** [WebPlatformTest/HTML5test#262]
The Samsung Smart TV 2013 scores 406 points with 12 bonus points
The browser is Chromium 24.0.1312.52

**Comment by NielsLeenheer** [comment]
Could you run the test again and place the unique id in this bug report. The unique id can be found just below the test results.

**Comment by jayne-mast** [comment]
The ID is 1371617803297_5337

**Comment by NielsLeenheer** [comment]
Scores on the current version of html5test.com will no longer be updated. A new version will be released in about a week with different scoring rules.
