### ISSUE TITLE
Detect WebCL support

### ISSUE THREAD

**Issue by kuckir** [WebPlatformTest/HTML5test#264]
I am a big fan of low-level ultra fast computations. It would be great to do them inside a browser. Currently there are two ways to do that: proprietary Google Native Client - https://developers.google.com/native-client/, where you distribute binaries, and open WebCL http://www.khronos.org/webcl/, where you distribute source code, which is compiled on client side. Second one can also run in parallel environments, e.g. on GPU.

I think it is a shame, that WebCL still is not implemented in modern browsers. What about adding WebCL detection to html5test, to encourage companies to implement it faster?

**Comment by paulirish** [comment]
IIRC, there is no interest amongst browser vendors in implementing WebCL.

**Comment by kuckir** [comment]
I am not sure if people realise, what would WebCL mean for web apps. I think that authors of "serious" apps (photo, video and audio editors, complex video games, scientific computations) still don't trust web platform too much. One of reasons is the speed of Javascript, which is still below native apps.

Google is working on Native Client, but I think that architecture-specific (compiled) code does not belong to the web. Google is also working on Dart, which can probably run faster than JS, if it is standardized. But WebCL allows us to distribute C code, which is easy to compile and would work much faster than Dart, especially on multicore GPUs.

Paul, can you ask Google to focus on WebCL instead of NaCl and Dart? :)

**Comment by NielsLeenheer** [comment]
Given that there does not seem to be much interested among browser vendors to support this, I am not going to add this feature at this time. Not much use to test for a feature that is not going to be supported anyway.
