### ISSUE TITLE
Opera, Firefox and other bete browsers

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#265]
I wonder, why are only the beta versions of Chrome and Safari showen, but does the test not show Opera 15 or Firefox 22+.

**Comment by coliff** [comment]
I'd love to see Internet Explorer 11 added too.

**Comment by NielsLeenheer** [comment]
I've added data about Opera 15 and IE 11. Firefox will be added soon.

**Comment by Christoph142** [comment]
Opera 16 is final now and they incorporated Chrome's splitting into Stable, Next and Developer stream. You might want to change this :+1:

**Comment by marsjaninzmarsa** [comment]
Firefox Aurora is still out of date.

**Comment by NielsLeenheer** [comment]
Scores on the current version of html5test.com will no longer be updated. A new version will be released in about a week with different scoring rules.
