### ISSUE TITLE
Include Firefox Nightly in the "Development or beta" section

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#267]
I noticed you've included Opera 15, Safari 7 and IE 11 in the Development or beta section, and I want to request you to include Firefox Nightly (currently in version 24) in the list. Is this possible?

**Comment by silasoverturf** [comment]
https://github.com/NielsLeenheer/html5test/issues/265#issuecomment-19621453

**Comment by NielsLeenheer** [comment]
Scores on the current version of html5test.com will no longer be updated. A new version will be released in about a week with different scoring rules.
