### ISSUE TITLE
detect.js: Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by quietmint** [WebPlatformTest/HTML5test#268]
I'm using Chrome with the custom user agent string `"Mozilla/5.0 (Windows NT 6.1) AppleWebKit (KHTML, like Gecko) Safari"` and can't access your site because of the following error. Please ensure detect.js fails gracefully.

```
Uncaught TypeError: Cannot read property '1' of null - detect.js:204
    Detected.detect - detect.js:204
    Detected.initialize - detect.js:118
    Detected - detect.js:102
    (anonymous function) - ie10.html:68
```

**Comment by NielsLeenheer** [comment]
If this is still an issue, could you reopen this bug here:
https://github.com/NielsLeenheer/WhichBrowser/issues
