### ISSUE TITLE
Penalize Vendor Prefixes

### ISSUE THREAD

**Issue by nmrugg** [WebPlatformTest/HTML5test#272]
I'm not sure if this has been discussed before, but I'd like to make a suggestion.

As a web developer, I find it very annoying to have to deal with the increasing amount of code duplication due to vendor prefixing. I believe that in order for a browser to be considered fully supporting the HTML5 spec, it must not use vendor prefixes. I propose that if a browser only supports a prefixed feature it should receive half credit.

**Comment by fbender** [comment]
I'd like to see that, too!

**Comment by NielsLeenheer** [comment]
At this time I do not think it would be a good idea to penalize vendor prefixes. I do plan on giving more information about which browser uses which prefix or which does not use a prefix at all.
