### ISSUE TITLE
Origami browser for Blackberry Playbook incorrectly detected

### ISSUE THREAD

**Issue by pierre5018** [WebPlatformTest/HTML5test#273]
Detects as "You are using Chrome Nightly 29.0.1547.2 on Windows 8",
Rather than Origami version 1.0.0 on Blackberry Playbook.

**Comment by NielsLeenheer** [comment]
I am afraid this is not something that can be fixed. Origami perfectly imitates Chrome and cannot be detected without the author adding 'hints' in UA string or other headers that it is not really Chrome and Origami instead.

**Comment by pierre5018** [comment]
perhaps you could rely on a follow on  question to the users  when they
reply no to the identification section?
