### ISSUE TITLE
contentEditable works on other browsers 

### ISSUE THREAD

**Issue by byeongeunlim** [WebPlatformTest/HTML5test#275]
I believe that HTML5Test score is closely relative to User-Agent. 

Below string is Chrome User-Agent.
"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36"
When Browsers.browser.name = "Chrome", Drag&drop API and HTML Editing score is 20/20. 

Other browser names listed in useragents.lib.php (except Chrome, Safari, Firefox browser) does not support. Drag&drop API and HTML Editing score is 2/20, even-though Drag&drop API and HTML Editing works fine. 

Please check and fix this. If I misunderstood calculation of score of HTML5Test, please explain. I would like to know. Thank you.

**Comment by NielsLeenheer** [comment]
Unfortunately there are too many browsers that report that Drag & Drop and ContentEditable are supported, but fail when you actually try if it works. So both these function are white-listed. Only if I can confirm for myself that the feature works as intended points are awarded.
