### ISSUE TITLE
Update scores

### ISSUE THREAD

**Issue by testman42** [WebPlatformTest/HTML5test#277]
Hello

I believe that site is a bit not updated.
All lastest Firefox (Release, Aurora, Nightly) are one version higher then those displayed on html5test.

And I wonder how is it possible that my Google Chrome dev (31.0.1612.0) gets lower score than Google Chrome 28.
Did they throw out some HTML5 stuff?

**Comment by silasoverturf** [comment]
Chrome 26 gets a lower score than Canary. Changes pertain to seamless iframe, support for which seems to have been removed.

http://html5test.com/compare/browser/chrome26/chromecanary.html

**Comment by NielsLeenheer** [comment]
Scores on the current version of html5test.com will no longer be updated. A new version will be released in about a week with different scoring rules.
