### ISSUE TITLE
Please add test for HTML5 <main> element

### ISSUE THREAD

**Issue by AdrianTP** [WebPlatformTest/HTML5test#278]
The WHATWG spec lists the &lt;main&gt; element:

http://www.whatwg.org/specs/web-apps/current-work/multipage/grouping-content.html#the-main-element

It would be great to be able to check for browser support for &lt;main&gt; by simply visiting html5test.com.

**Comment by NielsLeenheer** [comment]
The upcoming version will add a test for the <main> element
