### ISSUE TITLE
add test for registerContentHandler and registerProtocolHandler

### ISSUE THREAD

**Issue by dbaron** [WebPlatformTest/HTML5test#28]
http://www.w3.org/TR/html5/webappapis.html#dom-navigator-registerprotocolhandler describes two APIs:

window.navigator.registerContentHandler
window.navigator.registerProtocolHandler

that are really quite useful:  they allow Web applications that ought to be the user's handler for some type of Web content or protocol (e.g., gmail as a handler for mailto: links, google calendar as a handler for *.ics files) register to be such a handler.

I thought of this because I saw http://sachin.posterous.com/the-web-sucks this morning, which was complaining that this feature didn't exist.

I think these ought to be tested in html5test.  (I know they're implemented in Firefox, I think since Firefox 3, but I don't know whether other browsers implement them.)

**Comment by NielsLeenheer** [comment]
Added...
