### ISSUE TITLE
Canvas HD is dead

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#286]
The Canvas HD features as tested on current beta.html5test.com is going away and should not be tested for: http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2013-September/040735.html

**Comment by NielsLeenheer** [comment]
Thanks. This test was written before it that discussion.

**Comment by NielsLeenheer** [comment]
The final version of HTML5test will not include tests for Canvas HD. I'll close this bug once I remove the actual code.

**Comment by NielsLeenheer** [comment]
Removed
