### ISSUE TITLE
:read-write & :read-only selectors are tested twice

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#288]
On beta.html5test.com, :read-only and :read-write are tested for under Forms/Fields/CSS Selectors and User Interaction/HTML Editing/CSS Selectors. That's probably one too many.

**Comment by NielsLeenheer** [comment]
These are not duplicate tests. The same selector, but one test checks if it works on fields and the other checks if it works on regular elements that can be edited using designMode or contentEditable.

**Comment by fbender** [comment]
Alright.
