### ISSUE TITLE
CSP has no SecurityPolicy interface specification

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#289]
When you check for CSP support, you do `'SecurityPolicy' in document`. The CSP 1.0 spec (CR, so stable) does not specify such an interface, and is only added to the current draft CSP 1.1 spec and marked as experimental. 

Here's a website that tests for CSP and works for browser that do not implement `SecurityPolicy` (yet, so all of them): http://csptesting.herokuapp.com/
Testing for CSP can be as easy as CSP-blocking `eval` on the test page (or use one of the `*-src` directives) and `try`ing it in the test. 

If you're not willing to give up the convenience of the interface (which may or may not ever come), please follow the arguments in issue #287 and move this test to a non-counting part for the time being.

**Comment by NielsLeenheer** [comment]
Implemented a CSP 1.0 check.  Previously 1.1 was worth 5 points, now 1.0 is worth 3 points and 1.1 is worth 2 points.
