### ISSUE TITLE
Add links to w3schools on HTML properties you are testing

### ISSUE THREAD

**Issue by tekool** [WebPlatformTest/HTML5test#29]
It would be a great idea for HTML5 beginners to add a link on each property your are testing. I think to w3schools because I saw this made elsewhere. But as they don't include ID to create anchor links in their webpages it could be a link to the corresponding w3c HTML5 spec page of course.

**Comment by NielsLeenheer** [comment]
The upcoming version of html5test.com links to the relavant section of the w3 specs for each test.

**Comment by tekool** [comment]
Excellent, thank you. Keep up the good work!

**Comment by paulirish** [comment]
@tekool. let me recommend the Mozilla Development Center and the whatwg specs for reference. w3schools is unaffiliated with the w3c and has been known for providing really terrible information.
- https://developer.mozilla.org/  (or google: `mdc geolocation` for example)
- http://www.whatwg.org/specs/web-apps/current-work/

**Comment by fozzy** [comment]
Could you add further to this.  Could the codec tests (and any other applicable tests) link to information on plugins that would enable a browser to get a better score.  e.g. the WebM test links to where to get the WebM codec for the tested browser.
