### ISSUE TITLE
CSS 3

### ISSUE THREAD

**Issue by PatriceGILBERT** [WebPlatformTest/HTML5test#291]
I think it should be nice to have a test suite for all css functionnalities. I don't know how it can be done, but have html5 and css 3 together can be usefull.

**Comment by fbender** [comment]
This is the HTML5 test. Take a look at [css3test.com](http://css3test.com)!

**Comment by PatriceGILBERT** [comment]
oh ok thanks for the link :)

2013/10/17 Florian Bender notifications@github.com

> This is the HTML5 test. Take a look at css3test.com!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NielsLeenheer/html5test/issues/291#issuecomment-26484260
> .

## 

Patrice
