### ISSUE TITLE
Firefox Beta 25 Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [WebPlatformTest/HTML5test#293]
As you can see in the screenshot, the tests fail on http://beta.html5test.com/.

**Comment by fbender** [comment]
I see no screenshot.

**Comment by GrahamCampbell** [comment]
Ooops. I forgot to paste the link. I just went to screenshot it again, and the bug didn't occur this time.

**Comment by fbender** [comment]
I think I just saw the message. Something with accessing "encrypt" or so. But I only saw it once.

**Comment by NielsLeenheer** [comment]
I've had this report before. Are any of you perhaps running a 64 bit OS?

**Comment by fbender** [comment]
Yep, Mac OS X 10.8.5 on MBA 2012 (Sandy Bridge, I think). 

See also https://bugzilla.mozilla.org/show_bug.cgi?id=802882#c16

**Comment by GrahamCampbell** [comment]
Yes. I assumed it must have been due to one of my extensions. Also, my firefox updated yesterday. A fix by the Mozilla team may have fixed the issue.

**Comment by fbender** [comment]
Do you have NoScript installed? I do, but allow JS globally by default.

**Comment by mpopp75** [comment]
I saw this showing up on fresh profiles, with no addons installed. That rules out that any addons are involved. Happens with every version from 24 to 27, on Linux64.

**Comment by GrahamCampbell** [comment]
I don't have NoScript installed - I want javascript on my pages...

**Comment by mpopp75** [comment]
I just got this message on Firefox for Android too.

**Comment by pepejeria** [comment]
This issue is tracked by Mozilla here; https://bugzilla.mozilla.org/show_bug.cgi?id=927901

**Comment by mpopp75** [comment]
I guess this is now fixed in the 3rd candidate build for Firefox 25.0:

http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/25.0-candidates/build3/

And also in Aurora & Nightly channel. There is also a new candidate build for Firefox on Android 25.0 which I assume contains the fix as well.

**Comment by fbender** [comment]
Once someone has the 25 stable installed, can you test it there again? (esp. @mpopp75)

To reproduce, visit html5test.org, then click on the banner at the top to go to the beta page. No alert should appear.

**Comment by mpopp75** [comment]
I tried with Firefox 25 (Linux64 & Android) several times, and the alert never came up again. As far as I can tell I would say, this issue is fixed.

**Comment by GrahamCampbell** [comment]
Same here. I'll test with firefox 26 once it is released as a beta very shortly.

**Comment by mpopp75** [comment]
I did that too, using the candidate builds (which are usually the final bits) at http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/26.0b1-candidates/build1/ and no alerts there as well. Also tested Aurora & Nightly, also no alerts.

I noticed another thing though, namely that Objectstore Blob support and Objectstore ArrayBuffer support are sometimes recognized as supported and sometimes not on Firefox Nightly (not sure about Aurora & Beta, haven't seen it there yet). I should probably open a new bug report for that.

As for the alert thing, that's almost certainly fixed.

**Comment by fbender** [comment]
OK thanks. @NielsLeenheer can close this now, I think.

**Comment by GrahamCampbell** [comment]
I'll do it...

**Comment by NielsLeenheer** [comment]
Thanks everybody!
