### ISSUE TITLE
Maxithon browser not on comparason page

### ISSUE THREAD

**Issue by aspadistra** [WebPlatformTest/HTML5test#294]
The Maxithon browser is not shown in the desktop results

http://beta.html5test.com/results/desktop.html

It is the one of the most highly html5 compliant browsers, and it needs to be re-listed.

**Comment by cshaa** [comment]
I agree. And in this beta I was not even able to load it in the compare table.

**Comment by niutech** [comment]
Please bring back Maxthon browser to the list!

**Comment by NielsLeenheer** [comment]
Scores on the beta are just for testing the site, and are not complete and may not be up-to-date
