### ISSUE TITLE
Add Firefox OS

### ISSUE THREAD

**Issue by ferndot** [WebPlatformTest/HTML5test#295]
Firefox OS should be added to the mobile section of the browser comparison page.

**Comment by niutech** [comment]
Isn't the Firefox OS browser the same as Firefox Mobile?

**Comment by ferndot** [comment]
No, actually it isn't; Firefox Mobile is Firefox on Android.  Because of the nature of Firefox OS, it will naturally evolve at a different pace than Firefox Mobile, and may have different feature/api sets.

**Comment by NielsLeenheer** [comment]
Scores on the beta are just for testing the site, and are not complete and may not be up-to-date. I'll look into adding a separate entry for Firefox OS once the beta site is final.

**Comment by ferndot** [comment]
Want to re-look into this?
