### ISSUE TITLE
APNG test support

### ISSUE THREAD

**Issue by nt1m** [WebPlatformTest/HTML5test#296]
I think it's not fair that WebP is present when APNG detection is not.

**Comment by maxstepin** [comment]
I agree.

And WebP and AWebP use different headers, so level of support is not the same. 

They should be separated, just like PNG and APNG.

How about a special 2D-Animated category?

**Comment by NielsLeenheer** [comment]
Given that the test looks at which file formats canvas can export, animated formats are not applicable.

**Comment by clopez** [comment]
This JS code works for detecting APNG support .

https://gist.github.com/eligrey/175653
https://eligrey.com/blog/apng-feature-detection/

It looks fairly simple and reliable. I have tested it in chromium and epiphany (GNOME web browser) and it worked as expected

Can I suggest to reopen this issue and add back a test for APNG support? Thanks
