### ISSUE TITLE
`<menu>` test discrepancies with spec

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#297]
The current spec for [`menu`](http://www.whatwg.org/specs/web-apps/current-work/multipage/interactive-elements.html#menus) is different from the one you test for (esp. the `type`s). Also, `command` (which you removed in v. 5) has been replaced by [`menuitem`](http://www.whatwg.org/specs/web-apps/current-work/multipage/interactive-elements.html#the-menuitem-element) so you may want to add a test for it. [Context menus](http://www.whatwg.org/specs/web-apps/current-work/multipage/interactive-elements.html#context-menus) have been merged into `menu[type=popup]`.

You may also want to add further tests for functionality of `menuitem` and `menu` (e. g. where it can be invoked from, and invoking subtrees of a menu, see [1]). 

[1] http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2012-December/038472.html

**Comment by NielsLeenheer** [comment]
Redid the menu tests:
1. I check if HTMLMenuElement exists
2. If an element of type menu is an instance of HTMLMenuElement
3. The element has a type attribute
4. The default value of type (popup or toolbar)
5. If other values like 'foobar' are rejected

In case of popup menus I also check:
6. if HTMLMenuItemElement exists
7. If an element of type menuitem is an instance of HTMLMenuItemElement

**Comment by fbender** [comment]
Looks good, thanks. There's more you could cover, but I think that would be overkill.
