### ISSUE TITLE
compare should offer my browser 

### ISSUE THREAD

**Issue by DaleDe** [WebPlatformTest/HTML5test#298]
I would like to see "my browser" as a choice for compare. This is the most important option IMHO as it really helps to determine if a person wants to change or obtain an additional browser. This is particularly important for users that don't have one of the supported browser. I use Seamonkey by the way which does show all of the features on the home screen quite well but can't be chosen for comparison purposes.

**Comment by NielsLeenheer** [comment]
You can already do that:
![Screenshot](https://f.cloud.github.com/assets/233230/1444839/bafa994a-4212-11e3-8a8c-4feabf5d4cb0.png)
