### ISSUE TITLE
Firefox 26 Bug

### ISSUE THREAD

**Issue by GrahamCampbell** [WebPlatformTest/HTML5test#299]
When I go to http://beta.html5test.com/compare/browser/mybrowser/firefox-26.html using fierfox 26 beta, my fierfox 26 beta scores 440, but html5 test says firefox 26 scroes 438. I assume this old score of 438 is from an earlier build of firefox 26.

**Comment by NielsLeenheer** [comment]
The beta site is a work in progress and is not complete nor does it provide up-to-date results. Results will be updated before the new site goes live.
