### ISSUE TITLE
New Browser Request - Xbox One: scores 342/555 + 4 bonus points

### ISSUE THREAD

**Issue by steveworkman** [WebPlatformTest/HTML5test#301]
Tested during the xbox one tour event on October 30th 2013. Sadly, I didn't get a picture of the test itself, but I did get a picture of the supportdetails.com analysis of the console: http://t.co/VzURe9RhZn

**Comment by NielsLeenheer** [comment]
Thanks for the info. I'll keep a look out for test results of the Xbox One.

Generic answer: The beta site is a work in progress and is not complete nor does it provide up-to-date results. Results will be updated before the new site goes live.
