### ISSUE TITLE
input[type='range'] can never be :out-of-range

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#302]
The [test for `input[type=range]:out-of-range`](https://github.com/NielsLeenheer/html5test/blob/bc3430d8f7e45714d7b99da53c1b61ce97b5d5bf/scripts/engine.js#L2335) is _always_ `false`. Browsers seem to sanitize the `value` if it is `> max` or `< min` (at least Chrome and Firefox do that). So the test result can never be `true`. 

For this test, I recommend going back to `input[type=number]`. `:in-range` is not affected here, but if you want to change it, too (e.g. due to consistency), you're welcome to do that, even if that means that issue #283 is back again.

**Comment by NielsLeenheer** [comment]
Fixed. This was actually an unintentional change left over from testing #283.
