### ISSUE TITLE
Current browsers update

### ISSUE THREAD

**Issue by laukstein** [WebPlatformTest/HTML5test#303]
Update http://beta.html5test.com/results/desktop.html current browsers:
- Chrome 31
- Android 4.4
- Firefox 25
- Opera 17

**Comment by NielsLeenheer** [comment]
The beta site is a work in progress and is not complete nor does it provide up-to-date results. Results will be updated before the new site goes live.

**Comment by laukstein** [comment]
The same "current" browser outdated data you can see in:
- http://html5test.com/results/desktop.html
- http://html5test.com/results/tablet.html
- http://html5test.com/results/mobile.html

**Comment by laukstein** [comment]
@NielsLeenheer, you can reopen this issue since it is relevant.

**Comment by NielsLeenheer** [comment]
The new site will be launched this week. I am not going to update the old site anymore for just a day or two.
