### ISSUE TITLE
Point HTML5 spec links to the multi-page version of the spec

### ISSUE THREAD

**Issue by andreasbovens** [WebPlatformTest/HTML5test#304]
At present, "Go to the specification at W3C.org" points to references in the single-page HTML5 spec, which is very heavy to load. The multi-page spec is better suited here, IMHO.

**Comment by thomasfosterau** [comment]
This would be great for whatwg.org links as well. My laptop struggles to load the full page spec (and usually fails).

**Comment by NielsLeenheer** [comment]
The upcoming version only links to the multi-page spec.
