### ISSUE TITLE
new File System API spec

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#305]
There's a new spec in town, and it seems to have at least broader vendor support than the previous proposal: http://w3c.github.io/filesystem-api/Overview.html

Though I doubt this API is stable enough (you can check with the mailing list, though) to warrant allocating points for it just yet. However, because you are mentioning the legacy API, I'd say you should replace it with the new spec, or at least add it as well.

**Comment by NielsLeenheer** [comment]
Added a preliminary test for this spec. Is there still traction among implementors?

**Comment by fbender** [comment]
I don't have recent information (but I've been travelling), last I know is that Gecko is in progress and Blink in planning. I will file a new bug if anything changes that needs updating the test suite. Thanks! Will this be in 5.1?

**Comment by fbender** [comment]
Recent movement: https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0245.html & https://bugzilla.mozilla.org/show_bug.cgi?id=1164310

**Comment by fbender** [comment]
So Mozilla implemented the Directory Upload proposal from Microsoft, which uses a subset of the new File System API spec. There should probably be two tests to distinguish the features.

**Comment by NielsLeenheer** [comment]
I'll make sure to add a test for Directory Upload before the next release.

**Comment by NielsLeenheer** [comment]
Added a test for directory upload as a subtest for the input field. Marked experimental and award one point.
