### ISSUE TITLE
Web SQL Database should give away any points

### ISSUE THREAD

**Issue by nt1m** [WebPlatformTest/HTML5test#306]
Web SQL Database is deprecated so why would any future browser implement it. I mean it's silly to give away points for something deprecated. Or at least bring back the bonus points.

**Comment by NielsLeenheer** [comment]
If WebSQL is supported you get 5 points.
If IndexedDB is supported you get 20 points.
If both are supported you also get 20 points.

So browsers that support IndexedDB can get a full score without supporting WebSQL, but browsers that only support WebSQL will still get a slight improvement over a browsers that supports neither.
