### ISSUE TITLE
Prefixed features show as 'No' in features section

### ISSUE THREAD

**Issue by AshleyScirra** [WebPlatformTest/HTML5test#307]
It looks like in the 'Features' tab, anything that shows as 'Prefixed' with a tick elsewhere shows up as a 'No' with a cross.

Example with IE11 WebGL support:

http://html5test.com/compare/browser/ie-11.html - lists 'WebGL 3D graphics' as 'Prefixed'

http://html5test.com/compare/feature/webgl-context.html - lists 'IE11' support as 'No'

**Comment by NielsLeenheer** [comment]
Fixed
