### ISSUE TITLE
Canvas: Path is now Path2D

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#316]
… though [the spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#dfnReturnLink-9) has not been updated yet (and I'd wait for that to happen, I just wanted to file this bug to make sure it's tracked).

http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2013-December/041713.html

**Comment by NielsLeenheer** [comment]
Added this change to the upcoming version 5.1
