### ISSUE TITLE
Rethink forms score

### ISSUE THREAD

**Issue by diegobfernandez** [WebPlatformTest/HTML5test#317]
Some tests in Forms section has higher values than it should.

5 points: month, week, time, datetime-local.
4 points: range, number, color.

These input types should score 2 or 3 point as they can easily be achieved with javascript, and so has little impact in browser capability to do advanced tasks.

For example: Canvas and requestAnimationFrame is a game changer as we do not require 3th party plugins to perform vectorial and timelined tasks, but we have seen javascript widgets performing greatly (sometimes better than native) on inputs types even before standard specs.

**Comment by diegobfernandez** [comment]
Any comments?

**Comment by NielsLeenheer** [comment]
I do agree that the forms section weighs to heavy on the total score. I'm not sure yet how I want to fix this, but I expect to change this in the upcoming version of HTML5test.

**Comment by diegobfernandez** [comment]
Nice. Looking forward on next version!

**Comment by NielsLeenheer** [comment]
The upcoming version will have a maximum of 75 points for forms compared to 110 of the current version.
