### ISSUE TITLE
Konqueror and Epiphany

### ISSUE THREAD

**Issue by acerspyro** [WebPlatformTest/HTML5test#321]
Missing:
- KDE's Konqueror (At the time of writing, 4.11.2)
- GNOME's Epiphany browser

**Comment by NielsLeenheer** [comment]
I don't have the time to maintain Konqueror and Epiphany as a separate browsers on HTMLtest. But the browser itself and version updates will be accepted as a PR as long as it is frequently maintained. See https://github.com/WebPlatformTest/Data for more information.
