### ISSUE TITLE
IE 11 pointer events support

### ISSUE THREAD

**Issue by scheinercc** [WebPlatformTest/HTML5test#322]
I just saw that IE10 has support for pointer events and IE11 suddenly "losses" it again. After reading the following article I assume it's due to the test case!?
https://coderwall.com/p/mfreca

Should the test case be adjusted/updated?

**Comment by fbender** [comment]
The spec seems to have changed, the test uses `navigator.pointerEnabled` which is not in the spec. Use [`navigator.maxTouchPoints`](https://dvcs.w3.org/hg/pointerevents/raw-file/tip/pointerEvents.html#extensions-to-the-navigator-interface) instead.

Also, a (separate) test for the CSS `touch-action` property would be nice.

**Comment by NielsLeenheer** [comment]
Changed to match the latest revision of the spec.
