### ISSUE TITLE
Add Opus audio format

### ISSUE THREAD

**Issue by salarcode** [WebPlatformTest/HTML5test#323]
References:
http://tools.ietf.org/html/rfc6716
https://hacks.mozilla.org/2012/07/firefox-beta-15-supports-the-new-opus-audio-format/
http://opus-codec.org/

**Comment by fbender** [comment]
There should be both Ogg Opus and WebM Opus checks.

+1

**Comment by NielsLeenheer** [comment]
There is already a test of Ogg Opus, but I added one for WebM Opus too in the upcoming release
