### ISSUE TITLE
Test for (native) Promise support

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#326]
Promises are in the DOM (and coming to ECMAScript); currently developed Web APIs already depend on it. 

A test for a native Promise implementation would be great. There are several tests out there (e.g. Promise/A+ spec) though I don't know how compatible the DOM spec is (it should be close to full compliance though may not support all `Promise` methods).

**Comment by NielsLeenheer** [comment]
Promise support testing will be part of the next version of HTML5test

**Comment by fbender** [comment]
:+1:
