### ISSUE TITLE
MathML and SVG feature support test is not strict

### ISSUE THREAD

**Issue by AandK** [WebPlatformTest/HTML5test#330]
I am a webkit gtk developer, after I #define ENABLE_SVG 0 and #define ENABLE_MATHML 0, these two features have been disabled already, but html5test give the result shows these features still be supported.

html5test use following code snap to test browser whether support MathML and SVG feature,
var e = document.createElement('div');
e.innerHTML = '<math></math>';
var passedMath = e.firstChild && "namespaceURI" in e.firstChild && e.firstChild.namespaceURI == 'http://www.w3.org/1998/Math/MathML';

var e = document.createElement('div');
e.innerHTML = '<svg></svg>';
var passedSvg = e.firstChild && "namespaceURI" in e.firstChild && e.firstChild.namespaceURI == 'http://www.w3.org/2000/svg';

which is not strict to detect whether these two features are fully supported.

**Comment by fred-wang** [comment]
See discussions in #157  and #21

**Comment by NielsLeenheer** [comment]
As the other discussions mention. I only test for parsing of inline MathML and SVG according to the HTML5 parsing rules. And not if the renderer supports it.

I am thinking about combining these tests into a single one named "Parsing inline MathML and SVG". That should making it a bit more clear that it isn't a test for SVG support.

**Comment by NielsLeenheer** [comment]
Decided to keep the two separate tests, but made the wording on the results page clearer about that the test is about parsing support, not rendering.
