### ISSUE TITLE
"slice" method of ArrayBuffer

### ISSUE THREAD

**Issue by kuckir** [WebPlatformTest/HTML5test#331]
Hello,

my webapp is using ArrayBuffer - https://www.khronos.org/registry/typedarray/specs/latest/#5 . But it does not work in IE 11, since it does not have a "slice" method of ArrayBuffer implemented. But when I run html5test in IE11 and go to Performance -> Native binary data -> ArrayBuffer, it says "Yes".

Can you extend your test, so it also tests the presence of required methods of an object?

**Comment by kuckir** [comment]
In performance test, you should also add Uint8ClampedArray test - https://www.khronos.org/registry/typedarray/specs/latest/#7.1 , which is also not available in IE 11. It will help you to rate browsers more precisely.

**Comment by NielsLeenheer** [comment]
I believe both Uint8ClampedArray and the slice method for ArrayBuffer are relatively recent additions to the TypedArray spec. They are not part of version 1.0 of spec.

I do believe the new Canvas 2D Context spec redefined ImageData to use Uint8ClampedArray and I also think WebGL 1.0.1 has a dependancy on it, so it may be a good addition for the next update of HTML5test.

**Comment by NielsLeenheer** [comment]
Added Uint8ClampedArray for the next version of HTML5test

**Comment by NielsLeenheer** [comment]
I'm not going to add a test for ArrayBuffer slice, at this time. Closing this issue.

**Comment by kuckir** [comment]
To clear things up:
The latest "Khronos specification" (1.0 from February 2011) has no Uint8ClampedArray and no ArrayBuffer.slice(). IE 11 has implemented this specification.
The latest "Khronos working draft" (from July 2013) has Uint8ClampedArray and ArrayBuffer.slice(). Chrome, Firefox and other browsers have implemented this draft. 
So we don't need to test the presence ArrayBuffer.slice, Uint8ClampedArray is enough to distinguish between different versions of Typed Array standard.
