### ISSUE TITLE
Firefox OS

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#332]
firefox os is missing from the test

**Comment by ferndot** [comment]
Please add it!

**Comment by dstorey** [comment]
This is now dead, outside of TV (and IoT?)

**Comment by Kasijjuf** [comment]
@dstorey Just because Mozilla is abandoning it doesn't mean someone else won't come along and continue the project in some form.

**Comment by NielsLeenheer** [comment]
Panasonic televisions running Firefox OS are listed, but other than that... Please re-open this bug if Firefox OS on other platforms is brought back from the dead.
