### ISSUE TITLE
Different versions of Jolla Sailfish OS Browser 1.0

### ISSUE THREAD

**Issue by balta3** [WebPlatformTest/HTML5test#334]
Jolla's Sailfish OS is getting monthly updates at the moment, in every versions the browser is also updated. After the last update yesterday the browser is scoring 455 points now, Sadly they all are reporting version 1.0, but you could differentiate them on the gecko version in the user agent. Yesterdays update is using gecko 29.0

html5test.com is only showing a very old score at the moment as "Jolla Sailfish"

**Comment by NielsLeenheer** [comment]
Hmm, that is pretty unfortunate. Is there a browser version visible from the user interface (for example an about screen or something similar)?

**Comment by NielsLeenheer** [comment]
I've updated the score for Sailfish to use the latest release.
