### ISSUE TITLE
Wrong results for Chrome 13

### ISSUE THREAD

**Issue by phistuck** [WebPlatformTest/HTML5test#337]
When I tried comparing Internet Explorer 11 (which I happened to use in order to check its score, so it was "my browser" and not explicitly "Internet Explorer 11") and Chrome 13, I got some weird results. Unless my memory fails here, there are some mistakes.
http://html5test.com/compare/browser/ie-11/chrome-13.html

Chrome 13 did support Geolocation (4 or 5 and later), did not support getUserMedia ("Access the webcam". Either prefixed or not. ~23 and later, if I remember correctly), did support MP3, AAC and H.264 codecs (they were supported long before WebM).
I only noticed those, there might be more.

I think Geolocation and the codecs are not supported in the Chromium variant, so if you used Chromium instead of Chrome to test these, those mistakes make sense, but they do not apply to Google Chrome which is the browser I chose.

**Comment by NielsLeenheer** [comment]
Since filing this bug, the verified scores have been updated twice and I am in the process of redoing them again for the upcoming release. Closing this bug for now.
