### ISSUE TITLE
Maxthon 4.4

### ISSUE THREAD

**Issue by talregev** [WebPlatformTest/HTML5test#339]
Maxthon 4.4.
there already Maxthon 4.4,
and it point is 513.
better from Chrome. 
Why you hide this?
Why you don't place Maxthon at first place?
why you hide Maxthon at most used category. 
If you really want a competition, please show this results.

**Comment by DanAtkinson** [comment]
It's possible that Maxthon is not shown because it has a very low number of users compared to the other browsers that means it doesn't justify being included in the listing.

**Comment by R3gi** [comment]
Hello, I have to agree with @talregev . Maxthon is an international multi-platform browser, which supports more than 30 languages and which has huge user community all around the world. So it isn't definitely any tiny noname browser. Just please check http://forum.maxthon.com/ or find more info on http://maxthon.com/ :-)
Right now it really looks like you want to hide it, even if it has much better results than other famous superannuated browsers...
"Chrome isn't everything." ;-)

**Comment by talregev** [comment]
I agree with @R3gi. I am using chrome, but also like to see the true.
You also don't write correctly the number of the version of Maxthon.
Please fix the number of the version, and please stop hiding Maxthon!

**Comment by Azpidatziak** [comment]
Please, add Maxthon in Compare list options.
Maxthon is TOP5 Web Browsers in European Economic Area
https://web.archive.org/web/20140829080413/http://www.browserchoice.eu/BrowserChoice/browserchoice_en.htm

**Comment by DanAtkinson** [comment]
Maxthon uses the Trident and Webkit layout engines.

As such, and as per the [reporting section](http://html5test.com/about.html), Maxthon is not eligible for inclusion.

**Comment by R3gi** [comment]
"(…) And finally we only accept browsers which have a _unique score_. There are many browsers that are forks or modified versions of Chromium or Firefox. Similarly there are many browser that embed Internet Explorer or Webkit as provided by the operating system. These browser do not qualify. (…)"

You are right, even if it's modified version, but results are very _different_. May I ask, why these browsers do not qualify? For me it sounds like cheating… You are not comparing browsers, you're comparing their cores. And you're displaying only browsers from major contributos, from large companies. But normal user will interpret the Test as you are comparing directly browsers and the result is saying what browser is better, which can influences the browsers market position. At least you should add some visible notice on Your web :) That would be more fair.

**Comment by DanAtkinson** [comment]
I don't think that html5test.com really influences a browser's market position. And if market position is really what you care about (beyond the fact that it isn't well-adopted), rather than standards compliance, then you're quite welcome to set up a different website.

**Comment by Azpidatziak** [comment]
Hi Dan,

Maxthon use Webkit as default layout and have option to change to Trident, yes.
_Similarly there are many browser that embed Internet Explorer or Webkit as provided by the operating system. These browser do not qualify. For comparisons, simply choose the original browser on which the browser was based instead._
But default Maxthon webkit layout don't have a original browser that you can use for compare it's.

And Maxthon was a option in "Compare" tab for years, I think that you can make a exception.
_We retain the right to make exceptions to any of the rules above and to remove or refuse any browser we deem necessary._

What is about "microdata" feature score? It's give points in past but no longer.

Please make a exception and add Maxthon to compare tab.
Thanks!!

**Comment by R3gi** [comment]
@DanAtkinson It depends, I think you should know better than me, how known/used Html5Test website is :-) But that isn't what I'm talking about. I'm talking about impact to normal users. As you can see, many people are requesting browsers they like or which they are intersted in. Why? Well because they want to see the difference between them in order to find the "best" browser or find out, why their YT video doesn't work. I know that it isn't probably the main purpose, why was this service created, but you can not deny that this is so.
As I see it, it's a big opportunity for you to enhance the feautures and expand…But it's Your choice, I am only dumb user :)

**Comment by NielsLeenheer** [comment]
Right now Maxthon is a relatively minor browser marketshare wise. Perhaps Maxthon does belong here - because it does have a unique result - but right now there are already too many browsers to choose from on the results pages. I'm hoping to add some changes to the site that makes selecting browsers simpler. Once that is done, I'll gladly add more browsers.

**Comment by NielsLeenheer** [comment]
I don't have the time to maintain Maxthon as a separate browser on HTMLtest. But the browser itself and version updates will be accepted as a PR as long as it is frequently maintained. See https://github.com/WebPlatformTest/Data for more information.
