### ISSUE TITLE
Firefox 30 is not recognized

### ISSUE THREAD

**Issue by bastienJS** [WebPlatformTest/HTML5test#346]
I run Firefox 30 on my Windows 8.1 64Bit.

When I click the "other browsers" tab I see this:

![wrongfirefoxdetection](https://cloud.githubusercontent.com/assets/5945955/3262379/828f7244-f264-11e3-9f37-dff0959f4a11.png)

Although I run Firefox 30 (see about dialog) your site shows Firefox 29.

Thats seems a bug to me.

**Comment by NielsLeenheer** [comment]
"Current" does not refer to the browser that you are actually running, but a stored result of what the site thinks it the latest release of a particular browser. And sometimes it takes a couple of days before the site is updated after a new release.
