### ISSUE TITLE
Feature: Allow comparison of browsers based on saved results

### ISSUE THREAD

**Issue by DanAtkinson** [WebPlatformTest/HTML5test#348]
The website allows you to save your results, but I'd like to be able to compare this against another saved comparison.

One 'benefit' of this would be that I could compare a before and after browser update to see what has changed as, currently, I simply do a select all/copy of the page, paste it into Winmerge on the left, restart the browser and then select/copy/paste the page into Winmerge on the right to get a diff between the two.

It'd be awesome if the site could simply compare using two IDs instead.

Thanks!

**Comment by NielsLeenheer** [comment]
It is possible to compare to results, but you still have to look for changes yourself. They are not highlighted.

Go to "Compare" > "Browsers" and click on a + in the header of a column - while keeping the alt key pressed. A window pops up where you can enter the unique id of the test you want to compare. Do the same for the second id and you have the results of two tests side by side.

**Comment by DanAtkinson** [comment]
This behaves like an easter egg, rather than a documented feature!

Then I guess my feature request/s would be to change the alt+click functionality and make it visibly accessible and also to highlight any rows which have differences.

**Comment by NielsLeenheer** [comment]
It is an easter egg. I use it myself for comparing results, it's not documented anywhere. I'll probably add highlighting of changes in the next release.

**Comment by NielsLeenheer** [comment]
Coming soon!

<img width="587" alt="screen shot 2015-08-04 at 22 58 13" src="https://cloud.githubusercontent.com/assets/233230/9072587/626389b0-3afc-11e5-8a2d-0ae0dc254322.png">
