### ISSUE TITLE
firefox 30 does support h.264 if OS supports that

### ISSUE THREAD

**Issue by akostadinov** [WebPlatformTest/HTML5test#349]
Hello,

firefox 30 does support h.264 if OS supports that

It can be misleading for users that FF does not support that and they may give up and go for another browser. Maybe put somewhere a note that users should check with their linux distro or firefox binaries vendor for how to enable h.264

**Comment by Studio384** [comment]
This accounts for a lot of browsers. With the exact same browsers on different platforms, you'll still se different scores due to the platform it is being used on.

**Comment by NielsLeenheer** [comment]
I'm not planning on adding OS specific scores. I am considering looking at a way to collect multiple variations of the same browser and marking differing results for particular features as "os/device dependent". But in practice I think this would be very difficult to do without actually manually testing and confirming all of these differences. Closing this bug for now.
