### ISSUE TITLE
Microdata doesn't have a score

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#350]
On alpha.html5test.com the microdata is recognized correctly though always has a score of 0. Is that intended?

**Comment by blino** [comment]
That's probably intended, see commit c45be069f66bea6c51633ca277a3ffe10995d59b which drops points for the Microdata test.
The associated spec is also marked as rejected.

**Comment by NielsLeenheer** [comment]
This is indeed intended. The spec failed to gain traction and is basically dead in the water.
