### ISSUE TITLE
Speech Synthesis incorrectly marked as supported by Firefox

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#351]
Speech Synthesis is incorrectly marked as supported by Firefox since version 23. It will be implemented in [bug 1003439](https://bugzilla.mozilla.org/show_bug.cgi?id=1003439).
According to that issue Firefox OS **has** speech synthesis, though I don't have the possibility to verify that.

See also http://caniuse.com/web-speech.

**Comment by fbender** [comment]
This indeed seems to be implemented, but without "Speech Adapters": https://bugzilla.mozilla.org/show_bug.cgi?id=525444#c73 - whatever that means. Either way, caniuse is wrong.

**Comment by SebastianZ** [comment]
> but without "Speech Adapters": https://bugzilla.mozilla.org/show_bug.cgi?id=525444#c73 - whatever that means.

Currently no voices are implemented, which you can verify by executing `speechSynthesis.getVoices().length`. Also the `SpeechSynthesisUtterance` interface is currently still missing. Just execute the [example of the W3C spec](https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#examples-synthesis).
So I guess that's what is meant by that. And that is also the reason why caniuse says it's not implemented yet.
Obviously Firefox 31.0 (stable) accidentally exposes the `speechSynthesis` interface by default while in Nightly it's behind the pref `media.webspeech.synth.enabled`.

html5test [current just checks whether the `speechSynthesis` interface is implemented](https://github.com/NielsLeenheer/html5test/blob/8c56960826a6052948cbae01483f8fb82b9e0865/scripts/engine.js#L982), though it should also check whether the `SpeechSynthesisUtterance` interface is available.

Sebastian

**Comment by fbender** [comment]
> Obviously Firefox 31.0 (stable) accidentally exposes the speechSynthesis interface by default while in Nightly it's behind the pref media.webspeech.synth.enabled.

It seems to have been disabled in Fx 32. 

Either way, the functionality is implemented and can be enabled by any addon that brings its own Speech Adapter. I don't know why it was disabled by default, I assume an addon would have to flip this pref on install. 

Due to this circumstance, caniuse is incorrect. I'm not saying that it should show "supported" but rather "partial support" and a note that says it is limited to those installations having a speech adapter installed.

**Comment by fbender** [comment]
Maybe the test should also check for `speechSynthesis.getVoices().length > 0` and the description amended with `incl. installed voices` or similar.

**Comment by SebastianZ** [comment]
I created [pull request #392](https://github.com/NielsLeenheer/html5test/pull/392) for this. It adds two sub-items for the API and the voices under the _Speech Synthesis_.
![Split up *Speech Synthesis* item](https://cloud.githubusercontent.com/assets/958943/8032627/7cf7adda-0dd7-11e5-9a7d-1e095c94418a.png)

Sebastian

**Comment by NielsLeenheer** [comment]
@SebastianZ I'm not sure I want to go with this approach. Speech Synthesis is useless if there are no voices installed, so I think I want to change the test to include a check for voices. And simply say "No" if there are no voices installed.

**Comment by NielsLeenheer** [comment]
Speech Synthesis now says "Yes" when there are voices installed. Based on code by @SebastianZ. Committed to branch version-7.0

**Comment by SebastianZ** [comment]
> @SebastianZ I'm not sure I want to go with this approach. Speech Synthesis is useless if there are no voices installed, so I think I want to change the test to include a check for voices. And simply say "No" if there are no voices installed.

That's fine for me.

Sebastian
