### ISSUE TITLE
IE11 DOES support JPEG-XR

### ISSUE THREAD

**Issue by PaintNinja** [WebPlatformTest/HTML5test#353]
I can confirm that JPEG-XR files do fully work and display on Internet Explorer 11 and IE Mobile 11.

I am unsure but I believe it is the same with IE10.

**Comment by PaintNinja** [comment]
JPEG-XR files are fully supported in Internet Explorer 9, 10, 11 and higher. http://caniuse.com/#search=JPEG XR

In the HTML5Test.com results, it claims these browsers do not support the image file, when they clearly do!

**Comment by ericlaw1979** [comment]
This test is in the "Image export formats" section and thus the claim here is that IE's CANVAS object doesn't have the option to export its content as a JPEG-XR file using, for instance, the toDataUrl method. http://msdn.microsoft.com/en-us/library/ie/ff975241(v=vs.85).aspx

That seems like a believable claim; I'm not aware of a JPEGXR _encoder_ in IE, only a decoder.

**Comment by PaintNinja** [comment]
Ok I understand. I guess IE9+ has Partial support for JPEG-XR then, rather than no support at all?

**Comment by ericlaw1979** [comment]
IE9 has complete support for _rendering_ JPEG-XR. The point is that it doesn't have support for _generation_ of JPEG-XR.

**Comment by NielsLeenheer** [comment]
The test is indeed about exporting the canvas in various formats. And while IE does support reading JPEG-XR, it does not support exporting as JPEG-XR. So @ericlaw1979 is correct.
