### ISSUE TITLE
Windows Phone 8.1: input file incorrectly detected

### ISSUE THREAD

**Issue by Sebazzz** [WebPlatformTest/HTML5test#354]
I am running IE11 on Windows Phone 8.1 and the test incorrectly detects that the browser does not support file inputs. 

I have not checked, but I am pretty sure Windows Phone 8 also supports them.

**Comment by ghost** [comment]
Yes IE11 on 8.1 supports input=file. There are also some other false-positives.

Even on 8.1 Update preview (GDR1), it shows lesser score than 8.1's recorded score.

Did Microsoft eat their lunch or something?

**Comment by NielsLeenheer** [comment]
Fixed in the upcoming version of HTML5test.
