### ISSUE TITLE
Firefox supports :read-write and :read-only

### ISSUE THREAD

**Issue by mdibaiee** [WebPlatformTest/HTML5test#360]
http://css-tricks.com/almanac/selectors/r/read-write-read/

https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write
https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only

**Comment by NielsLeenheer** [comment]
:read-write and :read-only apply to both contentEditable elements and regular form fields. Firefox only supports the latter.
