### ISSUE TITLE
translation.js

### ISSUE THREAD

**Issue by pwayner** [WebPlatformTest/HTML5test#363]
When I tried to download some of the older versions (3.0) and (4.0), they didn't work because there was no copy of "/translation.js". 

I downloaded the current version of "http://www.html5test.com/translation.js" and it worked. It's just an empty JSON data structure but it seems to stop everything if it's missing.

**Comment by NielsLeenheer** [comment]
If you want you can file a pull request for these changes. I'm not actively working on updating these older versions.
