### ISSUE TITLE
Correct results are not produced in Windows Safari 5.1.7

### ISSUE THREAD

**Issue by skadimoolam** [WebPlatformTest/HTML5test#365]
![safaritest](https://cloud.githubusercontent.com/assets/6323063/4828757/6e07d894-5f82-11e4-8c65-dcd3142d60cd.png)

Is Safari 5.1.7 on windows this bad or did something go wrong in the test.
I ran the test a couple of time but this is the result.

**Comment by NielsLeenheer** [comment]
Safari for Windows has not been updated in a couple of years. So yeah, that is the score. Current versions of Safari for OS X score much better.
