### ISSUE TITLE
Distribute points more fairly

### ISSUE THREAD

**Issue by wolfbeast** [WebPlatformTest/HTML5test#366]
I've examined the test distribution of points and it seems they are distributed unfairly. You should reconsider the current points distribution.

A few examples:
- The audio element gets 20 points, but none of the audio file formats get any points. The audio tag and web audio API mean absolutely nothing if you don't support the formats. Same goes for the video element.
- Accessing the webcam is given a whopping 10 points (equal to canvas support and other major web features), while it's far from as useful in html5 as XHR file uploads or full screen API is (which get 5 points).
- Some stable features part of the current draft spec get no points at all, like 2D graphics -> Image export formats...

**Comment by NielsLeenheer** [comment]
Video, audio and image formats are optional and not required by the specs.

**Comment by wolfbeast** [comment]
Thank you for ignoring logic and ignoring my other points. :-1: down a notch for being a useful capacity comparison test then.

**Comment by NielsLeenheer** [comment]
Practically every browser that supports Audio, Video and Canvas support at least one and often more than one format. I know of only two which do not. And that is why I have a blacklist. Giving points for supporting formats is not useful. And given the controversy of between different formats it is even counter productive. 

Also I disagree with you assertions about the importance of Webcam support. Especially with WebRTC this is a big addition to the Web Platform.
