### ISSUE TITLE
website error

### ISSUE THREAD

**Issue by alx5962** [WebPlatformTest/HTML5test#369]
If you go there: http://beta.html5test.com/compare/browser/mybrowser.html

there's an error: "Access denied for user 'www-data'@'localhost' (using password: NO)Access denied for user 'www-data'@'localhost' (using password: NO)Access denied for user 'www-data'@'localhost' (using password: NO)Access denied for user 'www-data'@'localhost' (using password: NO)Access denied for user 'www-data'@'localhost' (using password: NO) "

**Comment by SebastianZ** [comment]
I don't see that. Is that still an error for you?

Sebastian

**Comment by alx5962** [comment]
No, it seems to be fixed now!
