### ISSUE TITLE
Broken on iOS 8 Safari in private mode (deleteDatabase error)

### ISSUE THREAD

**Issue by fregante** [WebPlatformTest/HTML5test#370]
html5test.com works fine in iOS8 unless you open it in private mode. If you do, you'll see this alert message and no tests will appear above the About section.

![iOS iPad Safari private mode](https://cloud.githubusercontent.com/assets/1402241/5057992/323aca58-6c91-11e4-9e0f-6839f2b32175.PNG)

**Comment by NielsLeenheer** [comment]
Will be fixed in the upcoming release
