### ISSUE TITLE
The website isn't accessible via HTTPS

### ISSUE THREAD

**Issue by alive4ever** [WebPlatformTest/HTML5test#371]
It would be better for the html5test.com website to enforce HTTPS for browser connections.

If it isn't possible to enforce HTTPS, at least make the site accessible via HTTPS, so that the integrity of the test results are protected against man in the middle attacks.

**Comment by NielsLeenheer** [comment]
I'd love to switch to HTTPS and the site is in fact already working on a secure connection: https://html5test.com. But until very recently our advertising partner was not ready yet and would still serve ads using a plain HTTP connection leading to mixed mode warnings in some browsers, so I had to hold of with switching.

Not that our ads are working with HTTPS I'm planning on moving to HTTPS soon.

**Comment by alive4ever** [comment]
The site is accessible via https, but currently the certificate chain sent by server is incompete. Android browser and Chrome for Android refuses to connect on https.

There are also more problems you can verify on [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=html5test.com).

I am looking forward for this issue to be fixed.

**Comment by NielsLeenheer** [comment]
Didn't know about the incomplete certificate chain. 

But other problems were a known issue. The only way to fix them was to set up a completely new server and get new certificates. Which I did. You should now see an A+ score.

**Comment by NielsLeenheer** [comment]
The new site with SSL support is now online.
