### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by borovinskiy** [WebPlatformTest/HTML5test#372]
I want packaging html5test in EPUB book for testing EPUB Book Reading Systems.

Can you add file with licensing?

**Comment by beatgammit** [comment]
According to #57 this should be BSD, but I don't find that documented in the source.

**Comment by borovinskiy** [comment]
Thank you.
I'll wait for the adding license file.

**Comment by NielsLeenheer** [comment]
https://github.com/NielsLeenheer/html5test/blob/version-5.1/index.html#L61-L80

**Comment by NielsLeenheer** [comment]
I'll add a separate LICENSE file with the next release
