### ISSUE TITLE
feature: option to only show differences in support

### ISSUE THREAD

**Issue by beatgammit** [WebPlatformTest/HTML5test#374]
It would be nice to hide redundant information, such as features that all selected browsers support. This is partially done today with collapsing lists of sub-components of a feature, but often many (if not all) of the features in a category are supported by the selected browsers.

**Comment by NielsLeenheer** [comment]
Coming soon!

<img width="895" alt="screen shot 2015-08-05 at 00 43 16" src="https://cloud.githubusercontent.com/assets/233230/9074561/1d973066-3b0b-11e5-87e9-a004f0f89c80.png">
