### ISSUE TITLE
Allow to see feature info within browser comparison page

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#376]
The page for comparing the results (http://html5test.com/compare/browser/index.html) should have an option to display the feature description like within the test page.

To clarify what I'm talking about, here a screenshot:

![Feature info](https://cloud.githubusercontent.com/assets/958943/5503259/4e02ba9e-8775-11e4-8970-a7999383e8f3.png)

Sebastian

**Comment by NielsLeenheer** [comment]
Coming soon!

<img width="502" alt="screen shot 2015-08-04 at 22 54 24" src="https://cloud.githubusercontent.com/assets/233230/9072511/ebc15684-3afb-11e5-967b-e31889d9add2.png">

**Comment by SebastianZ** [comment]
Great! Thank you for the info!

Sebastian

**Comment by SebastianZ** [comment]
Works fine on beta.html5test.com. Thanks Niels!

Sebastian
