### ISSUE TITLE
Add background color to comparison results to improve visibility

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#377]
To improve the visual indentification of the support of a specific feature within the comparison page the background of the fields should be colored.

![Comparison results with background color](https://cloud.githubusercontent.com/assets/958943/5503474/882aa518-8777-11e4-84f2-ae52b6d0f30e.png)

Sebastian

**Comment by dstorey** [comment]
The colour contrast probably isn't high enough in the example above to be accessible.

**Comment by SebastianZ** [comment]
I agree if you are referring to the _Partial_ status. The text color should be make black for them like for the other statuses.

Sebastian

**Comment by dstorey** [comment]
Even for the non-partial, e.g.
![screen shot 2016-02-29 at 5 38 23 pm](https://cloud.githubusercontent.com/assets/465069/13414907/1535642a-df0b-11e5-8d94-581e20d8711d.png)

**Comment by SebastianZ** [comment]
The colors you chose are different from the ones in my mockup. In the mockup they are black (`rgb(0, 0, 0)`) for the text color and some lighter green (`rgb(179, 239, 179)`) than in your screenshot for the background color of passing tests, resulting in a contrast ratio of 15.91:1 according to the [Color Contrast Checker](http://webaim.org/resources/contrastchecker/).

Sebastian

**Comment by dstorey** [comment]
The colours were with a colour picker but the green text is for the green arrow colour.

**Comment by SebastianZ** [comment]
You mean the check icon? That's `rgb(28, 140, 29)` (unchanged from the current color used on the page). Its contrast may be increased, though even when people can't distinguish it from the background, it doesn't matter much, as we then have the text and the colored background indicating the status.

Sebastian
