### ISSUE TITLE
Limited <menu> types tested

### ISSUE THREAD

**Issue by shgysk8zer0** [WebPlatformTest/HTML5test#381]
If you allow for prefixed versions then, in a sense, you are testing for functionality rather than names. Something to consider then is that Firefox does support alternative types, which are the same things by different names.

I cannot think of any examples for HTML, but if this were a CSS test, would you consider older versions of Chrome using `display: -webkit-box` instead of `display: flex` as supporting flexbox?

<blockquote>
<i>
<strong>Note:</strong> This documentation describes current Firefox implementation. Type 'list' is likely to change to 'toolbar' and 'context' to 'popup' according to HTML5.1 working draft.</i><br />
…<hr />
<strong>type</strong><br />
This attribute indicates the kind of menu being declared, and can be one of two values.
<ul>
<li> context: The context menu state, which represents a group of commands activated through another element. This might be through the menu attribute of a <code>&lt;button&gt;</code>, or an element with a contextmenu attribute. When nesting <code>&lt;menu&gt;</code> elements directly within one another, this is the missing value default if the parent is already in this state.</li>
<li> list: The list menu state, which represents a series of commands for user interaction. This is the missing value default, except where the parent element is a <menu> in the context menu state.</li>
</ul>
&mdash;<cite><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu">&lt;menu&gt;- HTML (HyperText Markup Language) | MDN</a></cite>
</blockquote>

**Comment by fbender** [comment]
Also see #297

**Comment by NielsLeenheer** [comment]
In the upcoming release I'm making a distinction between old legacy non-standard implementation that got standardised in a different way and early implementations of the standard and the standard got changed.

Old legacy non-standard implementations trigger a "No".
If you have an early implementation of the standard it triggers a "Incomplete".

The menu feature in Firefox would be the latter.
