### ISSUE TITLE
Add the vivaldi browser

### ISSUE THREAD

**Issue by PlanetVaster** [WebPlatformTest/HTML5test#383]
The Vivaldi browser is currently in the tech preview stage but is made by the same people who made opera and will soon be a major browser: https://vivaldi.com

**Comment by DanAtkinson** [comment]
:-1:

Vivaldi is based on the Blink layout engine, so I'm not sure whether there would be any point in adding this, since its use is already covered by Chrome.

Also, the actual usage of Vivaldi is so insignificant right now. that I don't believe it's worth handling it.

**Comment by nathanh752** [comment]
Opera 18-26 are also based on blink, so why is that browser still in there?  No point in having it in the list as it's already covered by chrome... Not to mention their (almost) non-existing market share...

**Comment by NielsLeenheer** [comment]
I'm hesitant to add Vivaldi at this time. And probably never as a primary browser due to market share. But I am planning on adding a way to better handle a larger number of secondary browsers.
