### ISSUE TITLE
Chrome doesn’t support Pointer Events (yet) says it does

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#385]
The test for Pointer Events is faulty. It shows Chrome as supporting Pointer Events. I‘ve seen it reported that IE doesn't support pointer events on non-touch hardware (don't have to verify right now)

I believe this is because you test for `maxTouchPoints` which they do support. It should instead check for the PointerEvent interface http://www.w3.org/TR/pointerevents/#pointerevent-interface

**Comment by NielsLeenheer** [comment]
Will change this in the next update.

**Comment by NielsLeenheer** [comment]
Fixed. Committed to version-7.0
