### ISSUE TITLE
Is it still active?

### ISSUE THREAD

**Issue by felipepessoto** [WebPlatformTest/HTML5test#386]

**Comment by felipepessoto** [comment]
I don't think so...

**Comment by paulirish** [comment]
It is, but its just one guy, so it comes in bursts.
https://github.com/NielsLeenheer/html5test/graphs/contributors

**Comment by NielsLeenheer** [comment]
Yes, the project is still active. The last few months I unfortunately didn't have the time to work on it extensively due to some family health issues. Updates will resume shortly.
