### ISSUE TITLE
Check for script execution events requires data: URLs to be allowed in the CSP

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#387]
The CSP 2 spec [states](http://www.w3.org/TR/CSP11/#match-source-expression) that `*` as CSP does not include the `data:` scheme.

Though this scheme is used for testing the script execution events, which now incorrectly [fails](https://bugzilla.mozilla.org/show_bug.cgi?id=1157724) on Firefox due to [bug 1086999](https://bugzilla.mozilla.org/show_bug.cgi?id=1086999).

To fix this either the [CSP](https://github.com/NielsLeenheer/html5test/blob/78b55a47f9792d7e3a7df888f65871b4608351b2/backend/controllers/browser.php#L10-L12) needs to be changed to include `data:` or the script source needs to be added via `s.textContent="window";` instead of [`s.src="data:text/javascript;charset=utf-8,window"`](https://github.com/NielsLeenheer/html5test/blob/332cc82e529c676a8b9c761f30de4a1ffe859c33/scripts/6/engine.js#L3592).

Sebastian

**Comment by DanAtkinson** [comment]
Is this something that you could commit as a pull request?

**Comment by SebastianZ** [comment]
Added `data:` to the CSP and created the PR.

Sebastian

**Comment by NielsLeenheer** [comment]
Will be fixed for the upcoming release

**Comment by NielsLeenheer** [comment]
Fixed, committed to the release-7.0 branch
