### ISSUE TITLE
iframe sandbox support

### ISSUE THREAD

**Issue by KieranP** [WebPlatformTest/HTML5test#39]
http://www.whatwg.org/specs/web-apps/current-work/#attr-iframe-sandbox

http://blog.chromium.org/2010/05/security-in-depth-html5s-sandbox.html

The Chromium blog post shows how to detect it:

```
if (”sandbox” in document.createElement(”iframe”)) {
    // This browser supports @sandbox.  We can sandbox untrusted content with confidence.
}
```

**Comment by NielsLeenheer** [comment]
Added to beta.html5test.com
