### ISSUE TITLE
Link to FileSystem API spec is broken

### ISSUE THREAD

**Issue by fbender** [WebPlatformTest/HTML5test#391]
Should be http://w3c.github.io/filesystem-api/ (instead of http://w3c.github.io/filesystem-api/Overview.html).

**Comment by DanAtkinson** [comment]
To be fair, W3C's own links appear to be broken, such as their 'Latest published version' link.

**Comment by NielsLeenheer** [comment]
Fixed, committed to the release-7.0 branch
