### ISSUE TITLE
Wii U Score is outdated

### ISSUE THREAD

**Issue by aroskuski** [WebPlatformTest/HTML5test#395]
The 5.4.0 update for Wii U updated the Internet Browser.  The latest version of the browser now scores 311 points.

**Comment by aroskuski** [comment]
Here is an example test result I collected with my Wii U:
http://html5test.com/s/2c8cd028abe1a73c.html

**Comment by aroskuski** [comment]
Here is an example test result I collected with my Wii U:
http://html5test.com/s/2c8cd028abe1a73c.html

**Comment by NielsLeenheer** [comment]
Updated!
