### ISSUE TITLE
Lots of links to MDN is broken

### ISSUE THREAD

**Issue by yume-chan** [WebPlatformTest/HTML5test#396]
At [/scripts/base.js#L823](https://github.com/NielsLeenheer/html5test/blob/version-7.0/scripts/base.js#L823)

``` JavaScript
/* ... */ content += "<a href='https://developer.mozilla.org/en-US/docs" + data.urls[i][1] +"' class='mdn'>" /* ... */
```

But according to search (https://github.com/NielsLeenheer/html5test/search?q=mdn+docs&type=Code), lots of link contains a extra `/docs` part leads to 404 pages.
(And as a note that GitHub search doesn't list all occurrences)

**Comment by NielsLeenheer** [comment]
All MDN links will be updated with the upcoming release.
