### ISSUE TITLE
Edge is listed as an IE version

### ISSUE THREAD

**Issue by mgol** [WebPlatformTest/HTML5test#398]
Currently the site lists Edge not as a separate browser but as "IE Edge" as if "Edge" was a version instead of a name. Perhaps it would be better to get it have a separate column? Or if you want to save space, at least changing the header from "Internet Explorer" to "Internet Explorer / Edge" or "IE / Edge" would be more to the point.

Refs #384

**Comment by mgol** [comment]
BTW, for comparison Can I Use currently uses ["IE / Edge" on the site](http://caniuse.com/#feat=css-supports-api) and tracks them both [separately in data](https://github.com/Fyrd/caniuse/blob/master/features-json/css-supports-api.json).

**Comment by NielsLeenheer** [comment]
The current situation is temporary. With the upcoming release later this month I'll have a proper solution in place.
