### ISSUE TITLE
Mediasource Extensions IE 11

### ISSUE THREAD

**Issue by lekoaf** [WebPlatformTest/HTML5test#399]
The Mediasource Extension support on IE 11 has diverged between Windows 7 and Windows 10.

IE 11 on Windows 10 supports Mediasource Extensions.
IE 11 on Windows 7 does not support Mediasource Extensions.

http://html5test.com/compare/feature/video-mediasource.html
https://msdn.microsoft.com/en-us/library/dn594470(v=vs.85).aspx

**Comment by NielsLeenheer** [comment]
I think the diversion started on Windows 8. But I'm probably won't make this distinction on the result pages. There are many more features dependant on platform or hardware. Including all those differences would make the result pages far too complicated.

**Comment by lekoaf** [comment]
Well it's not my problem really, but you would rather have an erroneous website than deal with bit of complication?

Yes, the diversion started in Win 8. My bad.
