### ISSUE TITLE
add Edge preview to upcoming

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#400]
A Windows 10 Insider Preview went out today. http://blogs.windows.com/bloggingwindows/2015/08/18/announcing-windows-10-insider-preview-build-10525/

Would be great to include Edge preview in the Upcoming row of the Edge column.

**Comment by Studio384** [comment]
Another issue, in the html5test.com-version, Edge 20.10525 has 412 points and "Pointer events" is noted as not supported, but it is. The beta.html5test.com version does identify this feature correctly for Edge.

**Comment by dstorey** [comment]
The pointer event test is faulty in V6 (gives points to Chrome when they don't support it, doesn't give points to Edge when it does). This was fixed in V7 but not back ported.

**Comment by dstorey** [comment]
A preview is out now (440 points currently).

**Comment by Studio384** [comment]
Edge will now identify itself as Edge 13 (up from 12 in Windows 10) for the next Insider Preview build.

**Comment by dstorey** [comment]
Our version number is now documented at https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/

**Comment by NielsLeenheer** [comment]
I've added Edge 13 to the current version of HTML5test. It's a bit of a kludge, but once the new version is out tracking Edge will become a lot easier.

**Comment by mgol** [comment]
Why are Pointer Events marked as unsupported in the Edge 13 preview? Same for IE 11? They're marked as supported in Edge 12.

**Comment by NielsLeenheer** [comment]
It's a bug in the test. It will be fixed with the next update which will be released Real-Soon-Now™

**Comment by dstorey** [comment]
@NielsLeenheer although there is a bug in the test, it is detected on touch hardware correctly, so should probably be listed s 458 instead of 453.

**Comment by Studio384** [comment]
It maybe would be useful to report "Edge" as "Edge 12", would be better in the logical sense.
