### ISSUE TITLE
Duplicate Scores

### ISSUE THREAD

**Issue by Yavanius** [WebPlatformTest/HTML5test#401]
I am seeing that duplicate but not identical scores are being generated. If you go to Other Browsers and Latest, you can see this.

The interesting thing is there appears to be a high score and a lower score, the later of which is the one that shows at the end of the test.

Also, on Palemoon, a repeat test resulted in a higher score. While I get duplicates also on Firefox and Edge, they did not have this specific issue.

410 Pale Moon 25.6.0 on Windows 10  8 minutes ago
412 Pale Moon 25.6.0 on Windows 10  8 minutes ago
405 Pale Moon 25.6.0 on Windows 10  11 minutes ago
407 Pale Moon 25.6.0 on Windows 10  11 minutes ago

**Comment by Yavanius** [comment]
UPDATE: After updating Firefox to 40, I had a thought and 'Forgot' the HTML5Test. I was able to reproduce the same bug I saw in Pale Moon in Firefox. I suspect this is true for all browsers.

To reproduce:
1. 'Forget' HTML5Test
2. Reload http://html5test.com
3. After results appear, goto other browsers, then latest
4. Go back to Your Browser

**Comment by NielsLeenheer** [comment]
That duplicate scores are generated is correct. But they should not be visible. Right now every visitor of the main site also submits a result for the next version of the test. This is in preparation for the launch of the new version next week, so that I have enough results to generate the other browsers and compare pages.

**Comment by Yavanius** [comment]
Okay, but why are we generating 4 different scores? It's not just duplicates, it's two different sets of duplicates.
