### ISSUE TITLE
Pale Moon (an Open Source web browser forked off from the Firefox/Mozilla code)

### ISSUE THREAD

**Issue by LimboSlam** [WebPlatformTest/HTML5test#404]
Hi there! I just love your HTML5 test website, it's a real tool for geeks/devs like us!! But sadly it doesn't list Pale Moon (an open source web browser forked off from the Firefox/Mozilla code) as an option to compare with other browsers or as an official browser it's self, not even under Firefox. Pale Moon has been out for 6 years and is a known alternative to Firefox that it's now the 2nd or 3rd most popular browser to go with, at least over here in the Mozilla/Gecko family. Too add, "Pale Moon has it's own GUID (a dual-GUID system to support both FF and PM add-ons) to reflect a divergence from Firefox starting from v25.0.0 onward (current stable release is v25.7.0 of Pale Moon), and with our very own add-on platform that has been increasingly growing. We have also just released v26.0.0pb2 that comes with a new layout and rendering engine called Goanna (a modified rendering engine forked off Gecko to fit our specific needs as an independent browser) starting from the version scheme 1.0 that is independent of Pale Moon, Firefox or Gecko versions. This version will increase as it's being worked on by our development team." Furthermore, Pale Moon is whole different beast now and should be added as an available browser/option on your website (in my opinion). 

-Our GUID is: {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}
-Pale Moon stable UA: Mozilla/5.0 (Windows NT 6.1; rv:25.7) Gecko/20150824 PaleMoon/25.7.0
-Firefox compatible UA: Mozilla/5.0 (Windows NT 6.1; rv:25.7) Gecko/20150824 Firefox/31.9 PaleMoon/25.7.0
-AMO specific UA: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.9) Gecko/20100101 Firefox/24.9 (Pale Moon)

-Pale Moon v26.0.0pb2 UA: Mozilla/5.0 (Windows NT 6.1; rv:1.0) Goanna/20150828 Gecko/20100101 PaleMoon/26.0.0b2
-Firefox compatibility UA: Mozilla/5.0 (Windows NT 6.1; rv:1.0) Goanna/20150828 Gecko/20100101 Firefox/31.9 PaleMoon/26.0.0b2 

If you want to know more about this change, please feel free to contact one us by private message or a public notice (register first) on our forums here: https://forum.palemoon.org/index.php. You can also read this current info on "how to account and recognize Pale Moon 26.0.0/Goanna-based applications" for your website: https://forum.palemoon.org/viewtopic.php?f=1&t=9361. More about the Goanna engine can be found here: http://moonchildproductions.info/goanna.shtml or here: https://forum.palemoon.org/viewtopic.php?f=1&t=8607. Now to test out Pale Moon v26.0.0pb2, please get it here: https://www.palemoon.org/WIP/. 

Best regards,
LimboSlam

**Comment by LimboSlam** [comment]
@NielsLeenheer : Why haven't I you responded? I see you have with others post quickly, but not mine? Why is that??

**Comment by VeronicaGarcia** [comment]
Yes will this be address anytime soon, @LimboSlam and @NielsLeenheer. How about @wolfbeast, any clarifications on this? Anything you can do about this? 

Oh, will the tag "New browser request" be added?

**Comment by dstorey** [comment]
HTML5Test is a personal project done in Niels’ spare time, so you can expect him to turnoff a dime and answer right away. 

Most browsers on HTML5Test have unique engines that make their differences enough to be worth tracking (e.g. not much point tracking both Firefox and Camino back in the day, or all the various Chromium based browsers, or MSIE/Trident browsers). How different is the forked Gecko in Palemoon to Firefox? Are you a fork that is going its own way from Gecko that will make it distinctly different, like Blink now is from WebKit? Will the HTML5 score always be similar to Firefox (inc. nightly) or will it diverge widely?

**Comment by wolfbeast** [comment]
> How different is the forked Gecko in Palemoon to Firefox?

Different enough to rebrand it (which will officially happen with the next milestone release)

> Are you a fork that is going its own way from Gecko that will make it distinctly different, like Blink now is from WebKit?

Yes, which anyone who has paid more than a few minutes reading up on Pale Moon would have seen.

> Will the HTML5 score always be similar to Firefox (inc. nightly) or will it diverge widely?

It will diverge (and has diverged) from the Firefox score, and will likely continue to do so, or converge again in some respects since you're just looking at the end result. Of course all browsers should strive to be more spec compliant so looking at "how much the score differs" as an indicator of "how different the browsers are under the hood" is a fallacy.

**Comment by dstorey** [comment]
It is not a fallacy for sites like this that track a score; as if the score is the same as Firefox then it can be tracked by tracking Firefox, just as Yandex can be tracked by tracking Chrome.

**Comment by wolfbeast** [comment]
No, you're incorrect. It is very much a fallacy for these scoring sites when you are dealing with independent development of engines.

Just because e.g. Chrome supports the same html5 element as Firefox, doesn't automagically mean that Chrome implements it the same way as Firefox and therefore should be considered 'the same" for that feature.

You can only group browsers together that are, in fact, using the same back-end. Yandex builds on the same back-end as Chrome (Yandex is front-end work on the Chrome/Chromium back-end). Pale Moon does _not_ build on the same back-end as Firefox.

**Comment by LimboSlam** [comment]
Hey everyone, sorry for not being the one to reply back to this request/issue I have started here at GitHub; I was recently hacked and just got a tackle on things with my system and so on.   

But anyways, everything @wolfbeast said is absolutely true @VeronicaGarcia, @dstorey and @NielsLeenheer. And to quote, "Pale Moon is not Firefox and never will be again."   

Sorry for the inconvenience @wolfbeast as I know you are greatly busy with the upcoming milestone release of Pale Moon v26.0.0, please forgive me.

**Comment by NielsLeenheer** [comment]
Sorry for the delay, see bug #447 for an explanation. 

I'll revisit this issue once I get version 8 up and running. I know the detection of Pale Moon and Goanna is working now, so the data should be there if I decide to add it to the verified results.

**Comment by LimboSlam** [comment]
@NielsLeenheer: Thanks for the reply back and and no worries. 

So yes Pale Moon is officially running off the Goanna engine. Um, the info above is a bit outdated, but we'll revisit this issue once you have v8 of the html5test finish.  

I hope for the best and keep up the good work. :+1:

**Comment by NielsLeenheer** [comment]
I don't have the time to maintain Pale Moon as a separate browser on HTMLtest. But the browser itself and version updates will be accepted as a PR as long as it is frequently maintained. See https://github.com/WebPlatformTest/Data for more information.

**Comment by LimboSlam** [comment]
Ok, sounds reasonable. Thanks @NielsLeenheer.
