### ISSUE TITLE
encode the passing tests in a barcode at the top

### ISSUE THREAD

**Issue by zcorpan** [WebPlatformTest/HTML5test#41]
<zcorpan_> http://www.google.se/search?hl=sv&safe=off&client=opera&hs=yuU&rls=en&tbs=prv%3A1&q=html5test&aq=f&aqi=&aql=&oq=&gs_rfai= - google scores 62 on html5test.com
<jgraham> zcorpan_: Hah!
<jgraham> zcorpan_: We should get them to encode the passing tests in a barcode in the area presented by google so we can determine what they pass

**Comment by NielsLeenheer** [comment]
lol!

**Comment by jgraham** [comment]
http://d-project.googlecode.com/svn/trunk/misc/qrcode/js/qrcode.js has a javascript QR code generator which could be read by many modern mobiles. You could try encoding the results as a URL somehow so that opening a specific URL will show the results in that browser.

**Comment by KieranP** [comment]
A comparison system of multiple browsers would be nice too, similar to Sunspider benchmarks.

**Comment by NielsLeenheer** [comment]
I've decided to go with sending scores directly back to the server instead of encoding them in a barcode.
