### ISSUE TITLE
Remove test for <input type="datetime-local">

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#411]
The type `datetime-local` got removed from the final [HTML5 specification for the `<input>` element](http://www.w3.org/TR/html5/forms.html#the-input-element) and is also [not included in the 5.1 spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-input-type). as far as I can see. So the test for it should be removed or at least marked as rejected and not give any points.

Sebastian

**Comment by dstorey** [comment]
This is supported by Chrome and has just very recently been added by Microsoft Edge (useful for accessibility and sites on mobile use it). With two (recent) interoperable unprefixed implementations, I wouldn't support removing it.

It is also still in the spec: https://html.spec.whatwg.org/multipage/forms.html#local-date-and-time-state-(type=datetime-local)

**Comment by SebastianZ** [comment]
Ok, I disregarded the WHATWG spec. So let's keep it then.

Sebastian
