### ISSUE TITLE
Update all browser data

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#413]
The browser data is getting seriously out of date. Microsoft Edge 13 and Safari 9 are stable and Firefox 41 and 42, Chrome 45 and 46 and Opera 31 and 33 have been released.

**Comment by 810** [comment]
Any update about this @NielsLeenheer ?

**Comment by NielsLeenheer** [comment]
HTML5test will be updated soon. Please see bug #447 for more information.
