### ISSUE TITLE
UC Browser Mobile application_Broken Authentication & Session management

### ISSUE THREAD

**Issue by vandanajais16** [WebPlatformTest/HTML5test#414]
1. Open UC Browser Mobile application
2. Open Facebook or other site & login into the website
3. Access some Authenticated page
4. log out from the application
5. Click on back option
6. Previously accessed authenticated pages is accessible (with out login)

**Comment by NielsLeenheer** [comment]
I don't think this has anything to do with HTML5test. Please report with UC Browser directly.
