### ISSUE TITLE
HTML5.1 feature testing

### ISSUE THREAD

**Issue by Dead2** [WebPlatformTest/HTML5test#415]
I would very much like to see testing of HTML5.1 features, since those are supposedly already partly available in browsers and the standard is set to be finalized in 2016. I have searched the web for information about what features are implemented in what browsers but it mostly amounts to rumours and such with very little reliable information. So I have no idea what browsers are most up-to-date regarding html5.1 support.

The specific feature I have been looking for is the sortable attribute to table. Ie: <table sortable> will allow sorting by each < th> without requiring javascript (and jquery). Table layout restrictions apply, but mostly don't use rowspan/colspan and it should be good it seems.

I see you have some html 5.1 items already (picture tag is one such I think), but a table showing all the html5.1-specific features together would be nice. Or a separate test for only new html5.1 features.

**Comment by dstorey** [comment]
As far as I can tell, here are the current changes between 5 and 5.1:

Elements:
- details / summary (included in HTML5Test)
- dialog (included in HTML5Test)
- menu / menuitem (included in HTML5Test)

Attributes not associated with the above:
- allowfullscreen (Fullscreen API included in HTML5Test)
- draggable / dropzone (Drag 'n' drop part of HTML5Test)
- microdata properties (included in HTML5Test)
- sortable / sorted (_not_ included in HTML5Test)

So it is only sortable tables from HTML5.1 that isn't included.

**Comment by NielsLeenheer** [comment]
Sortable tables is the only feature that is new in HTML 5.1 that isn't included in HTML5test. However sortable tables have already been removed from the WHATWG version of the spec and there are no plans to implement as far as I know.
