### ISSUE TITLE
'Uncaught ReferenceError: Test is not defined' on selecting My browser to compare

### ISSUE THREAD

**Issue by princejwesley** [WebPlatformTest/HTML5test#416]
Target URL: http://beta.html5test.com/compare/browser/index.html

![image](https://cloud.githubusercontent.com/assets/1622515/11817459/edf7ed2c-a37a-11e5-8341-5f292eaaa082.png)

Error location : https://github.com/NielsLeenheer/html5test/blob/version-7.0/scripts/reporting.js#L490

I tried `new Test7` instead of `new Test` and it seems working

**Comment by NielsLeenheer** [comment]
Fixed on alpha.html5test.com

**Comment by LMLB** [comment]
Seeing this again.

**Comment by LMLB** [comment]
Seeing this again on alpha.html5test.com

**Comment by LMLB** [comment]
These files still reference `/scripts/8/data.js` and/or `/scripts/8/engine.js`:
- `backend/templates/browser.html`
- `backend/templates/feature.html`
- `backend/templates/timeline.html`
