### ISSUE TITLE
BlackBerry bb10 score underrated in summaries, should be 461

### ISSUE THREAD

**Issue by pierre5018** [WebPlatformTest/HTML5test#417]
BB10 version 10.3.2 html5Test returns score of 461.
Comparisons and charts show only 449.

**Comment by pierre5018** [comment]
In desktop mode, bb10 browser scores 463
![img_20151225_082650]. Incorrect identification of terminal browser as. using Safari 7.1 on OS X Mavericks 10.. (https://cloud.githubusercontent.com/assets/5086279/11998804/85a76784-aae1-11e5-960f-a5be766a743c.png)

**Comment by NielsLeenheer** [comment]
Will be updated with the next release
