### ISSUE TITLE
Penalise points for only supporting vendor prefixed feature

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#421]
I’ve mentioned this elsewhere, but I think it deserves its own entry.

I think browsers should be penalised for only supporting vendor prefixed features. HTML5Test exists to promote implementation of HTML5 features, and promoting vendors to update their implementation to the unprefixed version is just as important. Otherwise authors start relying on the prefixed one, causing interop issues for other browsers (mostly non-webkit). Net result is often that non-webkit browsers have to implement a number of features twice, once for the unprefixed, and then have to reverse engineer the webkit version to be bug compatible (sometimes it is just adding a prefix alias, but often it is a different syntax and all sorts of different behaviour)

The situation is so bad that Opera, MS, and Mozilla have all had to implement webkit prefixes, and there is even a compat spec (that also takes effort to write and research) to define the WebKit behaviour and properties needed.

David Baron from Mozilla proposed removing support for prefixed properties on CSS3Test, and it is likely that that test will change to penalise prefixes. github.com/LeaVerou/css3test/pull/132

The only prefix I see as valid is the WebGL one as it is not a vendor prefix (it is more similar to the HTTP header x- prefix, and has strict rules from Kronos in that 100% of the test suite needs to pass. This doesn't impact interop as all vendors use the same prefix.

**Comment by NielsLeenheer** [comment]
I've just merged a branch that allows us to configure the amount of points that will be awarded for prefixes, buggy implementations and old implementations. 

Every feature in the `data.js` file has a value property. Usually this is just a number. But now it can also be an object with the maximum property. This is the number of points that gets awarded with true unprefixed support. And there is an award property that contains an object with optionally the points for `PREFIX`, `BUGGY` and `OLD` implementations.

For example:

```
{
    id:     'webaudio',
    name:   'Web Audio API',
    value:  { maximum: 5, award: { PREFIX: 3 } },
    urls:   [
                [ 'w3c', 'http://www.w3.org/TR/webaudio/' ],
                [ 'wp',  '/apis/webaudio' ]
            ]
},
```

**Comment by NielsLeenheer** [comment]
Done. Prefixes get less points on version 8.
See http://alpha.html5test.com.
