### ISSUE TITLE
Update current Edge version to 13 and upcoming version to 14.

### ISSUE THREAD

**Issue by vnicolici** [WebPlatformTest/HTML5test#423]
And while you're at it, rename Edge to Edge 12 for consistency.

Edge 13 has been the current version since November, and the latest Insider Preview for Windows 10 comes with Edge 14.

**Comment by 8825** [comment]
#423

**Comment by mgol** [comment]
I just wanted to report the same but I see it's already here. Any updates?

@8825 what do you mean by linking to the same bug?

**Comment by NielsLeenheer** [comment]
HTML5test will be updated soon. Please see bug #447 for more information.
