### ISSUE TITLE
Comparision for DIALOG element

### ISSUE THREAD

**Issue by pradeep1210** [WebPlatformTest/HTML5test#424]
Why is there no comparison for dialog element?
I found that Edge browser doesn't support the dialog element while the others do.

**Comment by dstorey** [comment]
Dialog is included

**Comment by pradeep1210** [comment]
I tried on both http://html5test.com and http://beta.html5test.com 
I couldn't find <dialog> element in the comparison list. 
Or maybe I am missing something. Can you please have a look at the attached screenshot?

![html5test](https://cloud.githubusercontent.com/assets/17339700/13346205/ac347bfa-dc8a-11e5-9975-98cbf13d34b0.png)

**Comment by pradeep1210** [comment]
OK I think I got it. It is buried inside the "Interactive elements" node.
