### ISSUE TITLE
Specification Link for Focus Ring out of date

### ISSUE THREAD

**Issue by anthonyxwatson** [WebPlatformTest/HTML5test#425]
The sub-test:

System focus ring support

has the following link to specification:

https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-drawsystemfocusring

which is a dead link (that subsection isn't on that page, which is really confusing, since the test name is already wonky, making it unclear whether the loaded spec page is at all related to that test.)

I managed to hunt around and finally find the following spec sub-section:

https://html.spec.whatwg.org/multipage/scripting.html#drawing-focus-rings-and-scrolling-paths-into-view

which I think is the newer equivalent to the current link.

Not that this is your problem or you have any control over this, but I was baffled on what a "system focus ring" might possibly be. It sounds like something really snazzy, like maybe some way to draw "rings" natively, or maybe form of female birth control. But as soon as I read the first line of the actual spec article, I rolled my eyes and thought "oh! like a halo around the element that's in focus! duh!" Seems like a really wonky name for the actual underlying concept. Especially since similar concepts exist in other parts of the web standard (namely "outline" for CSS) that fulfills the same objective in some browsers. So I vote we pick a name and stick with it, and make it something that doesn't vaguely sound like a skin condition that a dog might get!

**Comment by NielsLeenheer** [comment]
Fixed in commit 11b8196, including an updated test.
