### ISSUE TITLE
Stop awarding points for Web SQL Databases

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#427]
Web SQL has been rejected, yet it still awards 5 points.

**Comment by Kasijjuf** [comment]
Would you please provide a link to where it is officially rejected?

**Comment by dstorey** [comment]
You only get points for WebSQL if you don't support IndexedDB. It is perhaps a fair point it shouldn't get points as the spec was abandoned, but as all major browsers now support IndexedDB, it doesn't really impact anything.

**Comment by dstorey** [comment]
@Kasijjuf “Beware. This specification is no longer in active maintenance and the Web Applications Working Group does not intend to maintain it further.”

https://www.w3.org/TR/webdatabase/

**Comment by Studio384** [comment]
> Would you please provide a link to where it is officially rejected?

HTML5Test itself already says it is rejected. Anyway, see @dstorey's comment.

**Comment by NielsLeenheer** [comment]
I've decided to keep this as is. It really does not matter anymore, because all modern browsers support IndexedDB and you only get points for WebSQL if you don't support IndexedDB.
