### ISSUE TITLE
JS error when adding "my browser" on compare page of beta test

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#430]
Steps:

Go to http://beta.html5test.com/compare/browser/index.html
Click +
Add "My browser"

Expected:

browser to be added

Actual:

In some cases it is possible to get browser added (not sure exact repo yet), but it most often throws a JS error: 

ReferenceError: Can't find variable: Test
calculateColumnreporting.js:1:9135
(anonymous function)reporting.js:1:16409

Hit in calculateColumn

**Comment by dstorey** [comment]
This is dupe of #416

**Comment by NielsLeenheer** [comment]
Fixed on alpha.html5test.com
