### ISSUE TITLE
SQL Error on latests results page

### ISSUE THREAD

**Issue by Szpadel** [WebPlatformTest/HTML5test#431]
On page: https://html5test.com/results/latest.html, you are currently getting sql syntax error.
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY timestamp DESC LIMIT 100' at line 7`

Errors shouldn't be visible to user in production environment and you should investigate what what is wrong in generated $where, because there is potential SQL Injection vector.

**Comment by BetaFrey** [comment]
![error](https://cloud.githubusercontent.com/assets/14337809/15437935/5d0864e6-1e8f-11e6-99b1-6e609dc2311e.png)

**Comment by NielsLeenheer** [comment]
Fixed on alpha.html5test.com
