### ISSUE TITLE
The "Access the webcam" test is outdated

### ISSUE THREAD

**Issue by LMLB** [WebPlatformTest/HTML5test#432]
[`navigator.getUserMedia`](https://developer.mozilla.org/docs/Web/API/Navigator/getUserMedia) is deprecated and was replaced by [`navigator.mediaDevices.getUserMedia`](https://developer.mozilla.org/docs/Web/API/MediaDevices/getUserMedia)

**Comment by NielsLeenheer** [comment]
Fixed
