### ISSUE TITLE
drawFocusIfNeeded vs drawSystemFocusRing

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#433]
Test uses:

passed = typeof this.canvas.getContext('2d').drawSystemFocusRing != 'undefined';

No browser supports this.

However, non-IE/Edge browsers support the latest spec with drawFocusIfNeeded

**Comment by dstorey** [comment]
We (Edge) are now implementing this too using drawFocusIfNeeded for accessibility reasons

**Comment by NielsLeenheer** [comment]
Fixed
