### ISSUE TITLE
Microsoft Edge 13 is already published

### ISSUE THREAD

**Issue by car-meows** [WebPlatformTest/HTML5test#436]
And upcoming version of Microsoft Edge should be Edge 14. I think the reason caused this is this error occurred on Edge from html5test.com:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY timestamp DESC LIMIT 100' at line 7

**Comment by NielsLeenheer** [comment]
HTML5test will be updated soon. Please see bug #447 for more information.
