### ISSUE TITLE
Consider removing script execution events from V7

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#438]
Now removed from WHATWG version of HTML5. Still in W3C version, at least for time being. https://github.com/whatwg/html/commit/1a0b5e8377d59462e05a5cffda4b8592324a2785

If looking for something for the points,Web Payments and Web Authentication (née FIDO) are the kind of thing that would normally get included in HTML5Test, like all the other "Web *" specs. They're more work than the 1 point this would free up though. Then again there are other things that could get removed like HTML Imports, which I believe Firefox won't implement due to overlap with ES6 Modules.

**Comment by dstorey** [comment]
@NielsLeenheer  It's gone from W3C version too. Not in https://w3c.github.io/html/semantics-scripting.html#semantics-scripting but was in http://www.w3.org/TR/html5/scripting-1.html

**Comment by NielsLeenheer** [comment]
Deprecated. Not worth any points anymore, but still visible for now.
