### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by felipepessoto** [WebPlatformTest/HTML5test#439]

**Comment by DanAtkinson** [comment]
It would appear that way, wouldn't it? Last commit was done in August last year. Pull requests aren't being accepted or commented on.

You might get better mileage out of the compare feature on [Can I Use](http://caniuse.com/#comparison).

**Comment by NielsLeenheer** [comment]
This project isn't dead. But due to lack of time, it is not being updated at the moment. A big update is planned for this summer.

**Comment by NielsLeenheer** [comment]
See bug #447 for more information

**Comment by IgorTheLight** [comment]
It's not dead at all!
It's was updated just 4 years ago :-(
