### ISSUE TITLE
HTML5 does not mandate AAC, MP3 or h.264 codec support. 

### ISSUE THREAD

**Issue by hugovincent** [WebPlatformTest/HTML5test#44]
Patent-encumbered formats including AAC, MP3 and h.264 are not part of the HTML5 spec. It seems unfair to award points for any codecs at this point given that none are mandated by the spec (even more so because only Safari and Chrome (but not Chromium) support them). Perhaps (I hope) this will change in the future, possibly with Ogg Vorbis/VP8/WebM becoming mandated by the spec.

**Comment by NielsLeenheer** [comment]
Duplicate issue 3
