### ISSUE TITLE
remove addSearchProvider?

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#441]
- Edge deprecated this when switched over from IE. There is no plan to add it back.
- Chrome recently removed it: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/FXZloLz3Bao
- Opera and Safari do not support it.
- It has been deprecated from the WHATWG version of HTML https://github.com/whatwg/html/issues/713

@NielsLeenheer

**Comment by NielsLeenheer** [comment]
Fixed
