### ISSUE TITLE
Consider removing HTML Imports

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#442]
Firefox have said they will not implement this (related to the overlap with ES6 Modules): https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports

I don't think the actual spec has been deprecated though. 

Could possibly add ES6 Modules instead, but I'm not sure if that is testable as it isn't included in Kangax's table (or maybe just because it isn't ready), or just put the points towards some of the bigger Web \* specs coming out like Web Payments and Web Authentication (formally Fido 2.0)

@NielsLeenheer

**Comment by NielsLeenheer** [comment]
HTML Imports has been deprecated. It is no longer worth any points, but it is still visible. Might be removed completely in the next version.
