### ISSUE TITLE
Consider adding Web Authentication to V8

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#443]
**What is it?**
- A way to login using biometrics
- A way to login using 2 factor authentication

**Is it a standard?**

Yes. Originally put forward by FIDO Alliance as FIDO 2.0, it is now a W3C spec: https://w3c.github.io/webauthn/ Google and MS are spec editors along with PayPal, etc.

**Current support**
- Edge has an early prefixed implementation, but the API names have changed somewhat since it was implemented: https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/dev-guide/device/web-authentication/

**Reason to add**
- Many other "Web *" specs on HTML5Test already: Web Audio, WebGL, Web Components, WebRTC, etc.
- Passwords are tricky (see number of breaches over the last few years), and even when sites do a good job, users often do a bad job of selecting a good password. Web Authentication uses biometrics such as fingerprint reader (e.g. a standards way of doing what iOS and Android do for apps), and retina scan/face recognition (e.g. Windows Hello) to help solve this. Solving the password issue would be big for the web, so I think it deserves a place on the test.

**What to replace?**

I've filed a few things that have been deprecated from WhatWG version of HTML that could free up some points for this. There is also HTML Imports that Firefox won't implement.

**Comment by NielsLeenheer** [comment]
Under consideration.

Do you know if there is interest from other browser makers, apart from Microsoft?

**Comment by dstorey** [comment]
@NielsLeenheer Yes. Chrome has an implementation of FIDO U2F API which is a different spec and only related to two factor tokens(using keychains devices or whatever). This is the result of a FIDO 2 spec that goes beyond this and was moved to the W3C. Presumably with this and Google being editors they'll implement, especially when it fits in as part of a progressive web apps story along with web payments.

**Comment by NielsLeenheer** [comment]
Added, now available on http://alpha.html5test.com
