### ISSUE TITLE
Consider adding Web Payments (Payment Request API)

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#444]
**Overview**

A web API to allow merchants (i.e. web sites selling physical or digital goods) to easily accept payments from different payment methods with minimal integration.

**Standard**

https://w3c.github.io/browser-payment-api/specs/paymentrequest.html

**Justification**
- Fits in with the various web \* specs already included on HTML5Test
- Monetisation is one of the biggest concerns for web sites (and can be an alternative to just using ads to make money), and is one place where the web could be considered behind native apps, where monetisation is built into the store model.

**What it could replace**

As mentioned in the previous issue about Web Auth, there are around 4 points that could be removed from things now deprecated.

**Comment by NielsLeenheer** [comment]
Under consideration.

Do you know if there is interest from browser makers for this spec. Any implementation underway?

**Comment by dstorey** [comment]
@NielsLeenheer yes. I couldn't find the trackers in the various status sites but both Mozilla and Google are editors of the spec along with FB and MS. There has been noise in the media about Apple and payments through Apple Pay in the browser but I'm not sure if that is Web Payments or something non-standard as I'm not involved in the standards work.

**Comment by dstorey** [comment]
@NielsLeenheer here is Google's status entry: https://www.chromestatus.com/features/5639348045217792

**Comment by prajaybasu** [comment]
@NielsLeenheer here is Microsoft's progress on Web Payments : https://blogs.windows.com/msedgedev/2016/02/03/2016-platform-priorities/
And Edge 14 already has it as an experimental feature : https://onedrive.live.com/redir?resid=8BD10D41CDF4FFAA!188129&authkey=!APe0DxH2FpWlJvU&v=3&ithint=photo%2cpng

**Comment by NielsLeenheer** [comment]
Added, now available on http://alpha.html5test.com
