### ISSUE TITLE
The future of HTML5test

### ISSUE THREAD

**Issue by NielsLeenheer** [WebPlatformTest/HTML5test#447]
When I started this site more than 5 years ago my goal was to promote HTML5 for web developers and increase awareness, but most importantly to push browser makers into implementing these new standards. If this website in some way influenced browsers to implement just a single standard – to make just a single standard available to developers in all browsers – then I would say this website is was a big success. If this is the case I would say I have personally achieved my goals. Thanks to private conversations with people from all browsers makers, I know this website did make a difference. So I am happy.

But the site has not been updated for over a year. Not because I lost interest, but simply because life got in the way. Last year was a particularly busy one for me. First of all I suddenly got invited to speak at a conference and that lead to lots of other speaking opportunities and traveling. And more importantly due to a very serious health problem my wife had, I had to spend a lot of time visiting doctors and hospitals. Thankfully it looks like that is now behind us.

Over the years there have been many versions of HTML5test and the one that is now active on the main site is version 6. Version 7 is now running on beta.html5test.com and is already finished and has been collecting results more than 6 months. Every visitor that visits the main website actually runs both versions and the results for version 7 are submitted in the background. So I have a lot of data about version 7. And I could launch version 7 today. If I wanted to.

But releasing a new version is a lot of work, because all of the confirmed results have to be updated. And there are a lot of confirmed results. A lot! And simply updating the site without updating the results is something I do not think is a good way to go forward. And besides the work, the web platform moves very quickly so version 7 is already outdated. There are new standards that I want to include and that others that I need to drop. There are bugs that need to be fixed. That would basically mean that all the results that I collected of the last 6 months are useless. 

So I’ve decided to skip version 7 and work on version 8 instead. 

The goals for version 8 are not really ambitious, but it should make a nice update. Especially on top of everything that I already created for version 7. What I want to focus on:
- Make the site easier to update. Separate the score calculation from the tests, so it is easier to reuse data when the score calculation changes. 
- Maybe figure out a way so trusted collaborators can submit “official” results themselves and help update the site, so it doesn’t all come down to me. 
- Add new tests for new standards. 
- Push browser makers to move to non-prefixed versions of standards by giving prefixed implementations a penalty. 
- Restructure the project to make it easier to collaborate and invite others to help maintain it.

Over the summer I plan to work on the most immediate issues. The goal is to start collecting data as soon as possible, so we can launch the site after the summer. To do that I need help. Please open bugs for features that you think that should be included in the next version. PR are welcome too! Please file bugs for features that should be removed and which are buggy. I am going to use version 7 as a starting point, so please take a look at http://alpha.html5test.com and the `version-8.0` branch to see what is already there.

Cheers,
Niels Leenheer

**Comment by simevidas** [comment]
You could create a wiki page (here on GitHub) that lists the new tests that are planned for the next version, and also the ones that are proposed via Issues; that would make it easier to decide what else to propose 😅.

**Comment by NielsLeenheer** [comment]
OK, Thanks for the suggestion. 

You can find the full list of changes here: 
https://github.com/NielsLeenheer/html5test/wiki/Changes

**Comment by NielsLeenheer** [comment]
The new version of HTML5test has been released! Closing this issue.
