### ISSUE TITLE
Add test for requestIdleCallback

### ISSUE THREAD

**Issue by simevidas** [WebPlatformTest/HTML5test#448]
It’s an API for running JavaScript code in small chunks during periods when the main thread is idle, and it’s implemented in Chromium.

More info: https://developers.google.com/web/updates/2015/08/27/using-requestidlecallback

**Comment by NielsLeenheer** [comment]
Will be added to version 8

**Comment by NielsLeenheer** [comment]
Added, now available on http://alpha.html5test.com
