### ISSUE TITLE
Add a test for ES6 Modules

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#450]
# Would perhaps make sense to add ES6 Modules if HTML Imports are removed. ES Modules are what Mozilla want to go with instead for Web Components, and Edge is [currently implementing too](https://blogs.windows.com/msedgedev/2016/05/17/es6-modules-and-beyond/). According to https://www.chromestatus.com/features/5365692190687232 they have wide vendor consensus. There are at least two ES features: I18n API and Promises, so it wouldn't be totally out of the ordinary to include a ES feature on this test.

**Comment by NielsLeenheer** [comment]
Any idea how this should be feature detected? 

/cc @kangax

**Comment by ndelangen** [comment]
Do you want to test `<script type="module" />` support specifically?

**Comment by NielsLeenheer** [comment]
Yes, that is the idea.

**Comment by ndelangen** [comment]
You could use the fact that not supported type's won't load the src, and thus no onload event will be fired:

Here's my guess, but I have no browser that supports it to test on:

```
<body>
<script>

    var done = function () {
        // we're done testing
    };
    var success = function () {
        console.log(this.getAttribute('type') + ' is supported');
    };

    document.body.addEventListener("load", done, false);
</script>

<!-- works IF type=module is supported -->
<script type="module" onload="success.call(this)" src="about:blank"></script>

<!-- should NOT work -->
<script type="a-invalid-type" onload="success.call(this)" src="about:blank"></script>

<!-- should work -->
<script type="text/javascript" onload="success.call(this)" src="about:blank"></script>

<!-- should work -->
<script onload="success.call(this)" src="about:blank"></script>

</body>
```

**Comment by dstorey** [comment]
Should be able to test any test using Edge 14 with flags enabled (I believe it works with both import/export and `<script type="module">` depending on which you want to test for)

CCing @jdalton in case he has a good idea for how to test.

**Comment by jdalton** [comment]
You could just have it set to `false` by default and have a

``` html
<script type="module" src="module_test.js"></script>
```

which just sets it to true. It's an extra file but no fuss.

**Comment by NielsLeenheer** [comment]
Yeah, I was thinking about something similar. But I don't want it to be dependant on the network, so I guess using a data URL will work too.

**Comment by NielsLeenheer** [comment]
I've added a test for ES6 modules. Works in Edge 14 with Experimental JavaScript features enabled.

**Comment by NielsLeenheer** [comment]
Added, now available on http://alpha.html5test.com
