### ISSUE TITLE
Support Media Source Extensions tests

### ISSUE THREAD

**Issue by prajaybasu** [WebPlatformTest/HTML5test#453]
[This will improve scores for browsers like Edge 14 ](https://blogs.windows.com/msedgedev/2016/04/18/webm-vp9-and-opus-support-in-microsoft-edge/) because this is the default behavior for Edge 14 (copied from the link) :

Returns true :
- isTypeSupported ('video/webm; codecs="vp9"')
- isTypeSupported ('video/webm; codecs="vp9, opus"')
- isTypeSupported ('video/webm; codecs="opus"')
- isTypeSupported ('audio/webm; codecs="opus"')

And these will return “false”:
- isTypeSupported ('video/webm')
- isTypeSupported ('audio/webm')

VP9 works fine on YouTube for me at least. This kind of conflicts the results of html5test. 
Sorry if I blabbered something - I am not a hardcore web dev.

**Comment by dstorey** [comment]
MSE is already included on HTML5Test

**Comment by prajaybasu** [comment]
@dstorey  D'oh!

**Comment by NielsLeenheer** [comment]
Yes, we already test for the existence of MSE support. But I am interested in adding codec tests for MSE too. I already have this for the video and audio tag itself, but I suspect that codec support can differ between directly using the tags and MSE.

**Comment by dstorey** [comment]
Edge at least does support different codecs at the moment for MSE vs vanilla audio/video

**Comment by dstorey** [comment]
For that matter codecs supported by Web/ObjectRTC will be different to MSE & vanilla video element too

**Comment by NielsLeenheer** [comment]
Added codec detection for Media Source Extensions
