### ISSUE TITLE
Add test for :focus-within CSS pseudo-class

### ISSUE THREAD

**Issue by SebastianZ** [WebPlatformTest/HTML5test#455]
CSS Selectors Level 4 [defines a `:focus-within` pseudo-class](https://drafts.csswg.org/selectors-4/#the-focus-within-pseudo).

A test should be added for it.

Sebastian

**Comment by dstorey** [comment]
HTML5Test hasn't typically added CSS features (except where they are mentioned in the HTML5 spec like :valid, :invalid etc as they directly relate to new HTML5 features), so my vote would be not to include this. CSS3test covers this kind of thing well.

**Comment by SebastianZ** [comment]
Fair enough. I've filed https://github.com/LeaVerou/css3test/issues/142 instead.

Sebastian
