### ISSUE TITLE
date input type test returns incorrect value on Webkit

### ISSUE THREAD

**Issue by wwuck** [WebPlatformTest/HTML5test#46]
I opened html5test.com in the latest release of Safari 5 and it's reporting that <input type="date"> is supported.  When testing <input type="date"> on http://diveintohtml5.org/examples/input-type-date.html it is clearly not yet supported by webkit, as it shows a standard textbox.  I also tested the webkit nightly r59189 (2010-05-12), and Chrome 6.0.427.0 and get the same result.

Opera appears to be the only browser that currently supports <input type="date">.

**Comment by kalleboo** [comment]
That linked test works in Safari 5 (build 6533.16), it shows a paging control next to the text field that ticks it up and down by a day. http://xn--malmpeeps-37a.se/imgboard-img/88672f754328fb0cecf6bda2cbdb4bc6.jpg Unless the spec is more specific about how it ought to work?

**Comment by claudiobastos** [comment]
In Chrome (6.0.437.3 dev on Linux Ubuntu 10.04) the input tests are wrong too.
Date, datetime, time, ... seems ok on test, but don't work.
All of them are a normal text box
http://diveintohtml5.org/examples/input-type-time.html
http://diveintohtml5.org/examples/input-type-date.html

P.S. the check mark could link a "test input page" for each feature tested.

**Comment by NielsLeenheer** [comment]
The specification does not require specific widgets for each input type. A browser could just provide a text field and still fulfill every requirement of the spec.

However beta.html5test.com has some more tests that raise the bar somewhat for fields.
