### ISSUE TITLE
Break down menu type="context" to its two use cases, inc. button type=menu

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#461]
Currently menu type="context" is worth 2 points, while type="toolbar" is 1.

FF gets the full points but listed as partial, probably because it mostly doesn't work, for example only one menuitem item works as it doesn't treat menuitem as self closing, but adding a end tag is against spec, and it only works for right click style context menus. https://jsfiddle.net/z7zkqxky/

For primary click menus with button type="menu" it doesn't work at all. (this also makes menu type="toolbar" mostly worthless as it only works for plain LI list, rather than drop down toolbar buttons, which is the entire point of a toolbar menu). https://jsfiddle.net/8ytzpzrk/

So perhaps splitting context into menus invoked via the contenxtmenu attribute (right click) and menu attribute on button with type="menu" (primary click).

**Comment by NielsLeenheer** [comment]
Under consideration for version 9

**Comment by dstorey** [comment]
Closing this as menu is dead (except the most basic semantic list version of Menu)
