### ISSUE TITLE
add timeout as failsafe for dependency not loading

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#463]
There is a call to whichbrowser which is currently down. As there is a wait() function, this never resolves and stays in waiting state. Would be nice to have a timeout after a certain length of time and continue on its merry way if the server doesn't respond.

**Comment by NielsLeenheer** [comment]
As the backlist depends on browser detection, I am afraid that I can't just let the test run without it. But what I am probably going do is either install WhichBrowser locally as a failsafe. Or find a way to have a backup server for WhichBrowser itself.

**Comment by NielsLeenheer** [comment]
I'll revisit this after the upcoming release of version 8.

**Comment by rgl** [comment]
any update on this? I would love to try html5test but it rarely can load the page :-(

**Comment by LMLB** [comment]
api.whichbrowser.net is down again. ☹️

**Comment by LMLB** [comment]
and again

**Comment by NielsLeenheer** [comment]
Will be fixed in version 9
