### ISSUE TITLE
Cert error on https://alpha.html5test.com/

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#466]
IF one goes to the HTTPS version of the site, it generates a cert error, blocking the page: https://alpha.html5test.com/index.html 

(http://html5test.com will auto forward to HTTPS, so I hit this when editing URL to go to alpha version. It may be an issue which goes away when the alpha version moves to the bare www URL)

**Comment by NielsLeenheer** [comment]
This is a known issue. I can't use Let's Encrypt yet on this server and I don't think paying for a certificate for this temporary location makes much sense at this stage.
