### ISSUE TITLE
Add async/await to V8

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#468]
Originally I thought this made less sense, but now V8 includes Push API and a JS/scripting section, I think it completes the test:
- AppCache was reduced from 5 -> 3. Service Workers (10 points) is the new way of offline
- HTML Imports reduced from 2 -> 0. ES Modules (3 points) is the new way
- Server-Sent Events hasn't been adjusted. Push API is the new service worker era replacement (2 points). We're [prioritizing Push](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/p) over SSE for obvious reasons. There is much less reasons to implement/use SSE once Push is implemented.
- Promises was the new hotness for JS APIs and added to the test a while ago. Async/Await builds on top of this and is one of the biggest new ES features that will change how JS is written. It makes async programming easier to write and code easier to read. It is one of the top C#/.net features that devs on that side of the fence love.

Which is the long way of proposing:
- Reduce SSE to 2 or 3 points
- Add Async/await for 2 or 3 points (latter would match promises)...perhaps split between detecting async functions and the await keyword, but they go together.

Spec: https://tc39.github.io/ecmascript-asyncawait/
Post: https://blogs.windows.com/msedgedev/2015/09/30/asynchronous-code-gets-easier-with-es2016-async-function-support-in-chakra-and-microsoft-edge/

**Comment by dstorey** [comment]
Love letter from Google showing other vendor interest and importance: https://jakearchibald.com/2014/es7-async-functions/
Also https://www.twilio.com/blog/2015/10/asyncawait-the-hero-javascript-deserved.html

**Comment by NielsLeenheer** [comment]
I've added async/await for 3 points. I've also added classes, arrow functions and template strings.

I haven't changed Server-Side Events, because I think the use case is quite different from Push. And from personal experience I think it is very useful to have.

**Comment by dstorey** [comment]
@NielsLeenheer ok, thanks! They are both full duplex messaging, but I guess one requires a service worker and will work when browser isn't open, while the other doesn't in both cases.

It looks like the test isn't working in Edge when async/await is enabled (via the experimental JS flag), while it is on Kangax. I've not looked to see if that is a bug in the test or our implementation.

In reducing SharedWorker and TypedArrays for this, and adding the other important ES6 features, it makes me think that to round this off [SIMD.js](http://tc39.github.io/ecmascript_simd/) should probably be added. Like async/await it is the other big new ES7 feature and also isn't supported anywhere by default (Edge has it behind a flag). It is heavy promoted by Mozilla (along with ASM.js) and Intel, and it is somewhat related to TypedArrays which are already included. I'd probably reduce SharedWorkers to zero for that, as Safari removed it and doesn't look like adding it back and you've already reduced its points twice in sucession. Perhaps also a point form IndexedDB if it a 2 point feature (probably as it is a big feature) as that has a uneven 21 point score.

**Comment by NielsLeenheer** [comment]
The async/wait test failing is my mistake.
