### ISSUE TITLE
Streaming should include Adaptive Bit Rate solutions (0 points)

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#469]
There is now a section on streaming codecs in the test for MSE. There should be tests (zero points like the codecs) for the adaptive bit rate solutions:
- HTTP Live Streaming (HLS). A non-standard Apple solution (in much the same way as WebM and WebP are non-standard Google solutions). Works in Safari and Edge. Apple examples: https://developer.apple.com/streaming/examples/ . Details: https://develop (er.apple.com/streaming/
- MPEG DASH. The standards based solution. Supported by Edge. Examples: http://rdmedia.bbc.co.uk/dash/ondemand/bbb/ & http://dashif.org/test-vectors/ Info: http://www.bbc.co.uk/rd/blog/2013/09/mpeg-dash-test-streams  https://msdn.microsoft.com/en-us/library/dn551370(v=vs.85).aspx

**Comment by NielsLeenheer** [comment]
I'm more than happy to add these, if there are simple and reliable ways to feature detect this.

**Comment by dstorey** [comment]
MPEG-DASH can be detected by the following:

``` JS
video.canPlayType('application/dash+xml')
```

HLS has a bunch of different mime types. The two recommended are

``` JS
video.canPlayType('application/vnd.apple.mpegURL') || video.canPlayType('audio/mpegurl');
```

https://jsfiddle.net/9dobanoa/1/

**Comment by NielsLeenheer** [comment]
Created a special section for streaming. Added it there.
