### ISSUE TITLE
Mark Internet Explorer 11 as current

### ISSUE THREAD

**Issue by mgol** [WebPlatformTest/HTML5test#472]
Shouldn't IE 11 be marked as "Current", not "Older"? There is no newer version, the browser still receives security updates and [sometimes even bugfixes](https://connect.microsoft.com/IE/feedback/details/1763802/location-origin-is-undefined-in-ie-11-on-windows-10-but-works-on-windows-7) and other sites like Can I Use [list IE 11 as current](http://caniuse.com/#feat=css-supports-api).

**Comment by NielsLeenheer** [comment]
I'm hesitant to do that. It is the latest version, but it's not really current anymore. I'm thinking about combining Internet Explorer and Edge in the same column, but not sure yet how to do that yet.

**Comment by NielsLeenheer** [comment]
I decided to combine the columns to show the relationship between the two and to make it clear that one succeeded the other.

<img width="881" alt="screen shot 2016-07-12 at 13 21 53" src="https://cloud.githubusercontent.com/assets/233230/16765331/b576a46c-4833-11e6-955d-98e02a26cbd0.png">

**Comment by mgol** [comment]
One thing to remember - Edge will get new versions, the old ones will become unused & unimportant and IE 11 will live on for a while. But I guess this may not be a problem here as you may always show only a few latest Edge versions and then IE.

**Comment by NielsLeenheer** [comment]
In the current situation IE 11 will disappear when Edge 16 is officially released. I'm sure this will take a while and in the mean time IE 11 use will drop even more. But when that time comes, I may decide to drop Edge 12 in favor of IE 11.
