### ISSUE TITLE
Edge doesn't pass test for Classes, Template Strings, or Arrow Functions in Compare view

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#473]
Edge supports all these features (except Edge12 which doesn't support Classes) and they pass as expected on the main test, but when going to the Compare page, it fails the tests for classes, template strings and arrow functions in the "My Browser" column.

**Comment by NielsLeenheer** [comment]
It looks like the `eval()` that is needed for this test is blocked by CSP:

```
Resource violated directive 'default-src 'unsafe-inline' data: *' in Content-Security-Policy: script eval. Resource will be blocked.
```

The weird thing is, this page does not use CSP. It is used by an iframe loaded by this page, but only that specific URL has CSP headers set.

**Comment by NielsLeenheer** [comment]
Found it. The CSP headers were set at a different location - a left over from the old version.
