### ISSUE TITLE
Timeline page results are wrong for Edge 12

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#475]
Some of the results on the Timeline pages appear to be wrong. For example, the info on [Edge 12](http://html5test.com/results/desktop/timeline/edge.html) ~~and [Chrome 16](http://html5test.com/results/desktop/timeline/chrome.html)~~ appear to be in "reverse" indicating support being dropped instead of being added as it should be.

**Comment by NielsLeenheer** [comment]
The data on Chrome is correct. In early versions some features were shipped, deemed not ready yet and removed again.

Edge is a known issue that I'm working on. The timeline contains an experimental build with all flags enabled all the way at the bottom which shouldn't be there.

**Comment by NielsLeenheer** [comment]
Fixed

**Comment by Studio384** [comment]
This problem is now showing up again for Internet Explorer 6.

**Comment by NielsLeenheer** [comment]
I'm not seeing this anymore, can you retest?

**Comment by Studio384** [comment]
Yes, it's gone now.
