### ISSUE TITLE
On "Mobile", results for all versions of Windows Phone are missing in the overview

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#476]
The mobile-page doesn't show Windows Phone 7.5 and 8.0 and Windows 10 Mobile in the overview and score-sections, despite results for these versions being available in the timeline.

**Comment by NielsLeenheer** [comment]
Yes, this is an issue I still haven't made my mind up about.

Windows Phone used to have a single version of IE for a single version of the OS. But nowadays Edge is updated more regularly while the operating system version remains the same. That is why there in no Windows 10 Mobile in that list, but instead a separate Edge 13.

What I ideally want to do is show the relationship between the two, but I don't know yet how exactly I am going to do that.

**Comment by Studio384** [comment]
I think that just using the Edge version number (and IE) would make more sense. Another solution would be to use as version 1511 and 1607, etc. for Windows 10 Mobile.

**Comment by NielsLeenheer** [comment]
I decided to combine the columns and start using the Internet Explorer version numbering.

<img width="893" alt="screen shot 2016-07-12 at 13 19 45" src="https://cloud.githubusercontent.com/assets/233230/16765265/65bbdd20-4833-11e6-8d29-1e405e025c3e.png">
