### ISSUE TITLE
"Peer To Peer" displays wrong (45) max score instead of 60, total max score is 570, not 555

### ISSUE THREAD

**Issue by Studio384** [WebPlatformTest/HTML5test#485]
The "Peer To Peer" panel on the home page shows there is a maximum score of 45, but all items in it count up to 60 as the maximum score.

As a result, the maximum score displayed on the top of the page isn't 555 either, but 570.

**Comment by NielsLeenheer** [comment]
This is deliberate. Object RTC and WebRTC are both individually worth 15 points, but together the total of these two will never be more than 15 points. Supporting either of these two standards is enough to get the maximum score.

**Comment by Studio384** [comment]
![capture](https://cloud.githubusercontent.com/assets/1693592/17626934/ab778348-60af-11e6-9278-7da22f5250de.PNG)
Nope, it's broken. If both WebRTC and ObjectRTC are supported, 30 points will get awarded.

**Comment by Studio384** [comment]
This is Edge 14.14901 with WebRTC flag enabled, by the way.

**Comment by NielsLeenheer** [comment]
Fixed
