### ISSUE TITLE
Logic is broken for supporting either ORTC or WebRTC

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#489]
Edge is implementing WebRTC for backwards compatibility with sites which use that older API. This can be enabled with a flag in Edge15 (now in public preview). But Edge15 gets 500 overall and 48/45 in peer to peer as both are counted towards the total.

**Comment by Studio384** [comment]
#485 describes the same issue.

**Comment by NielsLeenheer** [comment]
Fixed
