### ISSUE TITLE
Add FLAC to Streaming and Audio sections

### ISSUE THREAD

**Issue by evieluvsrainbows** [WebPlatformTest/HTML5test#493]
Since Firefox has added support ([Source](http://www.phoronix.com/scan.php?page=news_item&px=FLAC-For-Firefox)) for the FLAC audio codec, I think FLAC should be added to the Streaming and Audio sections, and browsers should be rewarded some points if they support it.

**Comment by afmenez** [comment]
No codec currently award any points, so this one shouldn't either.

**Comment by afmenez** [comment]
Chrome 56 was released today with FLAC support too.

**Comment by cyrilst** [comment]
I also really think FLAC should be added to the Audio Codecs list.

**Comment by NielsLeenheer** [comment]
FLAC was added for version 9.0, but only for audio, not streaming. I don't think Ogg is supported by any browser using any codec for streaming.
