### ISSUE TITLE
Update Safari versions

### ISSUE THREAD

**Issue by moderndeveloperllc** [WebPlatformTest/HTML5test#494]
macOS 10.12 introduced Safari 10.0, which is also available for macOS 10.11. This should be the "Current" browser with Safari 10.1 as the "Upcoming".

**Comment by afmenez** [comment]
Safari 10.1 is already the current version.

**Comment by moderndeveloperllc** [comment]
@afmenez The current for macOS 10.12.2 is Safari 10.0.2. It looks like the site has been updated since I lest checked. Closing now.
