### ISSUE TITLE
Consider removing @dropzone

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#498]
There is a Blink intent to deprecate for the dropzone attribute https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/rdGvTDPU7mM

There is a proposal to remove it from the WhatWG version of the spec:
https://github.com/whatwg/html/issues/2331#issuecomment-281336838

CC / @NielsLeenheer

**Comment by dstorey** [comment]
Now removed from the spec

**Comment by dylanmtaylor** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=688943 looks like Chrome pulled the prefixed version
