### ISSUE TITLE
Consider adding IntersectionObserver

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#499]
Now that the dropzone attribute has been removed from HTML5, assuming it is removed from the test, 1 point is freed up.

A good potential replacement is IntersectionObserver. It isn't widely supported yet (Chrome only so far and in development for Edge) and is incredibly important for performance. Currently ad providers do things like check 60 times a second (or more) if an ad is in view to report back to advertisers if the ad was viewed (they only pay if the ad is visible). This happens for every ad on the page, which is one of the major reasons ads slow down the browser.

IntersectionObserver is feature designed to combat this so that ads can be performant without resorting to these hacks.

**Comment by dstorey** [comment]
Spec https://wicg.github.io/IntersectionObserver/

**Comment by NielsLeenheer** [comment]
IntersectionObserver was added in commit cc2054745e44d0180d51c1a8d90311a6c91f6536
