### ISSUE TITLE
No coverage since Firefox 48...

### ISSUE THREAD

**Issue by emberdart** [WebPlatformTest/HTML5test#500]
... and 52 is the current stable. Are these broken tests?

Cheers

**Comment by dstorey** [comment]
you can update browsers at https://github.com/WebPlatformTest/Data

**Comment by danielgp** [comment]
I have just created a new pull request with latest desktop releases for Chrome, Firefox and Opera. I hope will be accepted soon and we'll see it in action.

**Comment by dstorey** [comment]
@NielsLeenheer this can be closed now
