### ISSUE TITLE
ES2015 module test fails

### ISSUE THREAD

**Issue by WebReflection** [WebPlatformTest/HTML5test#502]
![screenshot from 2017-04-05 14-32-02](https://cloud.githubusercontent.com/assets/85749/24707739/b0d4e6d4-1a0c-11e7-8f93-13ca15be7917.png)

It looks like the only engine that really supports ES2015 modules also has CORS policy enabled by default so that inline eval-scripts are not allowed.

A `try/catch` wouldn't work neither so you rather try to load a `./module.js` file with similar logic but a static callback name.

**Comment by NielsLeenheer** [comment]
It doesn't look like you override this behaviour using CSP headers. So loading an external file would be the easiest solution indeed.

**Comment by NielsLeenheer** [comment]
Fixed for version 9.0

**Comment by WebReflection** [comment]
did such version ship?

I keep seeing a NO under module support

![screenshot from 2017-09-20 17-32-09](https://user-images.githubusercontent.com/85749/30652837-b2b3104c-9e29-11e7-8713-1f7301693a6d.png)

**Comment by WebReflection** [comment]
no answers in moths, closing this to remove it from my issues

**Comment by dstorey** [comment]
I know this has been fixed in V9 but Chrome started passing this in V8 and we looked at it and fixed the bug that made it not work, so my thought is the fix should be reverted and use the V8 test so that other browsers fix the bug.
