### ISSUE TITLE
Remove menu element

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#505]
menu element type context and toolbar have been removed from WhatWG HTML:
https://github.com/whatwg/html/pull/2742

HTML5Test should either remove both tests, or remove context and simplify the toolbar test. For example Edge and perhaps other browsers support HTMLMenuElement interface as a fancy list like it is in spec, but don't support setting type attribute to toolbar. As the type attribute is no longer in the spec, this is now correct behaviour.

**Comment by NielsLeenheer** [comment]
Removed, thanks for the PR
