### ISSUE TITLE
Webkit Browsers Support HTML5 Ruby, but reported as not support.

### ISSUE THREAD

**Issue by venj** [WebPlatformTest/HTML5test#51]
According to Wikipedia(http://tinyurl.com/yc4baqy) and my test, Webkit Browsers support HTML 5 Ruby tag(ruby, rt, rp), but reported as not support.

I tested with Safari 5 Mac and Chrome 6.0.472.4 dev for Mac, HTML 5 Ruby actually works.

updated: The issue is still persist in html5 test beta(http://beta.html5test.com/).

**Comment by NielsLeenheer** [comment]
Ruby does work in Webkit, but they fail the test because they do not report back the correct display type for ruby elements.

**Comment by NielsLeenheer** [comment]
Filed the following bug: 
https://bugs.webkit.org/show_bug.cgi?id=44515

**Comment by eseidel** [comment]
Hyatt's comments in that bug, suggest that the test suite should be altered instead of implementations (at least for now).
