### ISSUE TITLE
Hang when whichbrowser.net is not responding

### ISSUE THREAD

**Issue by stretch327** [WebPlatformTest/HTML5test#510]
Today whichbrowser.net is apparently down which is making html5test.com hang. It would be nice if there was a fallback in this case.

**Comment by Djfe** [comment]
Still happening! :(

**Comment by Vasilich** [comment]
today is again the case, where whichbrowser.net is unavailable, so tests cannot be started

**Comment by NielsLeenheer** [comment]
Will be fixed in version 9
