### ISSUE TITLE
Consider removing Directory Upload 

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#515]
While this is not totally abandoned, we implemented the webkit-directory attribute as the reality of the web is that it is used on too many sites to ignore, and has even made it into a spec now :( Having another solution will make it harder for this proposal to get traction, It may be worth removing it from the test and using the point for something else already merged into v9 or another proposal in the issues list like minLength or relList

**Comment by NielsLeenheer** [comment]
Removed, thanks for the PR
