### ISSUE TITLE
Tests for <details> and <summary> tags

### ISSUE THREAD

**Issue by john76** [WebPlatformTest/HTML5test#53]
Do you test support of <details> and <summary>

 tags by browsers? These seem to be quite important for disambiguation, and hence for search.

**Comment by paulirish** [comment]
I believe the test for them is as easy as
    ('open' in document.createElement('details'))

**Comment by NielsLeenheer** [comment]
Added to beta.html5test.com

**Comment by john76** [comment]
Thanks for adding these to the beta.

Strange thing, but the test says (FF4, Safari, Chrome, IE9) that <details> is supported, while <summary>

 is not, though <details> can only be a child of a <summary>

. Something wrong with the test or with the browsers? :)
