### ISSUE TITLE
Potential Scoring Issue

### ISSUE THREAD

**Issue by Justinius** [WebPlatformTest/HTML5test#533]
When comparing browsers there seems like there might be a scoring inconsistency.

Selecting Chrome 64/Edge 17/Edge All Flags

Under Peer to Peer Chrome gets 40 and Edge gets 33, but by just adding up the points it seems Edge is being under evaluated by 15 points. 

The ObjectRTC API for WebRTC doesn't seem to count. Its listed as 15 points and proposal, but the other proposed standards are counted towards the point total.

**Comment by Studio384** [comment]
That is expected behavior. A browser can only get points for WebRTC or ORTC, not for both, despite supporting both.
