### ISSUE TITLE
FileReader / BlobReader slice test

### ISSUE THREAD

**Issue by andrewfenn** [WebPlatformTest/HTML5test#55]
I'm using the File API's Binary Slice functionality in an app. Firefox hasn't implemented it where as Chrome has however Firefox passes all the File API tests.

**Comment by ebidel** [comment]
FF 5 has slice implemented (https://developer.mozilla.org/en/DOM/Blob). The method  has also been prefixed in webkit and moz because it has changed semantics:

file.webkitSlice
file.mozSlice

**Comment by andrewfenn** [comment]
It does now, it didn't when I first made this bug report.

That's besides the point however. There should be a test for it, this isn't something firefox specific, I just mentioned firefox because it was broken at the time I made this report.
