### ISSUE TITLE
Test for "mark" element bogus

### ISSUE THREAD

**Issue by zcorpan** [WebPlatformTest/HTML5test#56]
```
                var element = document.createElement('mark');
                document.body.appendChild(element);

                group.setItem({
                    title:  '<code>mark</code> element', 
                    url:    'http://www.w3.org/TR/html5/text-level-semantics.html#the-mark-element',
                    passed: typeof HTMLElement != 'undefined' && element instanceof HTMLElement && (color = this.getStyle(element, 'background-color')) && (color == 'yellow' || color == 'rgb(255, 255, 0)'), 
                    value:  1
                });
```

There are two things that are bogus here. First, the color yellow can be represented in a number of ways other than those two. For instance, Opera returns #ffff00 for yellow. Second, since the rendering section in HTML5 is non-normative, a conforming implementation could decide to use a completely different color than yellow, or decide to use a forground color instead, or an outline, or blinking text-decoration, or whatever.

Maybe all browsers are going to use a background color for "mark" anyway, so a practical test would be to check that the element has a background color other than the default (which is 'transparent').

**Comment by NielsLeenheer** [comment]
This issue will be fixed in the next release (currently at alpha.html5test.com)
