### ISSUE TITLE
IE9beta & PP6 show 133, not 377 total points in beta HTML5 test

### ISSUE THREAD

**Issue by flamespaceship** [WebPlatformTest/HTML5test#58]
The beta HTML5 test works for Minefield, Webkit, Chrome and Opera, but seems to have a problem with IE9beta.  While other browsers run tests adding up to 377 points, IE9 apparently only runs a subset, displaying a maximum 133 points on the results page.  IE9 seems to work the same as the other browsers in showing the full 300 points on the released version of the HTML5 test, so it is something new to the beta version of the test.

**Comment by wwuck** [comment]
It's even worse now.  The latest IE9 beta scores 21 and 1 bonus point out of a total of 31 points.

**Comment by NielsLeenheer** [comment]
Fixed
