### ISSUE TITLE
HTML6?

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#580]
Why does the URL <http://html6test.com> reference this Git?
This is obviously an HTML5 testing suite, was that some sort of joke?
HTML6 doesn't, any may never exist as far as I know.

**Comment by mpopp75** [comment]
If I remember correctly Niels set this up for an April fools prank a few years ago. Maybe it survived until today.

**Comment by ghost** [comment]
@mpopp75 Ah, that would explain a lot, thanks for clearing that up! A lot of people did the same around that time regarding "HTML6" jokes.
