### ISSUE TITLE
Please add a proper test for the menu tag

### ISSUE THREAD

**Issue by jswartwood** [WebPlatformTest/HTML5test#59]
I'm sure there is a lot of work involved in getting a set of tests for the menu tag (since it is a relatively complex tag.)  With select tag misuse (javascript/commands) and the huge inconsistencies across browsers (styling, etc), menu is potentially one of the most exciting tags in the html5 spec.

**Comment by NielsLeenheer** [comment]
Added test to beta.html5test.com
