### ISSUE TITLE
WebGL test for Firefox is not always accurate

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#65]
On Windows, with graphics hardware acceleration on, the test tells me that both Chrome 10.0.628.0 and Firefox 4.0b8 support WebGL - and they both do. 

With hardware acceleration turned down or off neither browser can display WebGL since hardware acceleration or alternative software support (like mesa) is required. However, the test now tells me that Firefox 4.0b8 doesn't support WebGL. It does support WebGL, it's just that it can't be activated without appropriate hardware/software support on the host computer. The chrome test continues to say that it supports WebGL even when it can't display it because hardware acceleration has been turned down.

**Comment by paulirish** [comment]
PMS: can you tell me if the results of Modernizr match your expectations?
http://modernizr.github.com/Modernizr/output.html  its #4.

If it's true then https://cvs.khronos.org/svn/repos/registry/trunk/public/webgl/sdk/demos/google/san-angeles/index.html should work.
