### ISSUE TITLE
incorrect spec link for "Embedding custom non-visible data" (dataset)

### ISSUE THREAD

**Issue by nickolay** [WebPlatformTest/HTML5test#66]
The "Embedding custom non-visible data" test links to http://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data, which doesn't exist at this moment https://github.com/NielsLeenheer/html5test/blame/master/index.html#LID1530

The proper link appears to be http://www.w3.org/TR/html5/elements.html#dom-dataset

**Comment by NielsLeenheer** [comment]
Fixed in next release
