### ISSUE TITLE
Invalid tests for storage.

### ISSUE THREAD

**Issue by ChALkeR** [WebPlatformTest/HTML5test#72]
`passed:    'localStorage' in window` is not a correct test for localStorage.

Because window.localStorage is set to null value in kdewebkit for me, but not undefined.
It does not work, of course, but the test passes.

**Comment by NielsLeenheer** [comment]
I would argue that this is a bug in kdewebkit. If a browser does not support localStorage, it should be undefined and not null. Nevertheless it does cause problems for detection, so I'll try to add a workaround.

**Comment by NielsLeenheer** [comment]
Added a workaround, please retest with beta.html5test.com
