### ISSUE TITLE
getStyle method breaks on hyphenated arguments

### ISSUE THREAD

**Issue by miketaylr** [WebPlatformTest/HTML5test#79]
Trying to figure out why Opera doesn't pass the `<mark>` test (at https://github.com/NielsLeenheer/html5test/blob/master/index.html#L1193). Turns out the `getStyle` utility method breaks on a property like `background-position` as `currentStyle` only accepts camelCased arguments:

https://github.com/NielsLeenheer/html5test/blob/master/index.html#L1100

If you pass `backgroundPosition` to `getStyle` in the `<mark>` test, Opera passes. I have no idea if IE8 or 9+ support this element, but if and when they do, this test will give a false negative for this same reason.

One approach would be write a `camelCase` utility and call that on any input to `currentStyle`. Here's one modified from MooTools (https://github.com/mootools/mootools-core/blob/master/Source/Types/String.js#L35): 

```
function camelCase(str){
  return str.replace(/-\D/g, function(match){
    return match.charAt(1).toUpperCase()
  })
}
```

Another fix would be to move the `getComputedStyle` branch before the `currentStyle` branch, and Opera will return the correct result based on that. But it might be nice to fix this bug too. :)

**Comment by NielsLeenheer** [comment]
Added the camelCase function to getStyle to make sure any properties from currentStyle are retrieved in camel case. Changes can be seen on beta.html5test.com.
