### ISSUE TITLE
Test form input attributes "height" and "width"

### ISSUE THREAD

**Issue by rasamassen** [WebPlatformTest/HTML5test#80]
Per http://www.w3.org/TR/html5/the-map-element.html#attr-dim-height
Per http://www.w3.org/TR/html5/the-input-element.html#the-input-element

Currently only IE supports the attributes "height" and "width" (though incorrectly).

**Comment by NielsLeenheer** [comment]
Added a test for height and width attributes, and a check to see if the element is set to the correct width and height when it is used.
