### ISSUE TITLE
drag and drop not supported on iOS

### ISSUE THREAD

**Issue by htmljenn** [WebPlatformTest/HTML5test#86]
Like contenteditable, iOS has the draggable attribute, but it doesn't support it. 

Reference: http://developer.apple.com/library/safari/#documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW19

So you have to detect iOS and mark it as "no".

**Comment by NielsLeenheer** [comment]
Disabled draggable for iOS and Andriod on beta.html5test.com
