### ISSUE TITLE
Allow to compare and "diff" two or more results. 

### ISSUE THREAD

**Issue by kamathln** [WebPlatformTest/HTML5test#94]
Latest firefox trunk scored only 289 +9  ..compared to latest nightly 312 +9 .. It would be nice to take two results and compare them side by side .. Just like one of the js performance profilers.. cant remember,.. must be sunspider ..

**Comment by joroldan** [comment]
For example in Sunspider, you get a different URL for each test, and then you can use it to compare several resault. In this case, comparing to the most common browsers would be enought. For example in "Other browsers" tab, it would be awesome if you add a link to compare that browser results with your own results or something similar.
